# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel`.

module Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel::NEUTRAL = 2
Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel::TRUSTED = 3
Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel::UNKNOWN_TRUST_LEVEL = 0
Hydro::Schemas::Github::Sponsors::V1::FraudSystemActionProhibited::TrustLevel::UNTRUSTED = 1
