# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Github::DependencySnapshotsApi::V2::AsyncCreateSnapshotResponse`.
# Please instead update this file by running `bin/tapioca dsl Github::DependencySnapshotsApi::V2::AsyncCreateSnapshotResponse`.

class Github::DependencySnapshotsApi::V2::AsyncCreateSnapshotResponse
  sig { void }
  def initialize; end
end
