#!/bin/bash
set -eu
# The vendored Git does not use the config in /etc/gitconfig.
# This means the VSCode credential helper is not used.
# To work around this, we copy the Git config from the system config to the vendored config.
git config --file ./vendor/git-core/etc/gitconfig credential.helper \
  "$(git config --file /etc/gitconfig credential.helper)"
