#!/bin/bash

###
# Due to the bug in VSCode initialization [https://github.com/microsoft/vscode-internalbacklog/issues/1420],
# the vscode git credential helper does not work correctly due to environment variables not properly set.
# This breaks all git credential providers registered by vscode extensions (e.g. `git`, `github`) and does
# not trigger GitHub OAuth flow in the browser. This file sets the environment variables to fix the issue.
###

# function to find VSCode git credential helper file
function find_vscode_gch_file {
    echo $(find ~/.vscode-remote/bin/ -type f -name $1 | head -n 1)
}

# function to find a socket file in `/tmp/` folder
function find_socket {
    echo $(find /tmp -maxdepth 1 -name "$1" | head -n 1)
}

# recompute the variables
if [ -z "$GIT_ASKPASS" ] || [ -z "$VSCODE_GIT_ASKPASS_MAIN" ] || [ -z "$VSCODE_GIT_ASKPASS_NODE" ] || [ -z "$VSCODE_GIT_IPC_HANDLE" ]; then
    echo "Fixing up VSCode Git Credential Helper.."
    export GIT_ASKPASS=$(find_vscode_gch_file "askpass.sh")
    export VSCODE_GIT_ASKPASS_MAIN=$(find_vscode_gch_file "askpass-main.js")
    export VSCODE_GIT_ASKPASS_NODE=$(find_vscode_gch_file "node")
    export VSCODE_GIT_IPC_HANDLE=$(find_socket "vscode-git-*.sock")
fi
