# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Authnd::Proto::IssueTokenResponse`.
# Please instead update this file by running `bin/tapioca dsl Authnd::Proto::IssueTokenResponse`.

class Authnd::Proto::IssueTokenResponse
  sig do
    params(
      error: T.nilable(String),
      expires_at_time: T.nilable(Google::Protobuf::Timestamp),
      result: T.nilable(T.any(Symbol, Integer)),
      token: T.nilable(String),
      token_id: T.nilable(Integer)
    ).void
  end
  def initialize(error: nil, expires_at_time: nil, result: nil, token: nil, token_id: nil); end

  sig { void }
  def clear_error; end

  sig { void }
  def clear_expires_at_time; end

  sig { void }
  def clear_result; end

  sig { void }
  def clear_token; end

  sig { void }
  def clear_token_id; end

  sig { returns(String) }
  def error; end

  sig { params(value: String).void }
  def error=(value); end

  sig { returns(T.nilable(Google::Protobuf::Timestamp)) }
  def expires_at_time; end

  sig { params(value: T.nilable(Google::Protobuf::Timestamp)).void }
  def expires_at_time=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def result; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def result=(value); end

  sig { returns(String) }
  def token; end

  sig { params(value: String).void }
  def token=(value); end

  sig { returns(Integer) }
  def token_id; end

  sig { params(value: Integer).void }
  def token_id=(value); end
end
