# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Launch::Services::Runnergroups::RemoveRunnerRequest`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Launch::Services::Runnergroups::RemoveRunnerRequest`.

class GitHub::Launch::Services::Runnergroups::RemoveRunnerRequest
  sig do
    params(
      group_id: T.nilable(Integer),
      owner_id: T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity),
      runner_id: T.nilable(Integer)
    ).void
  end
  def initialize(group_id: nil, owner_id: nil, runner_id: nil); end

  sig { void }
  def clear_group_id; end

  sig { void }
  def clear_owner_id; end

  sig { void }
  def clear_runner_id; end

  sig { returns(Integer) }
  def group_id; end

  sig { params(value: Integer).void }
  def group_id=(value); end

  sig { returns(T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity)) }
  def owner_id; end

  sig { params(value: T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity)).void }
  def owner_id=(value); end

  sig { returns(Integer) }
  def runner_id; end

  sig { params(value: Integer).void }
  def runner_id=(value); end
end
