# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::V1::IssueCreateTemplate`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::V1::IssueCreateTemplate`.

class Hydro::Schemas::Github::V1::IssueCreateTemplate
  sig do
    params(
      actor: T.nilable(Hydro::Schemas::Github::V1::Entities::User),
      issue: T.nilable(Hydro::Schemas::Github::V1::Entities::Issue),
      issue_creator: T.nilable(Hydro::Schemas::Github::V1::Entities::User),
      issue_template: T.nilable(Hydro::Schemas::Github::V1::Entities::IssueTemplate),
      issue_type: T.nilable(Hydro::Schemas::Github::V1::Entities::IssueType),
      repository: T.nilable(Hydro::Schemas::Github::V1::Entities::Repository),
      repository_owner: T.nilable(Hydro::Schemas::Github::V1::Entities::User),
      request_context: T.nilable(Hydro::Schemas::Github::V1::Entities::RequestContext)
    ).void
  end
  def initialize(actor: nil, issue: nil, issue_creator: nil, issue_template: nil, issue_type: nil, repository: nil, repository_owner: nil, request_context: nil); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::User)) }
  def actor; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::User)).void }
  def actor=(value); end

  sig { void }
  def clear_actor; end

  sig { void }
  def clear_issue; end

  sig { void }
  def clear_issue_creator; end

  sig { void }
  def clear_issue_template; end

  sig { void }
  def clear_issue_type; end

  sig { void }
  def clear_repository; end

  sig { void }
  def clear_repository_owner; end

  sig { void }
  def clear_request_context; end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::Issue)) }
  def issue; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::Issue)).void }
  def issue=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::User)) }
  def issue_creator; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::User)).void }
  def issue_creator=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::IssueTemplate)) }
  def issue_template; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::IssueTemplate)).void }
  def issue_template=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::IssueType)) }
  def issue_type; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::IssueType)).void }
  def issue_type=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::Repository)) }
  def repository; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::Repository)).void }
  def repository=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::User)) }
  def repository_owner; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::User)).void }
  def repository_owner=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::RequestContext)) }
  def request_context; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::RequestContext)).void }
  def request_context=(value); end
end
