# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::V1::SmsMessageSent`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::V1::SmsMessageSent`.

class Hydro::Schemas::Github::V1::SmsMessageSent
  sig do
    params(
      actor: T.nilable(Hydro::Schemas::Github::V1::Entities::User),
      hashed_sms_number: T.nilable(String),
      request_context: T.nilable(Hydro::Schemas::Github::V1::Entities::RequestContext)
    ).void
  end
  def initialize(actor: nil, hashed_sms_number: nil, request_context: nil); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::User)) }
  def actor; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::User)).void }
  def actor=(value); end

  sig { void }
  def clear_actor; end

  sig { void }
  def clear_hashed_sms_number; end

  sig { void }
  def clear_request_context; end

  sig { returns(String) }
  def hashed_sms_number; end

  sig { params(value: String).void }
  def hashed_sms_number=(value); end

  sig { returns(T.nilable(Hydro::Schemas::Github::V1::Entities::RequestContext)) }
  def request_context; end

  sig { params(value: T.nilable(Hydro::Schemas::Github::V1::Entities::RequestContext)).void }
  def request_context=(value); end
end
