# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Aleph::Proto::ReferenceInformation`.
# Please instead update this file by running `bin/tapioca dsl Aleph::Proto::ReferenceInformation`.

class Aleph::Proto::ReferenceInformation
  sig { void }
  def initialize; end
end
