import {SettingsLayout} from '../components/SettingsLayout'
import SettingsHeader from '../components/SettingsHeader'
import SectionContent from '../components/SectionContent'
import Section from '../components/Section'
import {Button, Breadcrumbs, FormControl, TextInput, Text, Textarea, Checkbox, Link, Flash} from '@primer/react'
import SettingsFormFooter from '../components/SettingsFormFooter'
import {ControlGroup} from '@github-ui/control-group'

const EnterpriseSaml = () => {
  const formMinWidth = ['100%', '500px']
  return (
    <SettingsLayout nav="enterprise" active="Security">
      <Breadcrumbs>
        <Breadcrumbs.Item href="#">Security</Breadcrumbs.Item>
        <Breadcrumbs.Item href="#" selected>
          SAML single sign-on
        </Breadcrumbs.Item>
      </Breadcrumbs>
      <SettingsHeader title="SAML single sign-on" divider />
      <Text sx={{color: 'fg.muted'}}>
        Add another level of security to your enterprise with SAML single sign-on. Learn more about SAML single sign-on.
      </Text>
      <Section>
        <SectionContent variant="form">
          <FormControl>
            <FormControl.Label>Require SAML authentication</FormControl.Label>
            <FormControl.Caption>
              After you require SAML authentication, members of the Avocado Corp. enterprise must authenticate with your
              SAML identity provider (IdP) to access any of the enterprise&apos;s organizations. Supported IdPs include
              Azure, Okta, OneLogin, Ping Identity, or a custom SAML 2.0 provider.
            </FormControl.Caption>
            <Checkbox />
          </FormControl>
          <Flash variant="warning">
            Enabling enterprise SAML will remove active team synchronization settings in 9 organizations. Please take
            note of the current configuration in the affected organizations if you intend to manually re-enable team
            sync after enabling enterprise SAML.
          </Flash>

          <FormControl>
            <FormControl.Label required>Sign on URL</FormControl.Label>
            <TextInput placeholder="https://yourapp.example.com/apps/appId" sx={{minWidth: formMinWidth}} />
            <FormControl.Caption id="TODO">
              Members will be forwarded here when signing in to your enterprise
            </FormControl.Caption>
          </FormControl>
          <FormControl>
            <FormControl.Label required>Issuer</FormControl.Label>
            <TextInput placeholder="https://example.com" sx={{minWidth: formMinWidth}} />
            <FormControl.Caption id="TODO">
              Typically a unique URL generated by your SAML identity provider
            </FormControl.Caption>
          </FormControl>

          <FormControl>
            <FormControl.Label>Public certificate</FormControl.Label>
            <Textarea placeholder="Paste your x509 certificate here" sx={{minWidth: formMinWidth, height: 100}} />
            <FormControl.Caption id="TODO">Your x509 certificate</FormControl.Caption>
          </FormControl>
        </SectionContent>
      </Section>
      <Section>
        <Text sx={{font: 'var(--text-caption-shorthand)', color: 'fg.muted'}}>
          The assertion consumer service URL is{' '}
          <Link inline href="#">
            https://github.com/enterprises/avocado-corp/saml/consume
          </Link>
        </Text>
      </Section>
      <Section>
        <ControlGroup>
          <ControlGroup.Item>
            <ControlGroup.Title as="h2">Test your SAML configuration</ControlGroup.Title>
            <ControlGroup.Description>You need to test your SAML configuration before saving.</ControlGroup.Description>
            <ControlGroup.Button>Start test</ControlGroup.Button>
          </ControlGroup.Item>
        </ControlGroup>
      </Section>
      <SettingsFormFooter>
        <Button variant="primary">Save SAML settings</Button>
        <Button variant="default">Cancel</Button>
      </SettingsFormFooter>
    </SettingsLayout>
  )
}

export default EnterpriseSaml
