#!/bin/bash
set -e

if [ ! -f /data/enterprise-manage/current/public/index.html ]; then
  IS_LOADING=1
  if ! /usr/local/share/enterprise/ghe-preflight-check; then
    IS_LOADING=0 # if preflight check fails we want to display why instead of just show 'Starting' screen
  fi
  LOADING=$IS_LOADING /usr/share/rbenv/versions/current/bin/erb /usr/local/share/enterprise/preflight.html.erb > /data/enterprise-manage/current/public/index.html
fi
