#!/bin/bash
set -e

. /usr/local/share/enterprise/ghe-systemd-lib.sh

if test -f /etc/github/cluster || /usr/local/share/enterprise/ghe-preflight-check; then
  rm -f /data/enterprise-manage/current/public/index.html
fi
