#!/bin/bash
set -e

if [ -L /data/user/mysql -o -L /data/user/redis -o -L /data/user/elasticsearch ]; then
  echo "*** waiting for database blkdev to appear"
  while ! mountpoint -q /data/db; do
    VGNAME=$(lvs --noheadings -o vg_name | grep ghe_db_ | awk '{ print $1 }')
    if [ -n "$VGNAME" ]; then
      vgchange -ay $VGNAME || true
      vgscan --mknodes
      if mount -o defaults,noauto,noatime,nofail,data=ordered /dev/mapper/$VGNAME-ghe_db_data /data/db; then
        break
      fi
    fi
    sleep 1
  done
fi
