#!/bin/bash
# Create missing directories in /var/log

# find /var/log -type d -printf '%p %U %G (%u,%g)\n'
log_dirs='
/var/log/nginx 0 0 (root,root)
/var/log/ghe-configuration 0 0 (root,root)
/var/log/lxc 0 0 (root,root)
/var/log/gh-migrator 500 500 (git,git)
/var/log/fsck 0 0 (root,root)
/var/log/unattended-upgrades 0 0 (root,root)
/var/log/elasticsearch 601 601 (elasticsearch,elasticsearch)
/var/log/mysql 600 4 (mysql,adm)
/var/log/apt 0 0 (root,root)
/var/log/ntpstats 103 105 (ntp,ssh)
/var/log/redis 602 602 (redis,redis)
/var/log/gitmon 500 500 (git,git)
/var/log/sysstat 0 0 (root,root)
/var/log/enterprise-manage 605 605 (enterprise-manage,enterprise-manage)
/var/log/grafana 613 613 (grafana,grafana)
/var/log/ghes-manage-agent 657 657 (ghes-manage-agent,ghes-manage-agent)
/var/log/ghes-manage-gateway 658 658 (ghes-manage-gateway,ghes-manage-gateway)
'

rover_links='alambic github'

for service in $rover_links ; do
  ln -nsf /data/$service/current/log /var/log/$service
done

IFS=$'\n'
for dir in $log_dirs; do
  path=$(echo $dir | awk '{print $1}')
  uid=$(echo $dir | awk '{print $2}')
  gid=$(echo $dir | awk '{print $3}')
  [ -d "$path" ] && continue
  mkdir -p $path
  chown $uid:$gid -R $path
done
