#!/bin/bash
set -e

for ((n=0; n<180; n++)); do
  if redis-cli ping 2>/dev/null | grep -q PONG; then
    break
  fi
  sleep 1
done

if ! redis-cli ping >/dev/null 2>&1; then
  cat /var/log/redis/redis.log 1>&2
  echo "Error: redis failed to start." 1>&2
  exit 1
fi

redis-cli BGREWRITEAOF > /dev/null 2>&1 || true
