#!/bin/bash
set -e

. /usr/local/share/enterprise/ghe-systemd-lib.sh

if ! service_enabled redis; then
  echo redis is not enabled on this node
  exit 126
fi

if test -s /data/user/redis/appendonly.aof && ! redis-check-aof /data/user/redis/appendonly.aof; then
  echo "AOF corruption detected, repairing..." >&2
  echo y | redis-check-aof --fix /data/user/redis/appendonly.aof
fi
