#!/bin/bash
# If /etc/resolv.conf is a regular file, move it to /etc/resolvconf/resolv.conf.d/base
# This lets us inject our local dnsmasq into /etc/resolv.conf first, but lets it use
# the nameservers provided by Docker as forwarders.
set -e

SRCFILE=/etc/resolv.conf

if [ "$(whoami)" != "root" ]; then
  exec sudo -E "$0" "$@"
fi

[ -e /.dockerenv ] || exit 0

if [ -f $SRCFILE ] ; then
  mkdir -p /var/resolvconf
  cp -R /run/resolvconf /var/resolvconf/run
  rm -f /etc/resolvconf/run
  ln -s /var/resolvconf/run /etc/resolvconf/run
  rm -rf /run/resolvconf
  ln -s /var/resolvconf/run /run/resolvconf
else
  echo "$0: $SRCFILE isn't a regular file, leaving it alone" >&2
fi
