#!/bin/bash
# Wait for resolvconf service to do its thing, then copy the output
# from that run into /etc/resolv.conf explicitly to ensure the first
# nameserver is 127.0.0.1 where dnsmasq is listening
set -e

DSTFILE=/etc/resolv.conf
TMPFILE=/var/run/resolvconf/resolv.conf

if [ "$(whoami)" != "root" ]; then
  exec sudo -E "$0" "$@"
fi

[ -e /.dockerenv ] || [ -e /run/.containerenv ] ||  exit 0

sleep 2

if [ -f "$TMPFILE" ] ; then
  size="$(stat --format %s "$TMPFILE")"
  if [ $size -gt 0 ]; then
    echo "Write $TMPFILE to $DSTFILE" >&2
    /bin/cat "$TMPFILE" > "$DSTFILE"
  else
    echo "$0: $TMPFILE is empty, leaving $DSTFILE alone" >&2
  fi
else
  echo "$0: $TMPFILE isn't a file, leaving $DSTFILE alone" >&2
fi
