#!/bin/bash
set -e

if [ -e /etc/default/samplicator ] ; then
  . /etc/default/samplicator
fi

if [ "$ENABLED" != "yes" ] ; then
  echo "samplicator disabled. Enable it adding ENABLED=yes to /etc/default/samplicator"
  exit 0
fi

exec /opt/samplicator/bin/samplicate -p 8125 -c /etc/samplicator.conf
