// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
/* eslint eslint-comments/no-use: off */
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

declare namespace WebCommitDialogModuleCssNamespace {
  export interface IWebCommitDialogModuleCss {
    commitFileIcon: string
  }
}

declare const WebCommitDialogModuleCssModule: WebCommitDialogModuleCssNamespace.IWebCommitDialogModuleCss

export = WebCommitDialogModuleCssModule
