#!/bin/bash

# Check if port 9100 is not already in use
if lsof -Pi :9100 -sTCP:LISTEN >/dev/null; then
  echo "An instance of Alloy is already running" && sleep infinity
  exit 0
fi

if [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
  SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
  source $SCRIPT_DIR/dx/lib/subproject-containers

  SUBPROJECT_VERSION=$(subproject_version "alloy")
  echo "alloy version $SUBPROJECT_VERSION"

  cleanup_docker() {
    echo "Stopping alloy..."
    docker stop alloy || true
  }

  trap cleanup_docker EXIT INT QUIT TERM HUP

  docker stop alloy &> /dev/null || true
  docker rm alloy &> /dev/null || true

  # Run the alloy node service.
  docker run -d --rm --name alloy --network host \
    -e PORT=9100 \
    -e HMAC_SECRETS=yay-alloy-dev \
    -e ALLOWED_DOMAINS=github.githubassets.com,github.localhost \
    -e GC_ON_RESET=true \
    "ghcr.io/github/shared-dev/alloy:$SUBPROJECT_VERSION"

  docker logs --follow alloy &
  wait
else
  bin/node vendor/alloy/dist/dev.js
fi
