#!/bin/sh

app_config=".app-config/production.sh"
if [ -f $app_config ]; then
  . $app_config
else
  echo "error: .app-config/production.sh is missing. you need to deploy before running $*"
  exit 1
fi

exec "$@"
