#!/bin/bash
#/ Usage: script/aqueduct-lite-server
#/
#/ Runs aqueduct-lite service.

# Never attempt to upload packages during aqueduct-lite-server run.
unset GITHUB_PACKAGES_SUBPROJECT_CACHE_WRITE

PORT="${AQUEDUCT_LITE_PORT:-18081}"
NAME="aqueduct-lite-${PORT}"

if [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
  SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
  source $SCRIPT_DIR/dx/lib/subproject-containers

  SUBPROJECT_VERSION=$(subproject_version "aqueduct-lite")
  echo "aqueduct-lite version $SUBPROJECT_VERSION"

  start_subproject --name=$NAME --entrypoint "/app/bin/aqueduct-lite" \
    "ghcr.io/github/aqueduct-lite/aqueduct-lite:$SUBPROJECT_VERSION" \
    --queue-depth-scan-interval 10m \
    --timeout-scanner-interval 10m \
    --listen-address 0.0.0.0:${PORT} \
    --redis-address redis://127.0.0.1:${AQUEDUCT_LITE_REDIS_PORT:-6379}/0

else
  script/build-subproject aqueduct-lite || exit 1

  exec vendor/aqueduct-lite/bin/aqueduct-lite \
    --queue-depth-scan-interval 10m \
    --timeout-scanner-interval 10m \
    --listen-address 0.0.0.0:${AQUEDUCT_LITE_PORT:-18081} \
    --redis-address redis://127.0.0.1:${AQUEDUCT_LITE_REDIS_PORT:-6379}/0
fi
