#!/usr/bin/env ruby

require File.expand_path("../../config/environment", __FILE__)

ARGF.each_line do |line|
  id = line.strip
  begin
    repo = Repositories::Public.get_active_or_deleted!(id)
    repo.async_backup_wiki
    puts "ENQUEUED: #{id}"
  rescue ActiveRecord::RecordNotFound
    $stderr.puts "NOT FOUND: #{id}"
  end
end
