#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Usage: ./script/background-jobs-invalid-queues <environment>
# Gets the invalid job queues for an environment.
# - Environments available: dotcom, proxima, enterprise, staff, development
#
# A queue becomes invalid within an environment either when:
# - There is no corresponding configuration for that particular environment.
# - The job queue configuration explicitly indicates that it should not be executed there.

queues_environment = ARGV.shift or abort "usage: script/background-jobs-invalid-queues <environment>"

require_relative "../config/environment"

ALLOWED_ENVIRONMENTS = %w{
  dotcom
  proxima
  enterprise
  staff
  development
}

def get_invalid_queues_for_environment(environment)
  if ALLOWED_ENVIRONMENTS.include?(environment)
    BackgroundJobQueues.queue_configurations.select do |_queue_name, queue_configuration|
      !queue_configuration[environment.to_sym]
    end.keys
  else
    puts "Wrong environment. Try one of these: #{ALLOWED_ENVIRONMENTS.join(",")}"
  end
end

puts get_invalid_queues_for_environment(queues_environment)
