#!/usr/bin/env ruby
require "github/config/active_record"

login = ARGV.shift or abort "usage: bcrypt-auth-token-for-user <login>"

bcrypt_auth_token = ApplicationRecord::Domain::Users.connection.select_value(Arel.sql("SELECT bcrypt_auth_token FROM users WHERE login = :login", login: login))

if bcrypt_auth_token
  puts bcrypt_auth_token
  exit true
else
  exit false
end
