#!/bin/sh
#/ Usage: build-ctags [<options>]
#/ Build tags file in the RAILS_ROOT directory. Any <options> provided are
#/ passed to ctags.
#/
#/ This command requires exuberant ctags to be installed.
set -e

# show usage message
if [ "$1" = "--help" ]; then
    grep ^#/ <"$0" | cut -c4-
    exit 2
fi

# change into RAILS_ROOT
cd "$(dirname "$0")/.."

# check that ctags version is correct
ctags --version >/dev/null 2>&1 || {
    echo "ctags not found or too old." 1>&2
    exit 1
}

exec ctags -R \
    --tag-relative=yes \
    --totals=yes \
    --extras=+f \
    --fields=+iaS \
    --exclude=*.md \
    --exclude=.*.js \
    --exclude=*.config.js \
    --exclude=db \
    --exclude=docs \
    --exclude=lib/git-core/template/hooks \
    --exclude=log \
    --exclude=node_modules \
    --exclude=public/assets \
    --exclude=public/javascripts \
    --exclude=public/static \
    --exclude=repositories/development \
    --exclude=repositories/test \
    --exclude=test/components \
    --exclude=test/controllers \
    --exclude=test/fast \
    --exclude=test/fixtures \
    --exclude=test/integration \
    --exclude=test/jobs \
    --exclude=test/js \
    --exclude=test/lib \
    --exclude=test/linting \
    --exclude=test/mailers \
    --exclude=test/models \
    --exclude=test/routes \
    --exclude=test/view_models \
    --exclude=tmp \
    --exclude=vendor \
    "$@"
