#!/bin/sh
#/ Usage: build-perf-test
#/        build-perf-test <branch>
#/ Build github performance tests from https://github.com/github/dotcom-performance

set -e
unset CDPATH

# show usage
if [ "$1" = "--help" ]; then
    grep ^#/ <"$0" |cut -c4-
    exit
fi

# change into root project dir
ROOT_DIR="$(dirname "$0")/../.."
cd $ROOT_DIR

# git repository URL to clone from.
REPO_URL="$(github/script/gh-clone-url github/dotcom-performance)"

# build path locations
builddir="dotcom-performance"
logfile="log/dotcom-performance-build.log"

if [ -d "$builddir" ]; then
  echo "removing $builddir directory..."
  sudo rm -rf $builddir
fi

git init -q "$builddir"

cd $builddir
if ! git config --local remote.origin.url >/dev/null; then
  git remote add origin "$REPO_URL"
fi
git pull origin master --prune
git reset --hard

echo "Successfully Built Performance Tests"
true
