#!/bin/bash
set -e

root=$(cd $(dirname "$0")/.. && pwd)

case "$1" in
'' | install | update ) mode=command ;;
* ) mode=exec ;;
esac

$mode "$root/bin/safe-ruby-quick" "$root/vendor/ruby/current/bin/bundle" "$@"

# Update licenses for Rails Current (only) before we bundle for Rails Next.
# Skip this step if $SKIP_BUNDLE_LICENSE_CACHE == 1 (Used to prevent errors in tests)
if [[ "$SKIP_BUNDLE_LICENSE_CACHE" != "1" ]]
then
  "$root/bin/licenses-cache" --sources bundler
fi
