#!/bin/bash

set -e

query=$1

if [ -z $query ]; then
  query="output"
fi

echo "Searching for query: $query"
result=$(curl -sS --fail \
  --max-time 5 \
  --header "Content-Type: application/json" \
  --data "{\"query\": \"$query\", \"experiments\": {\"corpus\": \"blue\"} }" \
  http://localhost:9888/twirp/blackbirdmw.query.v1.QueryAPI/Query)

length=$(echo $result | jq '.documents | length')
echo "OK! Got $length results"
