#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"

if ARGV.include?("--review-lab")
  group_id = "check_suite_status_change_processor_#{GitHub.current_ref.parameterize.underscore}"
end
processor = GitHub::StreamProcessors::CheckSuiteStatusChangeProcessor.new(group_id: group_id)
consumer = GitHub.hydro_consumer(processor.options)

CheckSuiteStatusChangeProcessorError = Class.new(StandardError)

begin
  GitHub.logger.info("start", { "code.namespace" => processor.class.name })
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
  GitHub.logger.info("finish", { "code.namespace" => processor.class.name })
rescue => e
  # rubocop:disable Style/HashSyntax
  GitHub.logger.error("failed to run stream processor", { "code.namespace" => processor.class.name, exception: e })
  Failbot.report(CheckSuiteStatusChangeProcessorError.new)
  raise
end
