#!/bin/bash
# Run git clean excluding regexps listed in .cicleankeep

git clean -fdx \
  app/ \
  public/

# Lists all files `git clean` would remove
git clean -d -x --dry-run | \
  # Filter and strip lines that start with "Would remove "
  grep "Would remove" | sed 's/^Would remove //' | \
  # Exclude paths from .cicleankeep
  grep --invert-match --file .cicleankeep | \
  # Run git clean on remaining paths
  xargs git clean -fdx
