#!/usr/bin/env ruby

require "yaml"
require "fileutils"
require File.expand_path("../../config/basic", __FILE__)

if ARGV.length != 1
  $stderr.puts "Invalid usage"
  $stderr.puts "  Usage: #{$0} <gist id>"
  $stderr.puts
  $stderr.puts "Example: #{$0} 123456"
  exit(1)
end

GIST = ARGV[0]
GIT_UID = 500

if Process.euid != GIT_UID
  $stderr.puts "ERROR: This script must be run as the git user.  su - git and try again."
  exit 1
end

BASE_GIST_PATH = GitHub::Routing.gist_storage_path(repo_name: GIST)

# check for .moved or .premoved directories only.
if File.directory?(BASE_GIST_PATH + ".moved")
  # moved path.
  CLEANUP_PATH = BASE_GIST_PATH + ".moved"
else
  CLEANUP_PATH = BASE_GIST_PATH + ".premove"

  unless File.directory?(CLEANUP_PATH)
    $stderr.puts "#{CLEANUP_PATH} does not exist on this fileserver.  No cleanup necessary."
    exit 0
  end
end

print "Pruning stale gist directory #{CLEANUP_PATH}..."
system("rm -rf #{CLEANUP_PATH}")
if $?.exitstatus != 0
  puts " FAILED"
  $stderr.puts "Prune failed"
  exit 1
end
puts " done."

exit 0
