#!/bin/sh
# Runs a script, as devoid of github's ruby environment as possible.

test -n "${NON_GH_PATH}" && export PATH=${NON_GH_PATH}

unset RUBYOPT
unset RAILS_ROOT
unset GEM_HOME
unset GEM_PATH
unset BUNDLE_APP_CONFIG

exec "$@"
