#!/usr/bin/env ruby
# frozen_string_literal: true

require "base64"
require "fileutils"
require "json"

# This script is called from script/setup --enterprise
if ENV["CODESPACES"]
  if `which gh`.strip.size.positive?
    warn "Downloading test.ghl from enterprise2 repo on github.com"
    Dir.chdir(File.expand_path("../../..", __FILE__))
    FileUtils.mkdir_p("enterprise2")
    test_ghl_b64 = JSON.parse(`gh api /repos/github/enterprise2/contents/test.ghl`)["content"]
    # Base64 decode into a test.ghl file
    File.open("enterprise2/test.ghl", "w") do |f|
      f.write(Base64.decode64(test_ghl_b64))
    end
  else
    warn "No gh command present. Skipping downloading test.ghl"
  end
end
