#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
processor = GitHub::StreamProcessors::CommunityInsights::DiscussionPageViewProcessor.new
consumer = GitHub.with_hydro_cluster(:yukon) { GitHub.hydro_consumer(processor.options) }

DiscussionPageViewProcessorError = Class.new(StandardError)

begin
  GitHub.logger.info("start", { "code.namespace" => processor.class.name })
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
  GitHub.logger.info("finish", { "code.namespace" => processor.class.name })
rescue => e
  # rubocop:disable Style/HashSyntax
  GitHub.logger.error("failed to run stream processor", { "code.namespace" => processor.class.name, exception: e })
  Failbot.report(DiscussionPageViewProcessorError.new)
  raise
end
