#!/bin/sh
# Usage: copilot-fauxpilot-api-server
# Start the real copilot-api server if it exists, or the fake copilot-api server otherwise.
set -e

if test -f /workspaces/copilot-api/script/server; then
  echo "/workspaces/copilot-api exists, will start the real copilot-api server..."
  if lsof -Pi :2206 -sTCP:LISTEN >/dev/null; then
    echo "Port 2206 is already in use; is an instance of copilot-api already running?"
    sleep infinity
  else
    cd /workspaces/copilot-api && script/server -port 2206
  fi
else
  echo "/workspaces/copilot-api not found, will start the fake copilot-api server..."
  if lsof -Pi :2206 -sTCP:LISTEN >/dev/null; then
    echo "Port 2206 is already in use; is an instance of fauxpilot_api_server already running?"
    sleep infinity
  else
    exec bin/safe-ruby packages/copilot4prs/app/lib/fauxpilot_api_server.rb 2206
  fi
fi
