#!/bin/bash
# Copy fonts from the mathjax node_module folder into public so they will be available
# to mathjax. We need to do this because mathjax has a hardcoded folder path for fonts.
mkdir -p ./public/static/fonts/mathjax
cp -r ./node_modules/mathjax/es5/output/chtml/fonts/woff-v2/* ./public/static/fonts/mathjax

rm -rf ./public/static/javascripts/mathjax
mkdir -p ./public/static/javascripts/mathjax

cp -r ./node_modules/mathjax/es5/a11y ./public/static/javascripts/mathjax

mkdir ./public/static/javascripts/mathjax/input
cp ./node_modules/mathjax/es5/input/mml.js ./public/static/javascripts/mathjax/input

mkdir ./public/static/javascripts/mathjax/sre
cp ./node_modules/mathjax/es5/sre/sre_browser.js ./public/static/javascripts/mathjax/sre

mkdir ./public/static/javascripts/mathjax/mathmaps
cp ./node_modules/mathjax/es5/sre/mathmaps/en.js ./public/static/javascripts/mathjax/mathmaps

mkdir ./public/static/javascripts/mathjax/ui
cp ./node_modules/mathjax/es5/ui/safe.js ./public/static/javascripts/mathjax/ui
