#!/bin/bash
# This script is run EVERY TIME ANYONE RUNS script/bootstrap OR script/setup
# As a result: the no-op case should be REALLY FAST to avoid being annoying
# If you're changing it: PLEASE make sure you're not making it take longer than
# a couple of seconds in the no-op case.
# THANKS <3 <3 <3

set -e

if ! [ $GITHUB_CI ]; then
  # source here first to prime some cached variables
  source "script/database-functions"

  # kill all subprocesses on interrupt
  trap '{ /usr/bin/pkill -P $$ &>/dev/null; wait; exit 130; }' SIGINT

  # attempt to create every cluster in parallel (which will be almost always a
  # no-op and, when it isn't, only not a no-op on a few clusters)
  script/create-abilities-cluster &
  script/create-configurations-cluster &
  script/create-gitbackups-cluster &
  script/create-ballast-cluster &
  script/create-memex-cluster &
  script/create-notify-cluster &
  script/create-kv-cluster &
  script/create-repositories-cluster &
  script/create-repositories-actions-checks-cluster &
  script/create-repositories-pushes-cluster &
  script/create-issues-pull-requests-cluster &
  script/create-billing-cluster &
  script/create-copilot-cluster &
  script/create-spokes-cluster &
  script/create-stratocaster-cluster &
  script/create-notifications-cluster &
  script/create-notifications-deliveries-cluster &
  script/create-notifications-entries-cluster &
  script/create-notifications-summaries-cluster &
  script/create-iam-cluster &
  script/create-hookshot-cluster --create &
  script/create-permissions-cluster &
  script/create-token-scanning-service-cluster &
  script/create-vt-cluster &
  script/create-migrations-cluster &
  script/create-lodge-cluster &
  script/create-authnd-cluster &
  script/create-commits-cluster &
  script/create-signup-flow-cluster &

  # waiting for all the above scripts to finish running
  wait
  # remove the interrupt trap
  trap - SIGINT
fi
