#!/bin/bash

source "script/database-functions"

tables=(key_values stratocaster_indexes search_index_template_configurations)

create_database_and_copy_tables "github_development" "github_development_kv" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_kv" "${tables[@]}"
