#!/bin/bash

source "script/database-functions"

tables=(migratable_resources migratable_resource_reports migration_files migration_repositories migration_timings migrations)

create_database_and_copy_tables "github_development" "github_development_migrations" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_migrations" "${tables[@]}"
