#!/bin/bash

source "script/database-functions"

tables=(pending_partner_token_notifications secret_scan_custom_patterns secret_scan_incremental_statuses secret_scanning_repositories secret_scans token_scan_location_migration_statuses token_scan_result_locations_v2 token_scan_result_sequences token_scan_results token_scan_statuses dry_run_scan_results)

create_database_and_copy_tables "github_development_notify" "github_development_token_scanning_service" "${tables[@]}"

create_database_and_copy_tables "github_test_notify" "github_test_token_scanning_service" "${tables[@]}"
