#!/bin/bash

source "script/database-functions"

tables=(notification_summaries)

create_database_and_copy_tables "github_development" "github_development_notifications_summaries" "${tables[@]}"
create_database_and_copy_tables "github_test" "github_test_notifications_summaries" "${tables[@]}"
