#!/bin/bash

source "script/database-functions"

tables=(billing_budgets billing_disputes billing_external_emails billing_payouts_ledger_discrepancies billing_payouts_ledger_entries billing_prepaid_metered_usage_refills billing_sales_serve_plan_subscriptions bundled_license_assignments enterprise_agreements metered_usage_exports plan_trials shared_storage_artifact_events stripe_connect_accounts subscription_sync_statuses vss_subscription_events)

create_database_and_copy_tables "github_development_collab" "github_development_billing" "${tables[@]}"

create_database_and_copy_tables "github_test_collab" "github_test_billing" "${tables[@]}"
