#!/bin/bash

source "script/database-functions"

tables=()

create_database_and_copy_tables "github_development" "github_development_vt" "${tables[@]}"
create_database_and_copy_tables "github_test" "github_test_vt" "${tables[@]}"
