#!/bin/bash

source "script/database-functions"

tables=(abilities)

create_database_and_copy_tables "github_development" "github_development_abilities" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_abilities" "${tables[@]}"
