#!/bin/bash

source "script/database-functions"

tables=(fileservers gist_replicas network_replicas repository_checksums repository_replicas)

create_database_and_copy_tables "github_development" "github_development_spokes" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_spokes" "${tables[@]}"
