#!/bin/bash

source "script/database-functions"

tables=()

create_database_and_copy_tables "github_development" "github_development_copilot" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_copilot" "${tables[@]}"
