#!/bin/bash

source "script/database-functions"

tables=(notification_deliveries)

create_database_and_copy_tables "github_development" "github_development_notifications_deliveries" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_notifications_deliveries" "${tables[@]}"
