#!/bin/bash

source "script/database-functions"

tables=(notification_entries spammy_notification_entries saved_notification_entries)

create_database_and_copy_tables "github_development" "github_development_notifications_entries" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_notifications_entries" "${tables[@]}"
