#!/usr/bin/env ruby
#/ Usage: create-all-deployment-variations <nwo> <pull-request-number> <integration>
#/ Create all variations of a deployment and it's status
#/ Example
#/ ./bin/create-all-deployment-variations "tarebyte/foobar" 1 heroku-deployments

# Show usage
if ARGV.include?("--help") || ARGV.length < 2
  system "grep ^#/ '#{__FILE__}' |cut -c3-"
  exit 1
end

require_relative "../config/environment"
require_relative "./seeds/runners/deployments"

# indicate where the execution starts. This file isn`t supposed to be loaded via require
if __FILE__ == $0
  # Show usagd
  if ARGV.include?("--help")
    system "grep ^#/ '#{__FILE__}' |cut -c3-"
    exit 1
  end
  Seeds::Runner::Deployments.run(nwo: ARGV.shift, pull_request_number: ARGV.shift, integration_slug: ARGV.shift)
end
