#!/bin/bash

source "script/database-functions"

tables=(hidden_users notification_subscriptions notification_thread_subscriptions notification_user_settings rollup_summaries)

create_database_and_copy_tables "github_development" "github_development_notifications" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_notifications" "${tables[@]}"
