#!/usr/bin/env ruby
# frozen_string_literal: true
#/ Usage: create-marketplace-stories [num]
#/ Create some Marketplace-related stories that we can feature

# Show usage
if ARGV.include?("--help")
  system "grep ^#/ '#{__FILE__}' |cut -c3-"
  exit 1
end

# Bring in the big environment
require_relative "../config/environment"
require "faker"

number_of_stories = ARGV.shift || 5

number_of_stories.times.map do |number|
  Marketplace::Story.create(
    external_post_id: Faker::Number.number(digits: 4),
    title: Faker::Book.title,
    url: Faker::Internet.url,
    author: Faker::Book.author,
    description: Faker::Lorem.sentence(number: 10),
    featured: number.even?,
    published_at: Faker::Date.between(from: 18.months.ago, to: Date.today),
  )
end

puts "Created #{number_of_stories} Marketplace stories"
