#!/bin/bash

source "script/database-functions"

tables=(permissions)

create_database_and_copy_tables "iam_development" "github_development_permissions" "${tables[@]}"
create_database_and_copy_tables "iam_test" "github_test_permissions" "${tables[@]}"
