#!/bin/bash

source "script/database-functions"

tables=(slotted_counters)

create_database_and_copy_tables "github_development" "github_development_ballast" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_ballast" "${tables[@]}"
