#!/bin/bash

source "script/database-functions"

tables=(statuses)

create_database_and_copy_tables "github_development" "github_development_repositories_checks" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_repositories_checks" "${tables[@]}"
