#!/bin/sh
#/ Usage: create-example-repo name
#/
#/ Create a new example repository for testing
#/
#/ This will create a bare repository in `test/fixtures/git/examples/$NAME.git`,
#/ and a full repository that can be modified in `tmp/$NAME`. Commit your changes
#/ to the repository in `./tmp` and then use `git push origin` to push the
#/ changes into the bare repository. The bare repository can then be committed
#/ along with the tests that make use of it.

set -e

# show usage message
if [ "$1" = "--help" ]; then
    grep ^#/ <"$0" | cut -c4-
    exit 2
fi

git init --bare --template='' test/fixtures/git/examples/$1.git
git clone test/fixtures/git/examples/$1.git tmp/$1
