#!/usr/bin/env ruby
# frozen_string_literal: true
#/ Usage: create-seeds-actions [<# of workflow runs to create, defaults to 20>]
# Purpose:
# Seed workflows with workflow runs in github/hub repository
#
# Seeding
# - Enables Actions/workflow feature flags
# - Creates the Actions GitHub app
# - Creates workflows in the github/hub repository
# - Creates workflow runs with different outcomes for those workflows

require_relative "./seeds/runners/actions"

# indicate where the execution starts. This file isn`t supposed to be loaded via require
if __FILE__ == $0
  # Show usage
  if ARGV.include?("--help")
    system "grep ^#/ '#{__FILE__}' |cut -c3-"
    exit 1
  end

  count = (ARGV.shift || 20).to_i
  puts "Please run `bin/seed help actions` to see the new usage"
  Seeds::Runner::Actions.execute(workflow_run_count: count)
end
