#!/bin/bash

source "script/database-functions"

tables=(stratocaster_events)

create_database_and_copy_tables "github_development" "github_development_stratocaster" "${tables[@]}"

create_database_and_copy_tables "github_test" "github_test_stratocaster" "${tables[@]}"
