#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Usage: create-pages-app
# Create the GitHub Pages OAuth app

# Show usage
if ARGV.include?("--help")
  system "grep ^#/ '#{__FILE__}' |cut -c3-"
  exit 1
end

puts "=> Loading the enviroment..."

# Bring in the big environment
require_relative "../config/environment"

unless Rails.env.development?
  puts "This can only be run in the development environment!"
  exit 1
end

puts "=> Creating the Pages OAuth app..."

# Parse arguments
owner = User.find_by_login("github")

application = OauthApplication.new(
  user: owner,
  name: "GitHub Pages",
  url: "http://example.com",
  callback_url: "http://example.com/oauth/callback",
)

application.save!
application
