#!/usr/bin/env ruby
# frozen_string_literal: true
#/ Usage: create-seed-dmca-strike-repos
# Purpose:
# Seed repos that have dmca strikes against a user
#
# Seeding
# - Ensures copywrong user exists
# - Ensures copywrong/strike1 exists
# - Ensures copywrong/strike2 exists
# - Ensures copywrong/prequel-strike exists
# - Issues DMCA takedowns against strike1 and prequel-strike

require_relative "./seeds/runners/dmca_strike_repos"

# indicate where the execution starts. This file isn`t supposed to be loaded via require
if __FILE__ == $0
  # Show usagd
  if ARGV.include?("--help")
    system "grep ^#/ '#{__FILE__}' |cut -c3-"
    exit 1
  end
  puts "Please run `bin/seed help dmca_strike_notices` to see the new usage"
  Seeds::Runner::DmcaStrikeRepos.execute
end
