#!/usr/bin/env safe-ruby
# typed: true
# frozen_string_literal: true

puts "=> Loading the environment..."

require_relative "../config/environment"

unless Rails.env.development?
  puts "=> This script is only intended for development."
  exit 1
end

class CreatePrivateRegistrySecretsApp
  def call
    if Apps::Internal.integration(:private_registry_secrets).present?
      puts "=> The private registry secrets GitHub app already exists."
    else
      puts "=> Creating the private registry secrets GitHub app..."
      Apps::Internal::PrivateRegistrySecrets.seed_database!
    end
  end
end

if __FILE__ == $0
  CreatePrivateRegistrySecretsApp.new.call
  puts "=> Done!"
end
