#!/usr/bin/env ruby

# runs a simple select over and over unless an exception occurs

$stderr.sync = true
require_relative "../config/environment"

if `hostname` =~ /stg\.github\.com/
  dbhost = "db2-active.stg.github.com"
  dbname = "github_staging"
  dbpass = "SiQuivu7"
else
  dbhost = "github-mysqlwriter1-cp1-prd.iad.github.net"
  dbname = "github_production"
  dbpass = "uus6HooN"
end

ActiveRecord::Base.establish_connection( # rubocop:disable GitHub/DoNotCallMethodsOnActiveRecordBase
  adapter: "mysql2",
  host: dbhost,
  username: "github",
  password: dbpass,
  database: dbname,
)

loop do
  begin
    puts "starting new query at #{Time.now}"
    User.find_by_login("wfarr")
    puts "query complete at #{Time.now}"
    sleep 0.001
  rescue Exception => e # rubocop:todo Lint/GenericRescue
    puts "Caught exception #{e} at #{Time.now}"
  end
end
