#!/usr/bin/env safe-ruby
# frozen_string_literal: true
# Usage: script/decode-saml-response

# on average, most SAML Responses are in the 10k bytes range
MAXLEN = 100_000 # bytes

input =
  begin
    STDIN.read_nonblock(MAXLEN)
  rescue IO::WaitReadable
    abort "usage: #$0 - expects SAML Response string on STDIN"
  end

require File.expand_path("../../config/environment", __FILE__)

input = input.gsub(/\\[rn]/, "").gsub("\r", "").gsub("\n", "")

response = SAML::Message::Response.from_param(input)

puts response.document.to_xml(indent: 2)
