#!/bin/bash

export RAILS_ENV=test
export OUTPUT_FILES=true

# Grep output of test for lines that start with app/
unused_files=$(bin/rails test test/fast/linting/unused_code_test.rb | grep '^app/')

# Count number of lines in unused_files
echo "Deleteing $(echo $unused_files | wc -l) files"

echo $unused_files | xargs rm
