#!/bin/bash

cd $(dirname $0)/..

# Ensure that the container gets shut down when this script is started through Overmind
trap 'docker stop dev-identity-provider &> /dev/null' EXIT HUP INT QUIT PIPE TERM

SHA=$(cat config/dev-identity-provider-ruby-version)
docker run -it --rm --name dev-identity-provider --volume "$PWD/vendor/dev-identity-provider-ruby/config/certs:/app/config/certs" --publish 3333:3333 \
  ghcr.io/github/dev-identity-provider-ruby:$SHA
