#!/usr/bin/env ruby
# frozen_string_literal: true

require "getoptlong"
require File.expand_path("../../config/environment", __FILE__)
require "github/dgit"

GitRPC.timeout = 30.minutes.to_i
GitHub.load_activerecord

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} sync nwo fileserver"
  exit 1
end

usage unless ARGV.length == 3
usage unless ARGV[0] == "sync"
usage unless ARGV[1].split("/").size == 2

nwo = ARGV[1]
repo_id, network_id, root_id, is_wiki = GitHub::DGit::Routing::lookup_repo(nwo)
host = GitHub::DGit::Util.long_host(ARGV[2])

SpokesSyncCacheReplicaJob.perform_now(repo_id, host, is_wiki)
