#!/usr/bin/env ruby
# GHE server side script to calculate repository backup routes.
# Gets the host and network path for each network_id with the max_read_weight
#
# Note: This script typically isn't called directly. It's invoked by GHE
# backup-utils.
#
# Returns a list of <network_path> <server>
#
# a/nw/a8/3f/02/100000855 dgit-node1
# a/nw/a8/bc/8d/100000880 dgit-node1
# a/nw/a5/06/81/100000659 dgit-node3
# ...
#
require File.expand_path("../../config/basic", __FILE__)
require "github/dgit"
require "github/dgit/enterprise"

GitHub.load_activerecord

GitHub::DGit::Enterprise.all_network_paths_with_max_read_weight.each do |res|
  #remove root path to get relative path only
  res.slice!("#{GitHub.repository_root}/")
  puts res
end
