#!/usr/bin/env ruby
require_relative "../app/platform/responsibility_audit"

schema_path = "config/schema.internal.graphql"
csv_path = "graphql-responsibilities.csv"
puts "Parsing #{schema_path}, writing to #{csv_path}..."
audit = Platform::ResponsibilityAudit.new(schema_path: schema_path)
File.write(csv_path, audit.to_csv)
