#!/usr/bin/env ruby
# frozen_string_literal: true

##
# Use this script when you are trying to profile the Rails boot-time heap
# It will output a file that contains the Rails just after boot.
# Use `bin/process-heap` to process the resulting JSON heap file.

require "objspace"
require "optparse"
ObjectSpace.trace_object_allocations_start

output = nil

parser = OptionParser.new do |opts|
  opts.banner = "Usage: #{__FILE__}"

  opts.on("-o", "--output [FILE]", "Output heap to [FILE] (`-` means stdout)") do |o|
    output = o
  end

  opts.on("-h", "--help", "Display this screen") do
    puts opts
    exit
  end
end
parser.parse!

unless output
  raise OptionParser::MissingArgument, "missing -o\n" + parser.to_s
end

APP_PATH = File.expand_path("../../config/application", __FILE__)
require_relative "../config/boot"
require_relative "../config/environment"

GC.start

if output == "-"
  ObjectSpace.dump_all output: $stdout
else
  File.open(output, "w") { |f| ObjectSpace.dump_all output: f }
end
