#!/usr/bin/env ruby
# frozen_string_literal: true

switches = %w[SNEK_CI_ENABLED SNEK_CI_ALL_FEATURES_ENABLED SNEK_CANARY_ENABLED SNEK_PROXIMA_ENABLED]
switches.select! { |killswitch| ENV[killswitch] != "true" }
if switches.length != 0
  puts "Killswitches enabled: #{switches.join(", ")}"
  exit 1
end
