#!/usr/bin/env safe-ruby

require File.expand_path("../../config/environment", __FILE__)
if __FILE__ == $0
  $stdout.sync = true

  # Use the readonly DB in production
  if Rails.env.production? && !GitHub.enterprise?
    ActiveRecord::Base.connecting_to(role: :reading)
  end

  # Run!
  Elastomer::App.run ARGV
end

# vim:ft=ruby
