#!/usr/bin/env ruby
# frozen_string_literal: true

require "socket"
require_relative "ownership-detector"

detector = OwnershipDetector.new
ownership_metrics = detector.ownership_metrics

socket = UDPSocket.new
socket.send "total_tests:#{ownership_metrics[:total]}|g|#project:github", 0, "0.0.0.0", 28126
socket.send "total_owners:#{ownership_metrics[:total_owners]}|g|#project:github", 0, "0.0.0.0", 28126
ownership_metrics[:ownership].each do |owner, test_count|
  socket.send "tests:#{test_count}|g|#project:github,owner:#{owner}", 0, "0.0.0.0", 28126
end
