#!/bin/bash
set -e

GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [[ ${CODESPACES} != "true" ]]; then
  echo -e "This is a dev-only script"
  exit 1
fi

echo -e "\n${GREEN}Enabling Copilot chat model feature flags...\n${NC}"

bin/toggle-feature-flag enable \
  copilot_api_enable_model_gpt4o_switzerlandnorth \
  -F copilot_api_model_rollout_gpt4_o_preview_copilot_chat_users \
  -F copilot_api_model_rollout_gpt4_o_preview_copilot_chat_dev_users \
  -F copilot_api_enable_model_gpt4_francecentral1p \
  -F copilot_api_enable_model_gpt35turbo0613_centralus

echo -e "\n${GREEN}Done!\n${NC}"
