#!/bin/bash
set -e

### Bail out early if preconditions aren't met: ###

if lsof -Pi :8152 -sTCP:LISTEN -t >/dev/null ; then
  # gitrpc server running
  :
else
  echo -e "Your server is not running. Please start it with ./script/server and try again."
  exit 1
fi

bin/rake db:abort_if_pending_migrations

###################################################

GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "\n${GREEN}➡️ Setting up Copilot...\n${NC}"
./bin/setup-copilot -E -c

echo -e "\n${GREEN}➡️ Running enable-copilot-chat-skills...\n${NC}"
./bin/enable-copilot-chat-skills

echo -e "\n${GREEN}➡️ Enabling models for development...\n${NC}"
./bin/enable-copilot-chat-dev-models

echo -e "\n${GREEN}➡️ Running copilot_summaries seed script...\n${NC}"
./bin/seed copilot_summaries

echo -e "\n${GREEN}➡️ Creating Copilot chat app\n${NC}"
./bin/rails runner 'Apps::Internal::CopilotChat.seed_database!'
