#!/bin/bash

MAXPROCS=${MAXPROCS:-8}
RAILS_ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"

enable_pages_flag() {
  flag=$1
  echo "enabling flag $flag"

  $RAILS_ROOT/bin/safe-ruby $RAILS_ROOT/script/toggle-feature-flag enable $flag
}
# Make this function available for xargs to call.
export -f enable_pages_flag

enable_pages_flags() {
  echo "Enabling Pages flags. Starting $MAXPROCS processes."
  echo "ℹ️  Override by setting MAXPROCS on the command line."

  # This list is from https://github.com/github/pages-engineering/issues/537
  flag_arr="
    private_pages
    pages_org_toggle
    pages_github_app
    pages_features_checks_api
    pages_beta_image
    pages_beta_replication_strategy
    pages_gc
    pages_build_metrics
    pages_build_recycle
    pages_build_based_allocation_enabled
    private_pages_org_toggle
    pages_alt_domain
    pages_health_check
    pages_domain_duplication
    load_acme_client_from_vault
    pages_domain_protection"

  # Use xargs to call multiple instances of toggle-feature-flag concurrently.
  echo "$flag_arr" | xargs -P $MAXPROCS -I{} bash -c 'enable_pages_flag {}'
}

enable_pages_flags

echo "Done!"
