#!/bin/bash
set -e

### Bail out early if preconditions aren't met: ###

if lsof -Pi :8152 -sTCP:LISTEN -t >/dev/null ; then
  # gitrpc server running
  :
else
  echo -e "Your server is not running. Please start it with ./script/server and try again."
  exit 1
fi

bin/rake db:abort_if_pending_migrations

###################################################

GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "\n${GREEN}➡️ Setting up Copilot...\n${NC}"
./bin/setup-copilot -E -c

echo -e "\n${GREEN}➡️ Mirror prod-enabled feature flags...\n${NC}"
./bin/toggle-global-flags --enable

echo -e "\n${GREEN}➡️ Running enable-copilot-chat-skills...\n${NC}"
./bin/enable-copilot-chat-skills

echo -e "\n${GREEN}➡️ Running copilot4prs seed script...\n${NC}"
./bin/seed copilot4prs

echo -e "\n${GREEN}➡️ Enabling models for development...\n${NC}"
./bin/enable-copilot-chat-dev-models

echo -e "\n${GREEN}➡️ Copilot enterprise admin \`cfbbizentadmin\` created...${NC}"
echo -e "\n${GREEN}➡️ Copilot org admin \`cfbbizentorgadmin\` created...\n${NC}"

echo -e "\n${GREEN}➡️ Creating Copilot Chat App\n${NC}"

./bin/rails runner 'Apps::Internal::CopilotChat.seed_database!'

echo -e "\n${GREEN}➡️ Copilot setup complete!${NC}"
