#!/bin/bash

./bin/toggle-feature-flag enable code_search_code_view
./bin/toggle-feature-flag enable react_code_search_enabled
./bin/toggle-feature-flag enable react_code_view_enabled
./bin/rails r ./script/create_blackbird_flag.rb
