#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "#{Rails.root}/config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

class EnableCopilotChatSkills
  CopilotChatSkillsFeatureFlags = %w[
    copilot_api_skills_get_alert
    copilot_api_skills_get_commit
    copilot_api_skills_get_discussion
    copilot_api_skills_get_file
    copilot_api_skills_get_issue
    copilot_api_skills_get_pr_commits
    copilot_api_skills_get_release
    copilot_api_skills_get_repo
    copilot_api_skills_get_repo_security_alert_counts
    copilot_api_skills_get_file_changes
    copilot_api_plan_skill
  ].freeze

  def enable_feature_flags
    puts "Enabling Copilot chat skills feature flags"
    CopilotChatSkillsFeatureFlags.each do |flag|
      puts "-> Enabling #{flag}"
      GitHub.flipper[flag].enable
    end
    puts "Done enabling"
  end
end

EnableCopilotChatSkills.new.enable_feature_flags
