#!/usr/bin/env safe-ruby
# frozen_string_literal: true
# vim: set ft=ruby

$stdout.puts "Loading environment..."
require File.expand_path("../../config/environment", __FILE__)
require File.expand_path("../../lib/github/bones_exporter", __FILE__)

ci_mode = ENV["GITHUB_CI"].present?

options = {
  list_mode: false,
  include_test_suites: true,
  ci_mode: ci_mode,
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: bin/export-bones-data [options] <files>"

  opts.on(
    "-l", "--list",
    "Only list files that would have data exported"
  ) do
    options[:list_mode] = true
  end

  opts.on("--[no-]test-suites", "Includes test suite information for files") do |enabled|
    options[:include_test_suites] = enabled
  end

  opts.on("-h", "--help", "Prints this message") do
    puts opts
    exit
  end
end.parse!

options[:files] = ARGV.presence
options[:output] = $stdout

exporter = GitHub::BonesExporter.new(**options)
status = exporter.run! || 1
exit(status)
