#!/bin/sh
# Usage: fakemunger-server [<options>]
# Start the fake munger server in development mode.
# When specified, <options> are passed through to the Sinatra app.
set -e

exec bin/safe-ruby lib/munger/fake_server.rb "$@"
