#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "ownership-detector"
require "optparse"

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: find-serviceowner-tests [org_name] [options]"

  opts.on("-t", "--team TEAM", "Team name to find the service owner's test files for. For the list of teams use the `--list_teams` option.") do |team|
    options[:team] = team
  end

  opts.on("--list_teams", "Print the list of teams that owns the test files.") do
    options[:list_teams] = true
  end

  opts.on("--stats_by_org", "Print stats, broken down by organizations, for the test files.") do
    options[:stats_by_org] = true
  end

  opts.on("-i", "--include_pattern PATTERN", "Filename pattern for including files.") do |pattern|
    options[:include_pattern] = pattern
  end

  opts.on("-e", "--exclude_pattern PATTERN", "Filename pattern for excluding files.") do |pattern|
    options[:exclude_pattern] = pattern
  end

  opts.on("-f", "--filename_pattern PATTERN", "Additional filename pattern to match against.") do |pattern|
    options[:filename_pattern] = pattern
  end
end.parse!

detector = OwnershipDetector.new(include_pattern: options[:include_pattern], exclude_pattern: options[:exclude_pattern],
  test_pattern: options[:filename_pattern])

if org = ARGV[0]
  puts detector.tests_for_org(org)
  exit 0
end

if options[:list_teams]
  puts detector.tests_by_maintainer.keys
end

if options[:team]
  puts detector.tests_by_maintainer[options[:team]]
end

if options[:stats_by_org]
  detector.ownership_stats
end
