#!/usr/bin/env bash

# returns tests for the "github" build
# script/find-tests
# tests for the meta build
# script/find-tests --meta
# tests for the acceptance build
# script/find-tests --acceptance

set -e

if [[ "$JANKY_ENV_TEST_SUBSET" != "" ]]; then
  # This environment variable contains space-delimited suite names,
  # which should get replaced with newlines to match the format of
  # the other output of this script.
  echo $JANKY_ENV_TEST_SUBSET | tr ' ' '\n'
elif [ "$GAUNTLET" == "1" ]; then
  script/find-changed-tests-for-ci
elif [ "$CI_AUTHZ_TEST" == "1" ]; then
  echo "test/test_helpers/rest_authz/runnable_class_test.rb"
elif [ "$CI_SYSTEM_TEST" == "1" ]; then
  bin/safe-ruby script/find-serviceowner-tests "$JANKY_ENV_SERVICE_OWNER" -i "^test/system/.*_test.rb" -e "^app"
elif [ "$CI_FAST_TEST" == "1" ]; then
  find test/fast -name \*_test.rb
elif [ "$CI_API_INTEGRATION_TEST" == "1" ]; then
  find test/integration/api -name \*_test.rb
elif [ "$CI_CLUSTER_DEPENDENCY_TEST" == "1" ]; then
  find packages/*/test/integration/**/*_test.rb test/integration/**/*_test.rb test/integration/*_test.rb -type f -not -path "*test/integration/api*"
elif [ -n "$JANKY_ENV_SERVICE_OWNER" ]; then
  FILE_FILTER_ARGS=""
  if [ -n "$TEST_FILENAME_FILTER" ]; then
    FILE_FILTER_ARGS="-f $TEST_FILENAME_FILTER"
  fi
  bin/safe-ruby script/find-serviceowner-tests "$JANKY_ENV_SERVICE_OWNER" $FILE_FILTER_ARGS
else
  { find test -name \*_test.rb -and -not -path test/meta\* -not -path test/system\* -not -path test/test_helpers\* -not -path test/fixtures\* -not -path test/fast\*  -and -not -path test/system\* ; find packages -path \*/test/\* -name \*test\*.rb ; } | cat
fi
