#!/usr/bin/env safe-ruby
# frozen_string_literal: true

# Strip the '/build/' prefix off a stackprof dump so it can be analyzed in dev.
# Download a prod dump by appending
#   ?flamegraph=1&flamegraph_output=raw
# to any github.com URL.

if !ARGV[0]
  puts "Usage: #{File.basename(__FILE__)} dump_file [output_file] [prefix_to_strip]"
  exit(1)
end

new_file = ARGV[1] || "stripped_#{File.basename(ARGV[0])}"
if File.exist?(new_file)
  puts "#{new_file.inspect} exists, refusing to overwrite!"
  exit(1)
end
prefix_to_strip = ARGV[2] || "/build/"
dump = Marshal.load(File.binread(ARGV[0]))
dump[:frames].each_value { |v| v[:file].delete_prefix!(prefix_to_strip) }
File.binwrite(new_file, Marshal.dump(dump))
puts new_file
