#!/bin/bash
# Creates the github.localhost SSL certificate for nginx.
#
# Optionally run script/install-nginx-cert to install the generated certificate
# into the system keychain.

# START OF SHARED CODE
# Shared by `generate-nginx-cert` and `install-nginx-cert`. Please update one if
# you update the other.
set -e

function plz_install_deps {
  echo "Please make sure \`mkcert\` and \`nss\` are installed."
  echo "Run \`script/bootstrap\` to install."
  exit 1
}

which mkcert >/dev/null || plz_install_deps

cert_dir=$(dirname "$0")/../config/dev/ssl
mkdir -p ${cert_dir}
cd ${cert_dir}

# IMPORTANT: Here, we tell `mkcert` to work only in the cert folder for the rest
# of this script. This prevents messing with other uses of `mkcert` on the
# system.
export CAROOT="$(pwd)"

leaf_key_file=github.localhost.key
leaf_cert_file=github.localhost.crt
root_ca_key_file=rootCA-key.pem
root_ca_cert_file=rootCA.pem
# END OF SHARED CODE

if [ -f ${root_cert_file} ]
then
  # Remove old CA, since we don't have the key from previous runs (see below).
  echo "----------------"
  echo "Detected an old root CA."
  echo "Attempting to remove the old CA before generating a new one."
  echo "This may ask for your permission to modify the operating system."
  echo "If the old CA is not installed, this may show an error (which you can ignore)."
  echo ""
  mkcert -uninstall || true
  rm ${root_ca_cert_file}
  rm -f ${root_ca_key_file}
fi

echo "----------------"
echo "Creating a root CA and using it to issue a cert for local test domains."
echo "We use \`mkcert\` for this, which may show warnings,"
echo "because we are generating certificates without trusting them yet."
echo ""
mkcert "github.localhost" "*.github.localhost" "*.githubusercontent.dev"

echo "----------------"
echo "Throwing away the root CA key, so that no one can use it to sign certs"
echo "that can intercept traffic for additional domains."
echo ""
rm -f ${root_ca_key_file}

# Move leaf cert files after deleting CA key, in case something goes wrong (e.g.
# permission issues with existing leaf files).
mv github.localhost+2-key.pem ${leaf_key_file}
mv github.localhost+2.pem ${leaf_cert_file}

echo "----------------"
echo "Root CA and certificate generated."
echo ""
echo "Run \`script/install-nginx-cert\` to install."
