#!/bin/bash
# Usage: gh-clone-url <user>/<repo>

cloneUrl=$(git config remote.origin.url)

if [[ "$cloneUrl" == "https://github.com/"* ]]; then
  echo "https://github.com/$1.git"
elif [[ "$cloneUrl" == "git@github.com:"* ]]; then
  echo "git@github.com:$1.git"
elif [[ "${GITHUB_SERVER_URL:=https://github.com}" == "https://gh-mirror.trafficmanager.net" ]]; then    # we're on the resiliency mirror
  echo "https://gh-mirror.trafficmanager.net/$1.git"
elif [ -f "$HOME/.git-credentials" ]; then    # we're using an injector image with docker
  echo "https://github.com/$1.git"
else
  echo "git@github.com:$1.git"
fi
