#!/usr/bin/env safe-ruby
#
#/ Creates an environment for executing pre-receive hooks
#/
#/ Usage: ghe-hook-env-create <name> <image>
#/
#/  name         The name of the environment
#/  image        A url or path of the environment tarball
#/
#/ OPTIONS:
#/   -h, --help         Show this message

if ARGV.include?("--help") || ARGV.include?("-h") || ARGV.length != 2
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end
env_name, image_url = ARGV

require_relative "../config/environment"

begin
  env = GitHub::PreReceiveEnvCli.create_env env_name, image_url
  puts "Pre-receive hook environment '#{env.name}' (#{env.id}) has been created."
rescue GitHub::PreReceiveEnvCli::Error => e
  abort e.message
end
