#!/usr/bin/env safe-ruby
# frozen_string_literal: true
#
#/ Usage: ghe-reset-gh-connect
#/
#/ This utility clears all GitHub Connect settings for use when restoring GitHub Enterprise Server instances.
#/ This should only be run after restoring a backup of the GitHub Enterprise Server instance.
#/
#/ OPTIONS:
#/   -h, --help         Show this message
#/   -y                 Bypass the confirmation prompt.

require "optparse"

def help!
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

bypass_warning = false

ARGV.options do |opts|
  opts.on("-y")                { bypass_warning = true }
  opts.on_tail("-h", "--help") { help! }
  opts.parse!
end

require File.expand_path("../../config/environment", __FILE__)

unless bypass_warning
  printf "WARNING: This will clear all GitHub Connect settings on this instance. Do you want to proceed? (y/N) "
  exit(0) if STDIN.gets.chomp.downcase != "y"
end

DotcomConnection.new.reset(User.ghost)

# vim:filetype=ruby
