#!/usr/bin/env safe-ruby
#
#/ Usage: ghe-reset-gh-connect-server-id
#/
#/ This utility resets the id that is given to GitHub.com to uniquely identify this server
#/
#/ OPTIONS:
#/   -h, --help         Show this message
#/   -y                 Bypass the confirmation prompt.

require "optparse"

def help!
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

bypass_warning = false

ARGV.options do |opts|
  opts.on("-y")                { bypass_warning = true }
  opts.on_tail("-h", "--help") { help! }
  opts.parse!
end

require File.expand_path("../../config/environment", __FILE__)

unless bypass_warning
  printf "WARNING: This will reset the id that GitHub.com will use to identify this server. Do you want to proceed? (y/N) "
  exit(0) if STDIN.gets.chomp.downcase != "y"
end

puts "Your new server id is #{DotcomConnection.new.reset_server_id}"
