#!/usr/bin/env safe-ruby
#
#/ Usage: ghe-user-suspend <username> [reason] [options]
#/
#/ This utility suspends the given user.
#/
#/ OPTIONS:
#/   -h, --help         Show this message

if ARGV.empty? || ARGV.include?("--help") || ARGV.include?("-h")
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

require_relative "../config/environment"

username = ARGV.shift
reason   = ARGV.join(" ")

unless user = User.find_by_login(username)
  abort "User not found: #{username}"
end

if user.organization?
  abort "Organization #{username} cannot be suspended."
elsif user.suspended?
  abort "User #{username} is already suspended."
else
  if reason.empty?
    user.suspend "suspended via ghe-user-suspend"
  else
    user.suspend "suspended via ghe-user-suspend - reason: #{reason}"
  end
  puts "User #{username} has been suspended. Use ghe-user-unsuspend to reverse this action."
end
