#!/usr/bin/env safe-ruby
#
#/ Usage: ghe-user-promote <username> [options]
#/
#/ This utility promotes the given user to a site admin.
#/
#/ OPTIONS:
#/   -h, --help         Show this message

if ARGV.empty? || ARGV.include?("--help") || ARGV.include?("-h")
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

require_relative "../config/environment"

if GitHub.site_admin_role_managed_externally?
  if GitHub.auth.ldap?
    abort "Promote users by adding them to your LDAP admin group: #{GitHub.ldap_admin_group}"
  elsif GitHub.auth.saml?
    abort "Promote users by using your SAML identity provider or disable SAML-based administrator demotion/promotion within the management console to use this command."
  end
end

username = ARGV.first

unless user = User.find_by_login(username)
  abort "User not found: #{username}"
end

if user.suspended?
  abort "User #{username} is suspended. Use ghe-user-unsuspend to unsuspend them first."
end

if user.site_admin?
  abort "User #{username} is already a site admin."
end

user.grant_site_admin_access "promoted via ghe-user-promote"

puts "User #{username} promoted to site admin. Use ghe-user-demote to reverse this action."

# vim: set syntax=ruby:
