#!/usr/bin/env safe-ruby
#
#/ Usage: ghe-user-unsuspend <username> [options]
#/
#/ This utility unsuspends the given user.
#/
#/ OPTIONS:
#/   -h, --help         Show this message

if ARGV.empty? || ARGV.include?("--help") || ARGV.include?("-h")
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

require_relative "../config/environment"

username = ARGV.first

unless user = User.find_by_login(username)
  abort "User not found: #{username}"
end

if user.suspended?
  if user.unsuspend "unsuspended via ghe-user-unsuspend"
    puts "User #{username} has been unsuspended. Use ghe-user-suspend to reverse this action."
  else
    abort "#{user.errors.full_messages.join(" ")}"
  end
else
  abort "User #{username} is not suspended."
end
