#!/bin/sh
#/ Usage: ghe-dpages-transition <transition-dir>
#/ Migrate the pages filesystem data to the dpages layout using the given
#/ transitional directory. <transition-dir> must exist and be owned by the git
#/ user. The existing pages directory is left in place after a successful
#/ transition. It is the caller's responsibility to move the transitioned
#/ hierarchy into place and to clean up the old hierarchy.
set -e

if [ "$1" = "--help" ] || [ $# -eq 0 ]; then
    grep "^#/" <"$0" | cut -c4-
    exit 1
fi

cd "$(dirname "$0")"/..
exec bin/safe-ruby lib/github/transitions/20150902132100_enterprise_dpages_transition.rb "$@"
