#!/usr/bin/env ruby
# frozen_string_literal: true

require File.expand_path("../../config/basic", __FILE__)
require "github/routing"

GitHub.load_activerecord

def process(gist)
  begin
    puts "#{gist} #{GitHub::Routing.lookup_gist_id(File.basename(gist, ".git"))}"
  rescue GitHub::Routing::NoSuchRoute
    ## Ignore archived gists
  end
end

while line = $stdin.gets
  process(line.strip)
end
