#!/usr/bin/env ruby

require File.expand_path("../../config/basic", __FILE__)
require "github/dgit"
require "github/routing"

GitHub.load_activerecord

def host_picker
  @picker ||= GitHub::DGit::HostPicker.new
end

def process(gist)
  begin
    gist_id = GitHub::Routing.lookup_gist_id(File.basename(gist, ".git"))
    hosts = GitHub::DGit::Routing.all_hosts_for_gist(gist_id) & GitHub::DGit.get_hosts
    if hosts.empty?
      hosts = host_picker.pick_fileservers(GitHub.dgit_default_copies, exclusions: [], far_from: [], no_raise: true).map { |fs| fs.name }
    end
    puts "#{gist} #{hosts.join(' ')}"
  rescue GitHub::Routing::NoSuchRoute
    ## Ignore archived gists
  end
end

while line = $stdin.gets
  process(line.strip)
end
