#!/bin/bash
#
# Launch gitrpcd server with the given port and repo path
#
# Usage:
#   gitrpcd-server  [--http-port=PORT] [--git-port=PORT] [--repository-path=PATH]

http_port=
git_port=
ernicorn_port=
repository_path=
while [ $# -gt 0 ]; do
  case "$1" in
    --git-port=*)
      git_port="${1#--git-port=}"
      shift
      ;;
    --git-port)
      git_port="$2"
      shift 2
      ;;
    --http-port=*)
      http_port="${1#--http-port=}"
      shift
      ;;
    --http-port)
      http_port="$2"
      shift 2
      ;;
    --ernicorn-port=*)
      ernicorn_port="${1#--ernicorn-port=}"
      shift
      ;;
    --ernicorn-port)
      ernicorn_port="$2"
      shift 2
      ;;
    --repository-path=*)
      repository_path="${1#--repository-path=}"
      shift
      ;;
    --repository-path)
      repository_path="$2"
      shift 2
      ;;
    -*)
      printf >&2 "%s: unexpected option: '%s'" "$0" "$1"
      exit 1
      ;;
    *)
      printf >&2 "%s: unexpected argument: '%s'" "$0" "$1"
      exit 1
      ;;
  esac
done

if  [[ "$DX_EDGE" != true ]] || [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" != true ]];  then
  export ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd)"
  export PATH="$ROOT/bin:$ROOT/git-bin:$PATH"
  GIT_EXEC="vendor/git-core/libexec/git-core"

  until [ -x "$GIT_EXEC/git" ]; do
    if [ "$GIT_BIN" != "1" ]; then
      echo "Run 'script/build-git' to setup git (needed for gitrpcd)."
      GIT_BIN=1
    fi
    sleep 60
  done

  export HOME="$(pwd)/$GIT_EXEC"
fi

exec script/launch-gitrpcd --exec-path="$GIT_EXEC" --git-port $git_port --http-port $http_port --ernicorn-port $ernicorn_port --repository-path "$repository_path"

