#!/usr/bin/env sh
set -eu
# This script is used to determine where GitRPCD should be looking for repositories.
# In Enterprise mode, repositories are stored under the "fi" directory, but in DotCom mode they are stored under the "development" directory.

if [ "$(cat ./tmp/runtime/current 2>/dev/null)" = "enterprise" ]; then
  echo "fi"
else
  echo "development"
fi
