#!/usr/bin/env ruby
# frozen_string_literal: true

unless Rails.env.development?
  raise "This is a dev-only script"
end

require_relative "../config/environment"
require "global_id_migration"

GlobalIdMigration::CLI.start
