#!/bin/bash
set -e

export RAILS_ENV=test
export GITHUB_CI=1

if [ "$DISTRO_CODENAME" == "stretch" ]; then
  export SKIP_NODE=true
fi

# Bootstrap our base dependencies
script/bootstrap --local --deployment

# Bootstrap RUBY_NEXT dependencies
RUBY_NEXT=1 script/bootstrap --local --deployment

# Strip out everything that isn't vendor, basically
script/clean-golden-vendor
ls -1 | grep -v vendor | xargs rm -rf
