#!/bin/bash

RAILS_ROOT=$(cd "$(dirname "$0")/.." && pwd)
export GPGVERIFY_PORT=${GPGVERIFY_PORT:-8686}
export GPGVERIFY_WEB_SIGNING_KEY="-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAuOuG6AGpPxXLjxWL/ZFiXjB+pNdRCgcZ8Vree3cPQHWGYGjH
EVeQ+pwlwvJWU/q4CtX1ZhRc7F6JeNg/iaaZWGkjDMXSDXKONuEP0nRkDtavF0fS
xA1biPL5FGeRUuJZ/1DOe9YvmBndgeOehaMQuBbKZZyfr2LQFa/M+ji0ZbUT3svs
rLmd/71Wx5sqkotVx4pPsvja+pu/HVjITSy4N28RC+s6VBeO/2yQSzw105q/6WG3
tI2mMDTR88RtALc40OX9V9apKEqzaDEjjLeIJ9cAILxW1Rivis0GdgoBhX7gXmzU
0N3GoTJ97MpZNjeta95VStXw+57jc72e1p9RwQIDAQABAoIBAQCwADuehjY3vN7J
iJB8/urJCw7+hZC0Ip4mgX5PtLnnd/Q1voP5lYZ/gC7QpSZVN8QDTDEMv0TSFAhz
5B5VPSOmairZ9U4/TlDdGsicXfr9xIdReSK5Rp1gcyFuskQ2xwkxYA+m/ey+r5+M
CMDQIKvBCrAIllHF9B5pBbHqVh4czeSExtCTFrTRWtb0wCpTmKtS3s12tu9y2i90
OAIc0zBYUxvU/2M93elCF/LkDLjd6Pn5sJpJ7VAOq8Pj+QilrJqadxm0KfLA2ZrW
l1zDW9hFoHgAscEETdn35zP3gb8cascepJg1zicUZ1veTixemI5q+TSdtj+hVxew
+/OK/VShAoGBAOrHZdKVbgeN78HzD7IbdCtFCEJ8c8WFNwR76IPDTc5pXwIMrxrJ
RMUbIdTCG9L+DXwJ2+5c+Bge8RAGXuVyp6iuONeov44s1DKPI5wiU4I53P4kb+MX
42DP+2tUxQmHhuAG91vdhc7F90PHtJYwldvQkFjNYDaZL5bJ8HXmpI7nAoGBAMmi
bvpM+vuSA4ZipnaUCXqkFmxXPIe152U8+KnXf9cTW/wNRjO2jWpyIEqr9syUNNAo
gAY8unOFnBFzRRqvfwfIgnJvNv2mmquYhtVqfJmsNXIKT6mouZlvMwGKtL0IAgik
gMWSwVevkdb/lMhBd3ntfM7bQJ1taAGbPcq17U0XAoGBAJ+uauSlWaattOo3BO/g
mExtsUZ3Gs624kqcc/JaPWssY8AjHF2dkrZ007e/JemFfWpl0j324Y6WTOLXUmfA
aaPiiyqyzUZH2zNgA5pIBoBGFraL1cWhE7de/eNsTm9CzEtGsaq7qiyOnLRu+bZE
6UgOPH8JgGziF2n5gyDNdBL1AoGAQsqAsn7/gIfcjQ5uj8b34N0r5FV9YoL6FIn+
4NvWqBrslHCdOZIWBBWr5rBR/3B0kiNoTSieppeynAEv+ef6T0y3EUsPzzP59i9/
MoCkp47o4U7TFqMiX9X68l7NAfT+H3jGgyvayb4JtEtTMIanGgd2GVt9auiL1ERl
Upmy8p8CgYACio8rlG8LiCAhlnqEKBq8pyQpDh0MN++YqT0l8LrGNNAijupWODw6
g3aCZ+1CMOgKkEJnvGOgfceDucAFAyo3VwOHR33scO4MCavYfBgbL9kEtsQVgHhM
8Zl/V5EcaZFus6zQjxEpNLRCQEvPeopcIXSM4Sm23s/hP7BbNjJPSA==
-----END RSA PRIVATE KEY-----"

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source $SCRIPT_DIR/dx/lib/subproject-containers

if [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
    SUBPROJECT_VERSION=$(subproject_version "gpgverify")
    echo "gpgverify version $SUBPROJECT_VERSION"

    NAME="gpgverify"

    # Mount the current dir as tests will delete the $repository_path folder, breaking the mounts
    # This will break if $repository_path isn't under the current directory
    start_subproject --name=$NAME \
      -e GPGVERIFY_WEB_SIGNING_KEY \
      ghcr.io/github/gpgverify/gpgverify:$SUBPROJECT_VERSION \
      /build/bin/gpgverify -skipPrivateKeyValidation -listen 127.0.0.1:$GPGVERIFY_PORT
else
  exec vendor/gpgverify/bin/gpgverify -skipPrivateKeyValidation -listen 127.0.0.1:$GPGVERIFY_PORT
fi
