#!/usr/bin/env ruby
# frozen_string_literal: true

warn "Loading rails environment..."
$stderr.sync = true
require File.expand_path("../../config/basic", __FILE__)
require_relative "../config/environment"

require "securerandom"
require "thor"

Dir.glob(Rails.root.join("lib/github/stream_processors/**/*.rb")).each { |f| require f }
# This will suppress log statements from the Hydro consumer and the Kafka client it initializes.
Hydro.consumer_logger = GitHub::Telemetry::Logs.null_logger
GitHub::StreamProcessors::DeadLetter::CLI.start(ARGV) if $PROGRAM_NAME == __FILE__
