#!/bin/bash
#/ This is meant to be run from script/build-ruby.
#/ Usage: install-bundler <ruby-prefix>
#/ Install a different version of bundler than the one that ships with Ruby

set -e

BUNDLER_VERSION="2.5.4"

function install_github_bundler() {
  local prefix=${1}
  local ruby_version="$(ls ${prefix}/lib/ruby/gems)"

  [[ -d "${prefix}/lib/ruby/gems/${ruby_version}/gems/bundler-${BUNDLER_VERSION}" ]] && return

  (
    unset GEM_HOME
    unset GEM_PATH
    "${prefix}/bin/gem" install --no-document --force --default bundler:$BUNDLER_VERSION
    "${prefix}/bin/gem" install --no-document --force bundler:$BUNDLER_VERSION
  )
}

install_github_bundler $1
