#!/bin/bash
#/ Usage: script/kafka-lite-server
#/
#/ Runs kafka-lite service.

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
CONFIG_DIR=$(readlink -f "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/../config")

arg_topics=$(cat $CONFIG_DIR/kafka-server-seeds)

if [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
  source $SCRIPT_DIR/dx/lib/subproject-containers

  SUBPROJECT_VERSION=$(subproject_version "kafka-lite")
  echo "kafka-lite version $SUBPROJECT_VERSION"

  cleanup_docker() {
    echo "Stopping kafka-lite..."
    docker stop kafka-lite || true
  }

  trap cleanup_docker EXIT INT QUIT TERM HUP

  docker stop kafka-lite &> /dev/null || true
  docker rm kafka-lite &> /dev/null || true

  # Run the kafka-lite go service.
  docker run -d --rm --name kafka-lite --network host --entrypoint "/kafka-lite" \
    "ghcr.io/github/kafka-lite/kafka-lite:$SUBPROJECT_VERSION" \
    --listen-address 0.0.0.0:9092 \
    --advertised-listener-address kafka-lite.localhost:9092 \
    --store redis \
    --log-format production \
    --max-message-age-ms 86400000 \
    $arg_topics

  docker logs --follow kafka-lite &
  wait
else
  script/build-subproject kafka-lite || exit 1

  exec vendor/kafka-lite/bin/kafka-lite \
    --listen-address 0.0.0.0:9092 \
    --advertised-listener-address kafka-lite.localhost:9092 \
    --store redis \
    --log-format production \
    --max-message-age-ms 86400000 \
    $arg_topics
fi
