#!/bin/bash
cd $(dirname $0)/..
REDIS_VERSION=3.2.11
REDIS_PORT=6379
CONTAINER_NAME=github_redis

if [ ! -z "$GITHUB_USE_DOCKER" ];then
  if [ "$GITHUB_USE_DOCKER" -eq 1 ]; then
    echo "starting redis $REDIS_VERSION container($CONTAINER_NAME) on port $REDIS_PORT"
    docker run \
      --rm \
      --name $CONTAINER_NAME \
      -p 127.0.0.1:$REDIS_PORT:$REDIS_PORT \
      --health-cmd='redis-cli ping || exit 1' \
      --health-interval=1s \
      -v $PWD/test/config/redis.conf:/usr/local/etc/redis.conf \
      --sysctl net.core.somaxconn=10240 \
      -d redis:$REDIS_VERSION \
      /usr/local/etc/redis.conf --port $REDIS_PORT
    until [[ "$(docker inspect -f {{.State.Health.Status}} $CONTAINER_NAME)"  == "healthy" ]];do
      sleep 1
    done
    echo "container $CONTAINER_NAME started!"
  else
    echo 'Please set GITHUB_USE_DOCKER=1'
    exit 1
  fi
else
  echo 'To use Dockerized version, please set GITHUB_USE_DOCKER to either 0(false) or 1(true)'
fi
