#!/usr/bin/env safe-ruby
#/ Usage: script/ldap-user-sync <login>
#/ Synchronize a User with LDAP. User login required.
$stderr.sync = true
require File.expand_path("../../config/environment", __FILE__)
require "optparse"

unless ENV["ENTERPRISE"]
  abort "enterprise mode required for #{$0}. Run script/setup --enterprise"
end

def usage
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

ARGV.options do |opts|
  opts.on_tail("-h", "--help") { usage }
  opts.parse!
end

login = ARGV.shift
user  = User.find_by_login(login)

usage unless login.present?

unless user
  warn "User #{login} not found"
  exit 1
end

LdapUserSyncJob.perform_later(user.id)
