#!/bin/sh

script/build-subproject librarian || exit 1

LIBRARIAN_BIN="vendor/librarian/bin/librariand"
until [ -x "$LIBRARIAN_BIN" ]; do
  # keeps this process alive, which keeps overmind alive.
  # Because librarian is an optional subproject, this process
  # needs to stay alive even if librarian didn't build.
  sleep 60
done

exec $LIBRARIAN_BIN
