#!/bin/bash
# Usage: licenses-cache [--source <SOURCE>]
#
# <SOURCE> is one of "rubygem", "npm", "manifest" (default: all).
set -e

root="$(cd $(dirname "$0")/.. && pwd)"
LICENSES_CONFIG="$root/vendor/licenses/config.yml"

[ -n "$GITHUB_CI" ] && exit 0

$root/bin/bundle exec licensed cache -c "$LICENSES_CONFIG" "$@"
