#!/bin/sh
#
# Verify that we know the license of all depenedencies and they are ones that
# we can comply with.

ROOT="$(cd $(dirname "$0")/.. && pwd)"
LICENSES_DIR="$ROOT/vendor/licenses"

cd "$ROOT"

bin/bundle exec licensed status -c "$LICENSES_DIR/config.yml" "$@"

RET=$?
if [ $RET -ne 0 ]; then
  echo
  echo "See https://thehub.github.com/engineering/development-and-ops/dotcom/licenses/"
  echo "/cc @github/open-source-licensing for help sorting it out."
  echo
fi

exit $RET
