#!/bin/sh

if [ "$1" = "--publish" ]; then
    publish="-p "
fi

bin/safe-ruby lib/github/transitions/20171012182134_populate_vulnerabilities_from_sheets.rb $publish-w -v --filename=data/vulnerabilities.csv
