#!/usr/bin/env ruby
# Usage: load-fake-health-checks [<repository>]
# Load fake health check data for <repository> or defunkt/dotjs when no
# <repository> is given.

require File.expand_path("../../config/environment", __FILE__)
repository = Repository.with_name_with_owner(ARGV[0] || "defunkt/dotjs")

puts "Loading health checks for #{repository.name_with_owner}"

check = repository.health["disk_usage"]
check.value = check.severe_threshold + 250.megabytes
check.status = RepositoryHealth::SEVERE
check.save!

check = repository.health["branch_count"]
check.value = check.warning_threshold + 532
check.status = RepositoryHealth::WARN
check.save!

check = repository.health["tag_count"]
check.value = check.warning_threshold + 311
check.status = RepositoryHealth::WARN
check.save!
