#!/usr/bin/env safe-ruby
# frozen_string_literal: true

# Run this script to replace hex values in marketing icon SVGs with CSS variables to support color modes.
# Usage: ./bin/marketing-icon-svg

IMAGE_PATHS = [
  "public/static/images/modules/projects/octicon-plan-project.svg",
  "public/static/images/modules/projects/octicon-get-organized.svg",
  "public/static/images/modules/projects/octicon-automate-workflow.svg",
  "public/static/images/modules/projects/octicon-track-progress.svg",
  "public/static/images/modules/projects/octicon-share-status.svg",
  "public/static/images/modules/projects/octicon-finish-project.svg",
  "public/static/images/modules/notifications/code-alert.svg",
  "public/static/images/modules/site/features/actions-icon-actions.svg",
]

REPLACEMENTS = {
  "\"#2088FF\"" => "\"var(--color-marketing-icon-primary, #2088FF)\"",
  "\"#79B8FF\"" => "\"var(--color-marketing-icon-secondary, #79B8FF)\"",
}

IMAGE_PATHS.each do |image_path|
  absolute_path = Rails.root.join(image_path)
  contents = File.read(absolute_path)
  REPLACEMENTS.each do |hex, css_var|
    contents.gsub!(hex, css_var)
  end
  File.write(absolute_path, contents)
end
