#!/usr/bin/env ruby

require File.expand_path("../../config/environment", __FILE__)
require "optparse"

# Run as a single process
if __FILE__ == $0
  $stdout.sync = true

  # Use the readonly DB in production
  #
  # - This script shouldn't touch MySQL, but just in case.
  if Rails.env.production? && !GitHub.enterprise?
    ActiveRecord::Base.connecting_to(role: :reading)
  end

  options = {}
  test = true

  ARGV.options do |opts|
    opts.on("-r",  "--run") { test = false }
    opts.on("-s", "--source-url SOURCE_URL") do |arg|
      options.merge!(source_url: arg)
    end
    opts.on("-v", "--verbose") do |_arg|
      options.merge!(verbose: true)
    end
    opts.on("-sn", "--source-name SOURCE_NAME") do |arg|
      options.merge!(source_name: arg)
    end
    opts.on("-d",  "--destination-url DESTINATION_URL") do |arg|
      options.merge!(destination_url: arg)
    end
    opts.on("-dn",  "--destination-name DESTINATION_NAME") do |arg|
      options.merge!(destination_name: arg)
    end
    opts.parse!
  end

  migrator = Audit::Elastic::Migrator.new(options)

  if test
    migrator.test
  else
    migrator.run
  end
end
