#!/bin/bash

# if no args, then show usage and exit
[ $# -eq 0 ]

# args with default values
RULE_NAMES=$1 # comma-separated-rule names (e.g. AnotherRule,GitHub::Accessibility::SomeRule)
shift 1

# process named args
while getopts "f:s:u:h" arg; do
  case "$arg" in
    f)
      FOLDER_NAME="${OPTARG}"
      ;;
    *)
      echo "help"
      ;;
  esac
done

COMMIT_MESSAGE="migrating erblint-disable for $RULE_NAMES"
PR_TITLE="[erblint-disable Migration] updating disables for $RULE_NAMES"

remove_colon="${RULE_NAMES//::/_}"
clean_branch_name="${remove_colon//,/_and_}"

BRANCH_NAME="migrate-erblint-disable/${clean_branch_name}"
PR_TEMPLATE="script/migrate-erblint-disables.pr.template"
PR_REVIEW_TEAM="@github/primer-rails-reviewers"

script/erblint-disable $RULE_NAMES

# create the PRs if any files have been updated
if [[ `git status --porcelain` ]]; then
  echo "Creating pull requests by code owner teams"
  script/create-prs-by-codeowners "$COMMIT_MESSAGE" "$PR_TITLE" "$PR_TEMPLATE" "$BRANCH_NAME" "$PR_REVIEW_TEAM"
else
  echo "No files in git have been modified. Exiting without creating pull requests"
fi
