#!/bin/bash
MYSQL_VERSION=5.7.21
MYSQL_PORT=3306
CONTAINER_NAME=github_mysql

cd $(dirname $0)/..

if [ ! -z "$GITHUB_USE_DOCKER" ];then
  if [ "$GITHUB_USE_DOCKER" -eq 1 ]; then
    echo "starting MySQL $MYSQL_VERSION container($CONTAINER_NAME) on port $MYSQL_PORT"
    docker run \
      --rm \
      --name $CONTAINER_NAME \
      -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
      -e TZ=America/Los_Angeles \
      -p 127.0.0.1:$MYSQL_PORT:$MYSQL_PORT \
      -v $PWD/test/db/conf.d/github.cnf:/etc/mysql/conf.d/github.cnf \
      --health-cmd='mysqladmin -uroot -h127.0.0.1 ping || exit 1' \
      --health-interval=1s \
      -d mysql:$MYSQL_VERSION
    until [[ "$(docker inspect -f {{.State.Health.Status}} $CONTAINER_NAME)"  == "healthy" ]];do
      sleep 1
    done
    echo "contaoner $CONTAINER_NAME started!"
  else
    echo 'Please set GITHUB_USE_DOCKER=1'
    exit 1
  fi
else
  echo 'To use Dockerized version, please set GITHUB_USE_DOCKER to either 0(false) or 1(true)'
fi
