#!/usr/bin/env ruby

$stderr.sync = true
require_relative "../config/environment"

def usage!
  $stderr.puts "Usage: network-maintenance [schedule $network-id] [run! $network-id] [retry [max]]"
  exit 1
end

usage! if ARGV.empty?

def given_network
  usage! unless ARGV.size > 1

  network = RepositoryNetwork.find_by_id(ARGV[1].to_i)
  if network.nil?
    $stderr.puts "Failed to find network #{ARGV[1]}"
    exit 1
  end

  network
end

case ARGV[0]
when "schedule"
  given_network.schedule_maintenance
when "run!"
  begin
    given_network.perform_maintenance
  rescue => boom # rubocop:todo Lint/GenericRescue
    $stderr.puts boom.to_s
  end
when "retry"
  max = if ARGV.size > 1
    ARGV[1].to_i
  else
    10
  end
  RepositoryNetwork.schedule_maintenance_retries(max)
else
  usage!
end
