#!/bin/bash
set -e

root=$(cd $(dirname "$0")/.. && pwd)

node="$root"/bin/node
npm="$root"/vendor/node/npm
node_flags=""

export PATH="$root/vendor/node:$PATH"

if [ "$CI" == "true" ] && [ -f /.github-full-focal-ecs-self-hosted-runner ]; then
  node_flags="--dns-result-order=ipv4first"
fi

$mode "$node" $node_flags "$npm" "$@"
