#!/bin/bash
# This script should be run after npm dependencies are changed. It is responsible for ensuring licenses are up
# to date, and that packages are patched up if necessary.
set -e

# Hoist all packages to the top-level node_modules
./script/hoist-node-modules

# Copy mathjax static assets
./script/copy-mathjax-static-assets

# Run licensed cache to keep license files up to date
if ! ./script/licenses-cache --sources npm 2>/dev/null ; then
  echo "❌ Failed to update license cache. Please run the following command:"
  echo ""
  echo "  ./script/bootstrap && ./script/licenses-cache --sources npm"
  echo ""
  exit 1
fi
