#!/bin/bash
set -e

root=$(cd $(dirname "$0")/.. && pwd)

node="$root"/bin/node
npx="$root"/vendor/node/npx

node_flags=""

if [ "$CI" == "true" ] && [ -f /.github-full-focal-ecs-self-hosted-runner ]; then
  echo "In CI and running with ipv4 dns result order"
  node_flags="--dns-result-order=ipv4first"
fi

$mode "$node" $node_flags "$npx" "$@"
