#!/bin/bash
#/ Usage: script/openapi-branch-releases [-h|--help]
#/
#/ Output the list of OpenAPI release identifiers that appear related to the
#/ code in this branch.
#/
#/ This script only checks build artifacts (i.e., GHES' "ENTERPRISE_RELEASE")
#/ and does not rely on application configuration, which may not be
#/ set appropriately in CI for some release types. To
#/ determine the current release more definitively, loading application
#/ configuration, see `bin/openapi help current-release` (or, in runtime code,
#/ `OpenApi::Description::Release.current`).
#/
#/ This script can be used in conjunction with various `bin/openapi` commands:
#/
#/ Generating root files:
#/
#/     $ script/openapi-branch-releases | xargs bin/openapi generate-root-files
#/
#/ Verifying root files:
#/
#/     $ script/openapi-branch-releases | xargs bin/openapi verify-root-files
#/
#/ Building bundled/dereferenced artifacts:
#/
#/     $ script/openapi-branch-releases | xargs bin/openapi bundle -o /tmp/dump
#/
set -eu

while [ $# -gt 0 ]; do
        case "$1" in
                -h|--help)
                        grep ^#/ <"$0" |cut -c4-
                        exit
                        ;;
                *)
                        shift
                        ;;
        esac
done

if [ -f "ENTERPRISE_RELEASE" ]; then
  echo ghes-$(cat ENTERPRISE_RELEASE | tr -d '\n')
else
  echo api.github.com
fi
