#!/usr/bin/env ruby
# frozen_string_literal: true

require "open_api"

unless defined?(::GitHub)
  module ::GitHub
    def self.openapi_include_test_fixtures?
      false
    end
  end
end

unless defined?(::GitHub::AppEnvironment)
  module GitHub::AppEnvironment
    def self.root
      Pathname.new("..").expand_path(File.dirname(__FILE__))
    end
  end
end

OpenApi::CLI::Root.start
