#!/usr/bin/env ruby
# frozen_string_literal: true

require "yaml"

# Check if there are changes to the OpenAPI description
# git diff --quiet returns an error code if that's the case
if !system("git diff --quiet origin/master..HEAD -- app/api/description")
  release_file = `git show origin/master:app/api/description/config/release.yaml`
  main_release = YAML.load(release_file)
  branch_release = YAML.load_file("app/api/description/config/release.yaml")
  exit(1) if Gem::Version.new(branch_release["info"]["version"]) <= Gem::Version.new(main_release["info"]["version"])
end
