#!/usr/bin/env ruby
# frozen_string_literal: true
#/ Takes in one or more org ids and returns a list of member ids.
#/
#/ org_ids - comma-delim list of org ids

#/ Examples
#/
#/   org-member-ids 54321,54322
#/   # => 1234,1235,1236,1237
#/
#/ Returns comma-delim list of org member ids

require_relative "../config/environment"

org_ids = ARGV.shift.split(",").map(&:to_i)
orgs = Organization.where(id: org_ids)
member_ids = orgs.flat_map(&:people_ids)

puts member_ids.join(",")
exit true
