#!/bin/bash

if [ -S /tmp/overmind.sock ]; then
  if lsof_output=$(lsof -F p /tmp/overmind.sock 2>/dev/null); then
    overmind_pid=$(echo "$lsof_output" | grep '^p' | cut -c2-)
    if ps -p $overmind_pid > /dev/null; then
      exit 0
    fi
  fi
fi

exit 1
