#!/usr/bin/env ruby

require "./config/environment"
require "./config/console"

repos = Repository.all.limit(250).order(Arel.sql("RAND()"))

users = User.all.limit(250).order(Arel.sql("RAND()"))

puts "Starring and following..."
users.each do |user|
  user.star(repos.sample)
  user.follow(users.sample)
end

puts "Recalculating trending, this will take a few minutes"

CalculateTrendingReposJob.perform_later("daily")
CalculateTrendingUsersJob.perform_later("daily")
CalculateTrendingReposJob.perform_later("weekly")
CalculateTrendingUsersJob.perform_later("weekly")
CalculateTrendingReposJob.perform_later("monthly")
CalculateTrendingUsersJob.perform_later("monthly")
