#!/bin/bash
set -euo pipefail

cd "${0%/*}"/..

# assumes two working paths with the same parent:
# 1. github/github (cwd)
# 1. primer/css (../../primer/css)
primer_path="${2:-../../primer/css}"
primer_module_name="@primer/css"
primer_modules_path="node_modules/$primer_module_name"

npm="$(which -a npm | grep ^/ | head -1)"

primer_on() {
  pushd "$primer_path" > /dev/null
  "$npm" link > /dev/null
  popd >/dev/null
  "$npm" link "$primer_module_name" > /dev/null
}

primer_off() {
  rm -r "$primer_modules_path"
  bin/npm install
}

case "${1:-on}" in
  on )
    if [ ! -d "$primer_path" ]; then
      echo "Couldn't find primer repo at $primer_path"
    elif [[ -L "$primer_modules_path" && -d "$primer_modules_path" ]]; then
      echo "It looks like you're already primerized."
      echo "Revert to pristine state with \`$0 off'"
    else
      echo "Linking primer repo in $primer_path"
      primer_on $primer_path
    fi
    ;;
  off )
    if [[ -L "$primer_modules_path" && -d "$primer_modules_path" ]]; then
      primer_off
    fi
    ;;
  -h )
    echo "Usage: primerize on [../primer]"
    echo "       primerize off"
    ;;
esac
