#!/usr/bin/env ruby
require_relative "../config/environment"

puts GitHub::Application.routes.routes.map { |r|
  spec = r.ast.to_s
  verb = r.verb
  defaults = r.defaults.sort.to_h
  constraints = r.constraints.sort.to_h
  conditions = r.conditions.sort.to_h
  requirements = r.requirements.sort.to_h

  "spec=#{spec} verb=#{verb.inspect} defaults=#{defaults.inspect} constraints=#{constraints.inspect} conditions=#{conditions.inspect} requirements=#{requirements.inspect}"
}.sort
