#!/bin/bash
set -e

if [ -z "$(which esrally 2>/dev/null)" ]; then
  echo "Could not find 'esrally' executable. Please run 'script/setup-rally' and then try again."
  exit 1
fi

JAVA_HOME=/usr esrally "$@"
