#!/usr/bin/env safe-ruby
#
#/ Usage: reconcile-system-roles [options]
#/
#/ This utility reconciles role, role_permission, and fine_grained_permission
#/ records in the DB to match the definitions in config/system_roles.yml.
#/ By default, this operation is run in dry-run-mode.
#/
#/ OPTIONS:
#/   -h, --help         Show this message.
#/   -v, --verbose      Print records being added/removed.
#/   -w, --write        Write the records to the DB. If unspecified, will perform a dry run.
#/   -p, --purge        Remove records present in the DB but not in the definition.

require "optparse"

def help!
  exec "grep ^#/<'#{__FILE__}'|cut -c4-"
end

purge   = false
dry_run = true
verbose = false

ARGV.options do |opts|
  opts.on("-p", "--purge")     { purge = true }
  opts.on("-w", "--write")     { dry_run = false }
  opts.on("-v", "--verbose")   { verbose = true }
  opts.on_tail("-h", "--help") { help! }
  opts.parse!
end

if ARGV.any?
  STDERR.puts "Unknown arguments: #{ARGV.join(", ")}\n"
  help!
end

require File.expand_path("../../config/environment", __FILE__)

GitHub.system_roles.reconcile(purge: purge, dry_run: dry_run, verbose: verbose)
