#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require_relative "dx/telemetry/telemetry"

settings = [DX::Telemetry::USER_TAG, DX::Telemetry::SERVER_FEATURES, DX::Telemetry::RESILIENT]
elapsed_time = ARGV[0]
DX::Telemetry.monitor_script_runtime_with_value("dx.monolith.server.start.time", elapsed_time.to_f, tags: [], settings: settings)
