#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require_relative "dx/telemetry/telemetry"

StaffshipURL = "https://github.ghe.com"

# Get repo info
repo = ENV["RESPOSITORY_NAME"]
user = ENV["GITHUB_USER"]
server_url = ENV["GITHUB_SERVER_URL"]
version = ENV["HCS_VERSION"]
codespace_name = ENV["CODESPACE_NAME"]
codespace_name_hash = Digest::SHA256.hexdigest codespace_name

tags = [
  "repo:#{repo}",
  "codespace_name:#{codespace_name_hash}",
  "user:#{user}",
  "hcs_version:#{version}"
]

hcs_metrics_base = "dx.frameworks.hcs"
if server_url == StaffshipURL
  hcs_metrics_base = "dx.frameworks.hcs.staffship"
end

settings = [DX::Telemetry::USER_TAG, DX::Telemetry::SERVER_FEATURES, DX::Telemetry::RESILIENT]
DX::Telemetry.monitor_script_usage("#{hcs_metrics_base}.usage", tags: tags, settings: settings)
