#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require_relative "dx/telemetry/telemetry"

settings = [DX::Telemetry::USER_TAG, DX::Telemetry::SERVER_FEATURES, DX::Telemetry::RESILIENT]
DX::Telemetry.monitor_script_usage("monolith.server.usage", tags: [], settings: settings)
