#!/usr/bin/env ruby
# frozen_string_literal: true
#
# repo-id: Get the database ID and the global ID for a given repository.
#
# Usage: repo-id github/github
#        Database ID: 3
#        Global ID: MDEwOlJlcG9zaXRvcnkz

require_relative "../config/environment"

ARGV.each do |arg|
  repo = arg.split("/")
  if repo.length != 2
    STDERR.puts "error: #{arg} is not a valid nwo"
    next
  end

  repo = Repository.nwo(arg)

  if repo
    puts "Database ID: #{repo.id}"
    puts "Global ID: #{repo.global_relay_id}"
  else
    puts "#{arg} Not Found"
  end
end
