#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
processor = GitHub::StreamProcessors::RegistryMetadata::LayerDownloadedProcessor.new
consumer = GitHub.hydro_consumer(processor.options)

RMSLayerDownloadedProcessorError = Class.new(StandardError)

begin
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
rescue => e
  GitHub.logger.error("failed to run stream processor", { "code.namespace": processor.class.name, exception: e })
  Failbot.report(RMSLayerDownloadedProcessorError.new)
  raise
end
