#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
processor = GitHub::StreamProcessors::RegistryMetadata::VersionDownloadedProcessor.new
consumer = GitHub.hydro_consumer(processor.options)

RMSVersionDownloadedProcessorError = Class.new(StandardError)

begin
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
rescue => e
  if GitHub.flipper[:packages_otel_migration].enabled?
    GitHub.logger.error(e)
  else
    GitHub::Logger.log_exception({ fn: self.class.name, error: "failed to run stream processor" }, e)
  end
  Failbot.report(RMSVersionDownloadedProcessorError.new)
  raise
end
