#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
processor = GitHub::StreamProcessors::RegistryMetadata::RepositoryAccessRemovalProcessor.new
consumer = GitHub.hydro_consumer(processor.options)

RepositoryAccessRemovalProcessorError = Class.new(StandardError)

begin
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
rescue => e
  GitHub::Logger.log_exception({ fn: self.class.name, error: "failed to run stream processor" }, e)
  Failbot.report(RepositoryAccessRemovalProcessorError.new)
  raise
end
