#!/bin/bash
#/ Usage: run-gitrpc-test FILE...
#/
#/ FILE can be relative to the repo root (e.g.
#/ vendor/gitrpc/test/client/ahead_behind_test.rb) or gitrpc's root
#/ (e.g. test/client/ahead_behind_test.rb).
#/
#/ To check for gitrpc methods that can be removed from the allowlist set the `GITRPC_DEPRECATED_PEDANTRY` environment variable.
set -e
set -o nounset

args=()
for f in "$@"; do
  case "$f" in
    -*)
      cat "$0" | grep "^#/" | cut -c4-
      exit 1
      ;;
    vendor/gitrpc/*)
      args+=("$(echo "$f" | cut -d '/' -f 3-)")
      ;;
    *)
      args+=("$f")
      ;;
  esac
done

cd vendor/gitrpc
if [ ! -e bin/testsuite ]; then
  echo Bootstrapping vendor/gitrpc...
  script/bootstrap --local
fi

set -x
exec bin/testsuite "${args[@]}"
