#!/bin/bash
set -e

cat <<MSG >&2
The new command to run JS tests with is:
  $ bin/npm test

If you want to to keep the test runner running so you can connect a real
browser and iterate on tests, use this flag:
  $ bin/npm test -- --no-single-run
MSG
exit 1
