#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "./seeds/app"
require_relative "./dx/telemetry/telemetry"

runner = ARGV[0] || "none"
tags = ["runner:#{runner}"]
settings = [DX::Telemetry::ENVIRONMENT_TAG, DX::Telemetry::SUCCESS_TAG, DX::Telemetry::USER_TAG, DX::Telemetry::RESILIENT]
DX::Telemetry.monitor_script_usage("monolith.seed.usage", tags: tags, settings: settings)
DX::Telemetry.monitor_script_runtime("monolith.seed.duration", tags: tags, settings: settings)

Seeds::App.start
