#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Usage
#
# To run this script, make sure you use the binary:
#
#   script/bootstrap
#   bin/seed-explore-repository
#
# Enjoy!

require_relative "../config/environment"
require "faker"
require_relative Rails.root.join("script/seeds/objects")

unless Rails.env.development? || ENV["STAGING_LAB_ENVIRONMENT"]
  puts "This can only be run in the development or staging environments!"
  exit 1
end

puts "==> Seeding GitHub Explore repository..."

user = User.find_by_login("monalisa")
org = Organization.find_by_login("github")
repo = Repository.find_by_name("explore")
repo ||= Repository.handle_creation(
  user,
  org,
  {
    name: "explore",
    description: Faker::Hipster.sentence
  },
  synchronous: true
).repository

Seeds::Objects::Commit.create(
  repo: repo,
  message: "JavaScript topic",
  committer: user,
  branch_name: "main",
  files: { "topics/javascript/index.md" => <<~EOS,
    ---
    aliases: js
    created_by: Brendan Eich‎
    display_name: JavaScript
    released: 1995
    short_description:  JavaScript (JS) is a lightweight interpreted programming language with first-class functions.
    topic: javascript
    url: https://developer.mozilla.org/en-US/docs/Web/JavaScript
    wikipedia_url: https://en.wikipedia.org/wiki/JavaScript
    ---
    JavaScript (JS) is a lightweight interpreted or JIT-compiled programming language with first-class functions. While it is most well-known as the scripting language for Web pages, many non-browser environments also use it, such as Node.js, Apache CouchDB and Adobe Acrobat. JavaScript is a prototype-based, multi-paradigm, dynamic language, supporting object-oriented, imperative, and declarative (e.g. functional programming) styles.
  EOS
  },
)

Seeds::Objects::Commit.create(
  repo: repo,
  message: "Ruby topic",
  committer: user,
  branch_name: "main",
  files: { "topics/ruby/index.md" => <<~EOS,
    ---
    created_by: Yukihiro Matsumoto
    display_name: Ruby
    github_url: https://github.com/ruby/ruby
    related: rails, language, python
    released: December 21, 1995
    short_description: Ruby is a scripting language designed for simplified object-oriented programming.
    topic: ruby
    url: https://www.ruby-lang.org/en/
    wikipedia_url: https://en.wikipedia.org/wiki/Ruby_(programming_language)
    ---
    Ruby was developed by Yukihiro \"Matz\" Matsumoto in 1995 with the intent of having an easily readable programming language. It is used by the Rails framework to create dynamic web-applications. Ruby's syntax is similar to that of Perl and Python.
  EOS
  },
)

Seeds::Objects::Commit.create(
  repo: repo,
  message: "Rails topic",
  committer: user,
  branch_name: "main",
  files: { "topics/rails/index.md" => <<~EOS,
    ---
    aliases: rails5, rails-application, ruby-on-rails, rails4, rubyonrails, rails-tutorial
    created_by: David Heinemeier Hansson
    display_name: Rails
    github_url: https://github.com/rails
    released: December 13, 2005
    short_description: Ruby on Rails (Rails) is a web application framework written in Ruby
    topic: rails
    url: http://rubyonrails.org/
    wikipedia_url: https://en.wikipedia.org/wiki/Ruby_on_Rails
    ---
    Ruby on Rails (Rails) is a web application framework written in Ruby. It is meant to help simplify the building of complex websites.
  EOS
  },
)
