#!/bin/sh

# Uses script/serviceowners-ls-files to find Ruby test files owned by the given
# service or team and runs them 10 at a time. Useful for running the full suite
# of tests relating to a service or team's code ownership.
#
# Usage: bin/serviceowners-test [options] <qualified service name or team>
# See: script/serviceowners-ls-files

exec bin/serviceowners-ls-files --quiet --glob '{test,packages}/**/*_test.rb' "$@" | xargs --max-args=10 --verbose bin/rails test
