#!/usr/bin/env safe-ruby
# frozen_string_literal: true

require_relative "../config/environment"
require "optparse"
require "github/serviceowners/service_endpoints"

json = false
OptionParser.new do |opts|
  opts.banner = "Usage: service-endpoints [services] [options]"

  opts.on("--json", false, "ouput endpoints as json that can be used when generating datadog SLOs/monitors") do
    json = true
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

$services = ARGV.map(&:to_sym)

endpoints_by_service = GitHub::Serviceowners::ServiceEndpoints.new(json:).build_service_endpoint_mapping(services: $services)
puts "\n----------------------------------------\n"
puts "📄 endpoint ownership summary for #{$services}:\n\n"
if json
  puts endpoints_by_service
else
  pp endpoints_by_service
end
