#!/usr/bin/env ruby
# frozen_string_literal: true
#
#/ Sets the number of discussion timeline items to display before hiding.
#/
#/ Usage: bin/set-discussion-page-size <count>
#/
#/ count - Number of items to display. Must be a positive integer.

# Show usage
if ARGV.size != 1 || ARGV.include?("--help") || ARGV.include?("-h")
  system "grep ^#/ '#{__FILE__}' |cut -c3-"
  exit 0
end
page_size = Integer(ARGV[0])

require_relative "../config/environment"
DiscussionTimelineItemSplitter.items_per_page = page_size
puts "Discussion timeline page size set to #{page_size}."
