#!/bin/bash
# usage: script/setup-itempicker
#
# This script will seed the database and enable necessary feature flags to let you
# see the ItemPicker React component on different pages.
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${ORANGE}Setting up ItemPicker and all necessary services for development...${NC}"
echo -e "${ORANGE}Please make sure that the dev server is running (script/server) before running this setup script ${NC}"

echo -e "${ORANGE}Setup feature flags...${NC}"

#  React feature flags
bin/toggle-feature-flag enable react_sandbox \
  -F projects_classic_creation_enabled \

echo -e "${ORANGE}Running all seeds...${NC}"

# Creates issues with labels
bin/seed issues_load --repo_name=github/hub --label_count=10 --issue_count=10
# Create fake-user users added to the fake-team
bin/create-users fake-user @github.localhost 10 fake-team
# Create 20 milestones
bin/seed milestones --repo_name=github/hub --milestone_count=20
# Create a project, mock users added Employee team, 4 repos with labels, and 1 issues/PRs/milestones
for i in `seq 5`; do bin/seed memex_projects --count=1; done
# Create a classic project
# bin/rails console
# > user = User.find_by(login: "monalisa")
# > project = Project.build(owner: user, creator: user, name: "Some Project")
# > project.save
# Create 4 pulls requests each time
for i in `seq 3`; do bin/seed pull_requests; done

echo -e "${GREEN} Successfully completed all seeding the database!${NC}"

echo -e "${GREEN}🎉 ItemPicker is setup and ready to use 🎉$"
echo -e "------------------------------------"
echo -e "🔗🔗 Links to different features 🔗🔗"
echo -e "For Issues Index, visit http://github.localhost/_react_sandbox/github/hub/issues"
echo -e "For Issues Show, visit http://github.localhost/_react_sandbox/github/hub/issues/1"
echo -e "For Issues Create, visit http://github.localhost/_react_sandbox/github/hub/issues/new"
-e "${NC}"
