#!/bin/bash
set -e

# This script sets up the github/alloy repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/alloy repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-alloy [-b branch] [-d|h] "
   echo "Options:"
   echo "-b     Specify the alloy branch to clone. Defaults to main if not provided."
   echo "-d     Before starting, delete the existing alloy directory in the codespace."
   echo "-h     Print this help message."
   echo
}

# Set the branch as main. If a branch is provided as an argument, it will be set to that when we parse the provided options.
BRANCH=main

# Get the options
while getopts ":b:hd" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      b) # If a branch was provided, re-set the variable
         BRANCH=$OPTARG;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing alloy repo...\n${NC}"
  sudo rm -rf /workspaces/alloy
fi

# Do a clone of alloy to the /workspaces/alloy dir
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning alloy repo at branch $BRANCH...\n${NC}"
git clone https://${GITHUB_TOKEN}@github.com/github/alloy /workspaces/alloy --branch $BRANCH

# Bootstrap alloy
echo -e "\n${GREEN}➡️ Bootstrapping alloy...\n${NC}"
(
   cd /workspaces/alloy
   /workspaces/alloy/script/bootstrap
)

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The alloy repo has been set up! 🎉🎉"
echo -e "${GREEN}To start alloy for github, run the following commands:${NC}"
echo -e ""
echo -e "${ORANGE}cd /workspaces/alloy && npm run dev${NC}"
echo -e ""
echo -e "${GREEN}To start alloy in another Codespaces along side with dotcom, run the following command:${NC}"
echo -e ""
echo -e "${ORANGE}code /workspaces/alloy${NC}"
