#!/usr/bin/env safe-ruby
# frozen_string_literal: true
require_relative "../script/seeds/runners/deployments"
require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

disable_ssr = ARGV.include?("--disable-ssr")

puts "Setting up feature flags..."

#  React feature flags
GitHub.flipper[:deployments_ux_filtering_react].enable


puts "Creating a deployment for the repo github/hub ..."
Seeds::Runner::Deployments.run

puts "Repo deployments React is setup!"
