#!/bin/bash

CBLUE='\033[0;34m'
CNOCOLOR='\033[0m'
BASE_PATH=/workspaces/github

STACK_EDITOR_OPT=false
while test $# -gt 0; do
  case "$1" in
    --help)
      echo "setup-stack-memex-issues-graph: Setup memex and issues-graph dev environments."
      echo
      echo "Usage: script/setup-stack-memex-issues-graph [-e|--editor same|new]"
      echo
      echo "  -e, --editor         Auto-open the cloned repos (in VSCode):"
      echo "                         same: Add the folders to the current workspace (reloads the window)"
      echo "                         new: Open the folders in a new window"
      echo "      --setup-dev      Setup issues-graph development tools:"
      echo "                         When provisioning issues-graph withing a dotcom codespace,"
      echo "                         some of the develoment dependencies may not be pre-built."
      echo "                         This option will run the setup script in issues-graph once"
      echo "                         it's cloned and available in your codespace"
      echo
      exit
      ;;
    -e|--editor)
      STACK_EDITOR_OPT="$2"
      shift
      shift
      ;;
    --setup-dev)
      INNER_ARGS=(--setup-dev)
      shift
      ;;
    *)
      echo "Unknown option '$1'."
      echo
      $(basename $0) --help && exit
  esac
done

clear

echo -e "${CBLUE}>> MEMEX SETUP <<"
echo -e "^^^^^^^^^^^^^^^^^${CNOCOLOR}"
source $BASE_PATH/script/setup-memex -af -w

echo
echo
echo -e "${CBLUE}>> ISSUES-GRAPH SETUP <<"
echo -e "^^^^^^^^^^^^^^^^^^^^^^^^${CNOCOLOR}"

source $BASE_PATH/script/setup-issues-graph "${INNER_ARGS[@]}"

echo
echo "memex and issues-graph are fully set up!"

case $STACK_EDITOR_OPT in
  new)
    code /workspaces/issues-graph
    ;;
  same)
    code --add /workspaces/github /workspaces/issues-graph
    ;;
esac
