#!/bin/bash
set -e

export BINSTALL_VERSION=v1.10.2
binstall_download_dir=$(mktemp -d)
wget https://github.com/cargo-bins/cargo-binstall/releases/download/${BINSTALL_VERSION}/cargo-binstall-x86_64-unknown-linux-musl.tgz -O ${binstall_download_dir}/cargo-binstall-x86_64-unknown-linux-musl.tgz
tar -xzf ${binstall_download_dir}/cargo-binstall-x86_64-unknown-linux-musl.tgz -C ${binstall_download_dir}
mv ${binstall_download_dir}/cargo-binstall ~/.cargo/bin

export PKS_VERSION=v0.2.12

cargo binstall --pkg-url=https://github.com/alexevanczuk/packs/releases/download/${PKS_VERSION}/x86_64-unknown-linux-gnu.tar.gz --pkg-fmt=tgz -y pks

# Run pks to seed the cache
~/.cargo/bin/pks check > /dev/null 2>&1
