#!/usr/bin/env safe-ruby
# frozen_string_literal: true
require_relative "../script/seeds/runners/notifications"
require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end

if ARGV.include?("--help")
  puts "Usage: sets up the required feature flags needed to use the New Notifications Inbox."
  puts "Accepts --help to see this message and also --list-view to create and apply a feature flag"
  puts "that will allow the default user (monalisa) to see active development code."
  puts "Lastly this script will seed a few notifications to get you started."
  exit 1
end

puts "Setting up feature flags..." # in alphabetical order:

GitHub.flipper[:issues_react_notifications].enable
GitHub.flipper[:issues_react_inbox_tabs].enable
GitHub.flipper[:issues_react_notification_new_graghql_field].enable
GitHub.flipper[:notification_inbox].enable
GitHub.flipper[:inbox_grouping_feature].enable

puts "Creating notification_inbox feature preview..."
ff = FlipperFeature.find_by_name("notification_inbox")
Feature.create(public_name: "Notifications inbox", slug: "notification_inbox", flipper_feature: ff, feedback_link: "https://github.com")
monalisa = User.find_by_login("monalisa")
monalisa.enable_feature_preview(:notification_inbox)

if ARGV.include?("--list-view")
  puts "Creating list view feature preview..."
  GitHub.flipper[:notifications_inbox_listview].enable
end

puts "Seeding inbox..."
Seeds::Runner::Notifications.execute

puts "Inbox is setup!"
