#!/bin/bash
set -e

# This script sets up the github/launch repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the E2E testing for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-e2e [-h] "
   echo "Options:"
   echo "-h     Print this help message."
   echo
}

E2E_TESTS_PATH='/workspaces/github/test/e2e'

# Get the options
while getopts ":b:hd" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

# run bootstrap
pushd $E2E_TESTS_PATH
./script/bootstrap
popd


echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! E2E testing has been set up! 🎉🎉"
echo -e "To configure E2E tests in this codespace, run the following command:${NC}"
echo -e ""
echo -e "${ORANGE}cd $E2E_TESTS_PATH ; script/setup${NC}"
echo -e ""
