#!/bin/bash

set -euo pipefail

# setting default values for variables due to set -u
EDITOR=unknown

while [[ $# -gt 0 ]]; do
  case $1 in
    --help)
      echo "setup-codespaces-ui: Setup UI development environment."
      echo
      echo "Usage: script/setup-codespaces-ui [-e|--editor same|new] [-w|--write-env]"
      echo
      echo "  -e, --editor         Auto-open the cloned ui repo (only in VSCode):"
      echo "                         same: Add the folder to the current workspace (reloads the window)"
      echo "                         new: Open the folder in a new window"
      echo
      exit;
     ;;
    -e|--editor)
      EDITOR="$2"
      shift
      shift
      ;;
    *)
      echo "Unknown option '$1'."
      echo
      $(basename $0) --help && exit
  esac
done

mkdir -p /workspaces/ui

if [ -z "$(ls -A /workspaces/ui)" ]; then
  git clone https://github.com/github/ui /workspaces/ui
else
  echo "/workspaces/ui already exists; skipped cloning ui repository"
fi

# Install ui dependencies
npm install --prefix ../ui


case $EDITOR in
  new)
    code /workspaces/ui
    ;;
  same)
    code --add /workspaces/github /workspaces/ui
    ;;
esac

echo
echo
echo "✅ UI is set up!"
echo
echo "From '/workspaces/ui':"
echo "  - Start the ui server: npm run dev"
echo
echo "From '/workspaces/github':"
echo "  - Start the dotcom server: script/server"
