#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
require_relative "../lib/github/transitions/20171218195425_create_git_hub_plans_in_zuora"
require_relative "../lib/github/transitions/20180111171000_create_data_packs_in_zuora"
require_relative "../lib/github/transitions/20180305191435_create_coupons_in_zuora"
require_relative "../lib/github/transitions/20180103164252_add_marketplace_plans_to_zuora"
require_relative "../lib/github/transitions/20181128173010_create_github_actions_product_in_zuora"
require_relative "../lib/github/transitions/20190823181007_create_github_package_registry_product_in_zuora"
require_relative "../lib/github/transitions/20190918090936_create_github_shared_storage_product_in_zuora"
require_relative "../lib/github/transitions/20200526204457_create_github_codespaces_product_in_zuora"
require_relative "../lib/github/transitions/20220329172157_create_copilot_product_in_zuora"
require_relative "../lib/github/transitions/20220818061815_create_copilot_for_business_product_in_zuora"
require_relative "../lib/github/transitions/20221003032841_create_git_hub_advanced_security_in_zuora"
require_relative "../lib/github/transitions/20230313195345_advanced_security_monthly_trial_does_not_bill_on_expiration"

GitHub.zuorest_client.timeout = 60
GitHub.zuorest_client.open_timeout = 60

GitHub::Transitions::CreateGitHubPlansInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateDataPacksInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateCouponsInZuora.new(dry_run: false).perform
GitHub::Transitions::AddMarketplacePlansToZuora.new(dry_run: false).perform
GitHub::Transitions::CreateGithubActionsProductInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateGithubPackageRegistryProductInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateGithubSharedStorageProductInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateGithubCodespacesProductInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateCopilotProductInZuora.new(dry_run: false).perform
GitHub::Transitions::CreateCopilotForBusinessProductInZuora.new(dry_run: false).run
GitHub::Transitions::CreateGitHubAdvancedSecurityInZuora.new(dry_run: false).run
GitHub::Transitions::AdvancedSecurityMonthlyTrialDoesNotBillOnExpiration.new(dry_run: false).run
