#!/bin/bash

set -e

while getopts "b:ph" opt; do
  case $opt in
    b)
      BRANCHNAME="$OPTARG"
      ;;
    p)
      PULL="true"
      ;;
    h)
      echo "Usage: $0:"
      echo "To pull a specific branch use the 'b' flag '$0 -b <branchname>'"
      echo "To pull the latest version of your branch use the 'p' flag '$0 -p'"
      echo "To display this message use the 'h' flag '$0 -h'"
      exit 0
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

if [[ $(uname -n) != "codespaces"* ]]; then
  echo "this script is only available for codespaces"
  exit
fi

if [ ! -d "/workspaces/driftwood" ]; then
  echo "cloning Driftwood"
  cd /workspaces
  git clone https://github.com/github/driftwood.git
  cd driftwood
fi

if [[ -n "$BRANCHNAME" ]]; then
  echo "pulling branch $BRANCHNAME"
  cd /workspaces/driftwood
  git checkout $BRANCHNAME
  git pull
fi

if [[ -n "$PULL" ]]; then
  echo "pulling latest version of your branch"
  cd /workspaces/driftwood
  git pull
fi

echo "Opening Driftwood codespace"
code /workspaces/driftwood

echo "You're all setup!"
echo "To launch your Driftwood enabled instance run 'script/driftwood-enabled-server' in this window"
echo "Then run 'script/codespaces-dev' in your Driftwood codespace once the GitHub server has started."
