#!/bin/bash
# usage: script/setup-listview
#
# This script will seed the database and enable necessary feature flags to let you
# see the ListView React component on different pages.
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

echo -e "${ORANGE}Setting up list-view and all necessary services for development...${NC}"
echo -e "${ORANGE}Please make sure that the dev server is running (script/server) before running this setup script ${NC}"

echo -e "${ORANGE}Running all seeds...${NC}"
script/setup-issues-react
bin/seed deployments
bin/seed pull_requests
bin/seed actions
bin/seed tasklist_blocks --count=5
bin/seed custom_properties
bin/seed issue_types

echo -e "${GREEN} Successfully completed all seeding the database!${NC}"

echo -e "${ORANGE}Enabling feature flags...${NC}"

bin/toggle-feature-flag enable new_pulls_dashboard \
  -F tasklist_block \
  -F issues_tasks_page \
  -F branches_commits_ux_refresh \
  -F issue_types \
  -F rules_history

echo -e "${GREEN} Successfully enabled all required feature flags ${NC}"

echo -e "${GREEN}🎉🎉 All list-view services have been setup 🎉🎉$"
echo -e "------------------------------------"
echo -e "🔗🔗 Links to different features 🔗🔗"
echo -e "For deployments, visit http://github.localhost/github/hub/deployments"
echo -e "For issues, visit http://github.localhost/issues/assigned"
echo -e "For repository issues, visit http://github.localhost/github/public-server/issues"
echo -e "For the pull request dashboard, visit http://github.localhost/pulls"
echo -e "For tasklist view, create a tasklist in an issue. Then, visit <issueURL>/tasks"
echo -e "For repository action runners, visit http://github.localhost/github/hub/actions/runners"
echo -e "For repository commits, visit  http://github.localhost/monalisa/smile/commits"
echo -e "For issue types, visit http://github.localhost/organizations/github/settings/issue-types"
echo -e "For org repositories, visit http://github.localhost/orgs/github/repositories"
echo -e "For repo custom properties, visit http://github.localhost/organizations/custom-properties-org/settings/custom-properties"
echo -e "${NC}"
