#!/usr/bin/env safe-ruby
# frozen_string_literal: true
require_relative "../config/environment"
require Rails.root.join("script/seeds/runners/sub_issue")

# The server must be running for this script to work
unless File.exist?("tmp/pids/ernicorn1.pid")
  fail "This script requires that the dev server is running. Are you sure it's turned on? (bin/server)"
end

# We depend on Issues React, so make sure it's enabled first
if GitHub.flipper[:issues_react].enabled? && GitHub.flipper[:issues_react_v2].enabled?
  puts "Issues React is already enabled, skipping..."
else
  puts "Setting up Issues React..."
  system("script/setup-issues-react")
end

puts "Setting up sub-issues..."

GitHub.flipper[:sub_issues].enable
GitHub.flipper[:nested_list_view_dnd].enable

puts "Creating sub-issues..."
::Seeds::Runner::SubIssue.run

# Running elastomer repair, just to ensure that all Elasticsearch indices are fully up-to-date
puts "Repairing Elastometer indexes..."
Elastomer::App.run ["repair"]

puts "🎉 Sub-issues is setup and ready to use!"
