#!/bin/bash
set -e

# This script sets up the github/classroom repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
  echo "Sets up the github/classroom repository for a github/github codespace."
  echo
  echo "Usage: setup-codespaces-classroom [-b branch] [-d|h] "
  echo "Options:"
  echo "-b     Specify the classroom branch to clone. Defaults to main if not provided."
  echo "-d     Before starting, delete the existing classroom directory in the codespace."
  echo "-h     Print this help message."
  echo
}

# Set the branch as main. If a branch is provided as an argument, it will be set to that when we parse the provided options.
BRANCH=main

# Get the options
while getopts ":b:hd" opt; do
  case $opt in
    h) # display help message
      help
      exit;;
    b) # If a branch was provided, re-set the variable
      BRANCH=$OPTARG;;
    d) # Delete the repository if it exists
      DELETE_REPO=true;;
    :)
    echo "Error: Option -$OPTARG requires an argument."
    exit 1;;
    \?) # Invalid option
      echo "Error: Invalid option -$OPTARG"
      exit 1;;
  esac
done

# If the classroom repo already exists and the delete argument hasn't been specified, echo a warning and exit.
if [[ -d "/workspaces/classroom" && -z "$DELETE_REPO" ]]; then
  echo -e "${RED}The classroom directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
  exit 1
fi

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing classroom repo...\n${NC}"
  rm -rf /workspaces/classroom
fi

echo -e "\n${GREEN}➡️ Cloning classroom repo at branch $BRANCH...\n${NC}"
git clone https://github.com/github/classroom.git /workspaces/classroom --branch $BRANCH

# Set $RAILS_ROOT
source $(dirname $0)/environment.sh

# Ensure rbenv is started when codespace starts

echo "eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> /home/vscode/.profile
echo 'eval "$(rbenv init -)"' >> /home/vscode/.profile

echo "eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> /home/vscode/.zshrc
echo 'eval "$(rbenv init -)"' >> /home/vscode/.zshrc

# Bootstrap classroom dependencies and prepare the DB
echo -e "\n${GREEN}➡️ Setting up classroom...\n${NC}"

( cd /workspaces/classroom ; script/setup )

echo -e ""
echo -e "${GREEN}💵💵 FINISHED! Classroom is ready. 💵💵${NC}"
echo -e ""
echo -e "Start classroom with ${BLUE}/workspaces/classroom/script/server${NC}. Dotcom must be started before."
echo -e ""
echo -e "Next you can ${ORANGE}cd /workspaces/classroom${NC} and do more from there:"
echo -e ""
echo -e "${ORANGE}code .${NC} - Open a new VS Code instance scoped to the classroom repo"

