#!/bin/sh
# usage: source ./script/setup-pink-panda

echo "=> cloning github/pinkpanda"
mkdir -p /workspaces/pinkpanda
git clone https://github.com/github/pinkpanda /workspaces/pinkpanda

echo "
=> make"
cd /workspaces/pinkpanda
make

echo "
=> Pink Panda service is set up!"
