#!/bin/bash
set -e

setup_turboscan() {
  if [ -z "$GH_GH_PAT" ]; then
    echo "You need to set a PAT in GH_GH_PAT! Check out https://thehub.github.com/engineering/development-and-ops/codespaces/dotcom-dependants-development/#setup-a-token-once-done-once-skip-this-for-future-services for more instructions."
    exit;
  fi

  echo -e '\n==== Cloning turboscan into /workspaces/turboscan ===='
  git clone https://username:"$GH_GH_PAT"@github.com/github/turboscan.git /workspaces/turboscan

  # Turboscan pulls Docker containers from ghcr.io. Thus, we need to authenticate with GHCR.
  echo -e '\n==== Authenticating with Docker ===='
  docker login -u username -p "$GH_GH_PAT" ghcr.io

  # Give ourselves access to GitHub's private Go modules (see https://aka.ms/AAdtgc8 for more information).
  echo -e '\n==== Setting Go environment variable GOPRIVATE to "*github.com/github/*" ===='
  go env -w GOPRIVATE='*github.com/github/*'

  echo -e '\n==== Bootstrapping turboscan services ===='
  pushd /workspaces/turboscan
  script/setup
  script/dev-run make clean build
  make bin/parse-sarif
  popd
}

setup_turboscan

echo -e ""
echo -e "🎉🎉 FINISHED! The turboscan repo has been set up at /workspaces/turboscan! 🎉🎉"
echo -e "To start turboscan, see https://github.com/github/turboscan#running-the-project-locally"
