#!/bin/sh
# usage: source ./script/setup-codespaces-alive
#
# 👋 Why, hello there! You probably don't want to be using this script.
# alive is run by default via script/server. This script is meant to be used
# for running the alive service when developing on the alive service itself.
# If you want live updates to work in dotcom in development,
# that will just work (tm) via script/server.

if [ "$(basename -- "$0")" = "setup-codespaces-alive" ]; then
  echo "Don't run $0, source it" >&2
fi

mkdir -p /workspaces/alive

if [ -z "$(ls -A /workspaces/alive)" ]; then
  git clone https://github.com/github/alive /workspaces/alive
fi

. /workspaces/github/script/alive-server-dev-env

echo "alive is setup!"
echo "if you want to run the alive server from source, comment out alive in Procfile, and run ./script/server from dotcom"
echo "run the alive servers with cd /workspaces/alive."
echo "go run cmd/alive-frontend/main.go"
echo "go run cmd/alive-router/main.go"
