#!/bin/sh
# usage: source ./script/setup-timelined-service

echo "=> installing azure-cli"
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

echo "=> cloning github/timelined"
mkdir -p /workspaces/timelined
git clone https://github.com/github/timelined /workspaces/timelined

echo "
=> make"
cd /workspaces/timelined
make

echo "
=> enabling project events feature flag"
cd /workspaces/github
bin/toggle-feature-flag enable project_timeline_events

echo "
What is your Cosmos DB container ID?"
read AZURE_COSMOS_CONTAINER_ID

echo "=> writing to dev.vscode.env"
echo AZURE_COSMOS_CONTAINER_ID="$AZURE_COSMOS_CONTAINER_ID" > /workspaces/timelined/dev.vscode.env

echo "
=> logging into Azure"
/workspaces/timelined/script/az-login

echo "
=> Timelined service is set up!

If you are using the timeline service for the first time, please run
/workspaces/timelined/script/az-create-role-assignment to set up permissions in Azure."
