#!/bin/bash
set -e

# This script sets up the github/copilot-usage-service repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/copilot-usage-service repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-copilot-usage-service [-b branch] [-d|h] "
   echo "Options:"
   echo "-d     Before starting, delete the existing copilot-usage-service directory in the codespace."
   echo "-w     Add the copilot-usage-service repo as a workspace in VS Code."
   echo "-h     Print this help message."
   echo
}

# Get the options
while getopts ":hdw" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
      w) # Add the repository as a workspace in VS Code
         ADD_TO_WORKSPACE=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

# If the copilot-usage-service repo already exists and the delete argument hasn't been specified, echo a warning and exit.
if [[ -d "/workspaces/copilot-usage-service" && -z "$DELETE_REPO" ]]; then
  echo -e "${RED}The copilot-usage-service directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
  exit 1
fi

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing copilot-usage-service repo...\n${NC}"
  rm -rf /workspaces/copilot-usage-service
fi

# Do a shallow clone of copilot-usage-service to the same dir as the github/github repo.
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning copilot-usage-service repo...\n${NC}"
gh repo clone github/copilot-usage-service /workspaces/copilot-usage-service

# Bootstrap copilot-usage-service
echo -e "\n${GREEN}➡️ Bootstrapping copilot-usage-service...\n${NC}"
( cd /workspaces/copilot-usage-service ; script/bootstrap-dotcom-codespaces; )

# Add the copilot-usage-service repo as a workspace in VS Code
if [ "$ADD_TO_WORKSPACE" = true ]; then
   echo -e "\n${GREEN}➡️ Adding copilot-usage-service to VS Code workspace...\n${NC}"
   code --add /workspaces/copilot-usage-service
fi

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The copilot-usage-service repo has been set up! 🎉🎉"
echo -e ""
echo -e "Make sure the generated /workspaces/copilot-usage-service/.env file has all the proper values."
echo -e ""
echo -e "${GREEN}Then, start the copilot-usage-service server by running the following commands:"
echo -e ""
echo -e "${ORANGE}cd /workspaces/copilot-usage-service ; script/server; ${NC}"
echo -e ""
