#!/bin/bash
set -e

# This script sets up the github/licensify repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
  echo "Sets up the github/licensify repository for a github/github codespace."
  echo
  echo "Usage: setup-codespaces-licensify [-b branch] [-d|h] "
  echo "Options:"
  echo "-b     Specify the licensify branch to clone. Defaults to main if not provided."
  echo "-d     Before starting, delete the existing licensify directory in the codespace."
  echo "-h     Print this help message."
  echo
}

# Set the branch as main. If a branch is provided as an argument, it will be set to that when we parse the provided options.
BRANCH=main

# Get the options
while getopts ":b:hd" opt; do
  case $opt in
    h) # display help message
      help
      exit;;
    b) # If a branch was provided, re-set the variable
      BRANCH=$OPTARG;;
    d) # Delete the repository if it exists
      DELETE_REPO=true;;
    :)
    echo "Error: Option -$OPTARG requires an argument."
    exit 1;;
    \?) # Invalid option
      echo "Error: Invalid option -$OPTARG"
      exit 1;;
  esac
done

# If the licensify repo already exists and the delete argument hasn't been specified, echo a warning and exit.
if [[ -d "/workspaces/licensify" && -z "$DELETE_REPO" ]]; then
  echo -e "${RED}The licensify directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
  exit 1
fi

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing licensify repo...\n${NC}"
  rm -rf /workspaces/licensify
fi

echo -e "\n${GREEN}➡️ Cloning licensify repo at branch $BRANCH...\n${NC}"
git clone https://github.com/github/licensify.git /workspaces/licensify --branch $BRANCH

# Install azure-cli if it's not already installed
if ! command -v az &> /dev/null
then
  echo -e "\n${GREEN}➡️ Installing azure-cli...\n${NC}"
  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
fi

# Bootstrap licensify dependencies
echo -e "\n${GREEN}➡️ Setting up licensify...\n${NC}"
( cd /workspaces/licensify ; script/bootstrap )

echo "=> Enabling licensify feature flags"
bin/toggle-feature-flag enable licensify_product_enablements
bin/toggle-feature-flag enable licensing_org_page

echo -e ""
echo -e "${GREEN}💵💵 FINISHED! licensify is now installed. 💵💵${NC}"
echo -e ""
echo -e "Follow the instructions in ${ORANGE}/workspaces/licensify/docs/development.md${NC} to configure & run licensify 🚀"
