#!/bin/bash

set -e

echo "Copying first-party codespace templates from production (gitrpc is required)..."

echo "Blank..."
bin/seed github_repo --nwo github/codespaces-blank --template true
echo "Rails..."
bin/seed github_repo --nwo github/codespaces-rails --template true
echo "React..."
bin/seed github_repo --nwo github/codespaces-react --template true
echo "Jupyter..."
bin/seed github_repo --nwo github/codespaces-jupyter --template true
echo "Express..."
bin/seed github_repo --nwo github/codespaces-express --template true
echo "Next.js..."
bin/seed github_repo --nwo github/codespaces-nextjs --template true
echo "Django..."
bin/seed github_repo --nwo github/codespaces-django --template true
echo "Flask..."
bin/seed github_repo --nwo github/codespaces-flask --template true
echo "Preact..."
bin/seed github_repo --nwo github/codespaces-preact --template true
echo "Copilot..."
bin/seed github_repo --nwo github/copilot-codespaces-demo --template true -t $GITHUB_TOKEN
echo "Dotnet..."
bin/seed github_repo --nwo github/dotnet-codespaces --template true -t $GITHUB_TOKEN

echo "Codespace templates are ready to rock and/or roll!"
