#!/bin/bash
set -e

remove_origin() {
  if git remote | grep -q "origin"; then
    git remote remove origin
  fi
}

mkdir -p /workspaces/actions-org
cd /workspaces/actions-org

if [ ! -d "setup-node" ]; then
  git clone https://github.com/actions/setup-node
fi
if [ ! -d "setup-dotnet" ]; then
  git clone https://github.com/actions/setup-dotnet
fi
if [ ! -d "setup-ruby" ]; then
  git clone https://github.com/ruby/setup-ruby
fi
if [ ! -d "setup-java" ]; then
  git clone https://github.com/actions/setup-java
fi
if [ ! -d "publish-immutable-action" ]; then
  git clone https://github.com/actions/publish-immutable-action
fi

# Remove the remote so we don't make any changes to the original repos
cd setup-node
remove_origin
cd ../setup-dotnet
remove_origin
cd ../setup-ruby
remove_origin
git branch -M main # setup-ruby is the only one still on master, change it to main to be consistent
cd ../setup-java
remove_origin
cd ../publish-immutable-action
remove_origin
cd ..

mkdir -p /workspaces/packsmoke
cd /workspaces/packsmoke

sudo chmod 777 /usr/share/dotnet
if ! command -v brew &> /dev/null; then
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
/bin/bash -c "$(brew install maven)"

if [ ! -f "/workspaces/runners/ruby/3.2.2/x64.complete" ]; then
  ruby-build 3.2.2 /workspaces/runners/ruby/3.2.2/x64
  touch /workspaces/runners/ruby/3.2.2/x64.complete
fi
for i in 0 1 2 3 4 5 6 7; do
  if [ ! -d "/workspaces/runners/r$i/_work/_tool/Ruby" ]; then
    mkdir -p /workspaces/runners/r$i/_work/_tool/Ruby
    ln -s /workspaces/runners/ruby/3.2.2 /workspaces/runners/r$i/_work/_tool/Ruby/3.2.2
  fi
done

if [ ! -d "packages-smoke-tests-publish" ]; then
  git clone https://github.com/github/packages-smoke-tests-publish
fi
if [ ! -d "packages-smoke-tests-install" ]; then
  git clone https://github.com/github/packages-smoke-tests-install
fi
if [ ! -d "test-publish-internal-ts-action" ]; then
  git clone https://github.com/immutable-actions/test-publish-internal-ts-action
fi

cd packages-smoke-tests-publish
remove_origin
cd ../packages-smoke-tests-install
remove_origin
cd ../test-publish-internal-ts-action
remove_origin
