#!/bin/bash
set -e

# This script sets up the github/enterprise-cloud-importer repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/enterprise-cloud-importer repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-enterprise-cloud-importer [-b branch] [-d|h] "
   echo "Options:"
   echo "-b     Specify the enterprise-cloud-importer branch to clone. Defaults to master if not provided."
   echo "-d     Before starting, delete the existing enterprise-cloud-importer directory in the codespace."
   echo "-h     Print this help message."
   echo
}

if [ -z "$GH_GH_PAT" ]; then
  echo "You need to set a PAT in GH_GH_PAT! Check out https://thehub.github.com/engineering/development-and-ops/codespaces/dotcom-dependants-development/#setup-a-token-once-done-once-skip-this-for-future-services for more instructions."
  exit;
fi

# Set the branch as main. If a branch is provided as an argument, it will be set to that when we parse the provided options.
BRANCH=master

# Get the options
while getopts ":b:hd" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      b) # If a branch was provided, re-set the variable
         BRANCH=$OPTARG;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing enterprise-cloud-importer repo...\n${NC}"
  rm -rf /workspaces/enterprise-cloud-importer
fi

# Do a clone of enterprise-cloud-importer to the same dir as the github/github repo.
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning enterprise-cloud-importer repo at branch $BRANCH...\n${NC}"
git clone https://$GH_GH_PAT@github.com/github/enterprise-cloud-importer /workspaces/enterprise-cloud-importer --branch $BRANCH

# Install Node.js 16.x.
# From https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
echo -e "\n${GREEN}➡️ Installing Node.js...\n${NC}"
curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install -y nodejs

# Install dependencies in the enterprise-cloud-importer repo
echo -e "\n${GREEN}➡️ Installing enterprise-cloud-importer package dependencies...\n${NC}"
( cd /workspaces/enterprise-cloud-importer ; script/bootstrap )

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The Enterprise-Cloud-Importer repo has been set up! 🎉🎉"
echo -e "To start the Enterprise-Cloud-Importer service, run the following command:${NC}"
echo -e ""
echo -e "${ORANGE}cd /workspaces/enterprise-cloud-importer ; PORT=9081 npm start"

