#!/bin/bash

set -o pipefail

source $(dirname $0)/environment.sh

if [ -z "$SKIP_RUBY_BUILD" ]; then
  if [ -n "$BOOTSTRAP_LOG" ]; then
    script/build-ruby 2>&1 | tee -a "$BOOTSTRAP_LOG"
  else
    script/build-ruby
  fi
  if [ "$?" != "0" ]; then
    FAILED_COMPONENT="ruby"
  fi

  export PATH=$RAILS_ROOT/vendor/ruby/"$(config/ruby-version)"/bin:$PATH
fi
