#!/bin/sh
# usage: source ./script/setup-tenant-bound-rate-limiting

echo "=> enabling rate limiting and feature flags"

# rate limiting is not enabled by default in dev environments
# primary limiter
export RATE_LIMITING=1
# secondary limiter
# in the Rails development environment, this controls secondary rate limiting
# See: ./lib/github/config/environments/development.rb#L341
export GH_REQUEST_LIMITING=1

# By default there is not a secrect key set locally. There also isn't a local stamp configured
# so we use one that's defined in config/proxima.rb
# Cliensts will need to set this in their environment and use it as the signing key when making requests
# with the X-PSI-JWT header.
export PROXIMA_SERVICE_IDENTITY_SECRET_KEY_STAFF_WUS2_01=abc123

# toggle the feature flags
if ! bin/toggle-feature-flag enable \
  -F proxima_service_rate_limits \
  -F proxima_service_rate_limiting \
  -F proxima_service_rate_limits_primary \
  -F proxima_service_rate_limits_secondary; then
  echo "Error: Failed to enable feature flags"
  exit 1
fi

echo "=> secret key for signing X-PSI-JWT tokens: $PROXIMA_SERVICE_IDENTITY_SECRET_KEY_STAFF_WUS2_01"
echo "=> completed tenant bound rate limiting setup"
echo "=> Run bin/seed proxima_service_identity after the server starts to create rate limit configurations for the avacado_gmbh"
echo "=> starting server in 3 seconds..."
sleep 3

echo "=> calling script/server"
exec script/server "$@"
