#!/bin/bash
set -e

EVENTER_CODE_SRC="/workspaces/eventer"

setup_eventer() {
  if [ -z "$(ls -A $EVENTER_CODE_SRC)" ]; then
    echo -e '\n==== Cloning eventer into /workspaces/eventer ===='
    mkdir "$EVENTER_CODE_SRC"
    git clone https://github.com/github/eventer.git "$EVENTER_CODE_SRC"
  fi

  echo -e '\n==== Bootstrapping eventer services ===='
  pushd /workspaces/eventer
  script/bootstrap
  script/setup

  popd
}

setup_eventer

echo -e ""
echo -e "🎉🎉 FINISHED! The eventer repo has been set up at /workspaces/eventer! 🎉🎉\n"
echo -e "To start eventer services, run:"
echo -e "  cd /workspaces/eventer"
echo -e "  HYDRO_SERVICES=true ./script/server\n"
echo -e "To start github using eventer, unfortunately, we need to run kafka instead of kafka-lite."
echo -e "⚠️  First, comment out 'kafka-lite' in /workspaces/github/Procfile  ⚠️\n"
echo -e "Then run:"
echo -e "  cd /workspaces/github"
echo -e '  EVENTER_HMAC_KEY=1234abcd EVENTER_HOST="http://localhost:8084" HYDRO_KAFKA_BROKERS="localhost:9092" ./script/server'
echo -e "\nSee more notes in the readme: https://github.com/github/eventer"
