#!/bin/bash
set -euo pipefail

# Sets up Dependency Graph Platform and related services

help=false
while (($#)); do
    if [ "$1" = "--help" ]; then
        help=true
    elif [ "$1" = "-h" ]; then
        help=true
    fi
    shift
done

if [ "$help" = true ]; then
    echo "Usage: setup-codespaces-dependency-graph"
    echo "  --help -h  Print this help"
    exit 0
fi

DGP_DIR="/workspaces/dependency-graph-platform"

bootstrap_dependency_graph () {
  echo -e '\n==== Bootstrapping dependency-graph-platform ===='

  (cd "$DGP_DIR" && script/bootstrap)

  echo "done"
}

setup_dependency_graph () {
  if [ -z "$GITHUB_TOKEN" ]; then
    echo "Could not find GITHUB_TOKEN! This may indicate an issue with your codespace setup. Refer to https://thehub.github.com/epd/engineering/products-and-services/codespaces/dotcom-development/ for instructions and troubleshooting."
    exit 1;
  fi

  if [ ! -d "$DGP_DIR" ]; then
    echo -e '\n==== Cloning dependency-graph-platform into $DGP_DIR ===='
    git clone https://github.com/github/dependency-graph-platform.git "$DGP_DIR"
  else
    echo -e "\n==== Updating dependency-graph-platform ===="
    (cd "$DGP_DIR" && git pull)
  fi

  # DG services pull Docker containers from ghcr.io. Thus, we need to authenticate with GHCR.
  echo -e '\n==== Authenticating with Docker ===='
  docker login -u username -p "$GITHUB_TOKEN" ghcr.io

  bootstrap_dependency_graph
}

setup_dependency_graph

echo -e ""
echo -e "🎉🎉 FINISHED! The Dependency Graph repos have been set under /workspaces/! 🎉🎉"
