#!/bin/sh
# usage: source ./script/setup-codespaces-voltron

if [ "$(basename -- "$0")" = "setup-codespaces-voltron" ]; then
  echo "Don't run $0, source it" >&2
fi

mkdir -p /workspaces/voltron

if [ -z "$(ls -A /workspaces/voltron)" ]; then
  git clone https://github.com/github/voltron /workspaces/voltron
fi

echo "voltron is setup!"
echo "if you want to run the voltron server from source, comment out voltron in Procfile, and run ./script/server from dotcom"
echo "run the voltron servers with cd /workspaces/voltron."
echo "/workspaces/voltron/script/server
