#!/usr/bin/env safe-ruby
# frozen_string_literal: true
require_relative "../config/environment"

unless Rails.env.development?
  raise "This is a dev-only script"
end
puts "Deprecated, please use script/setup-issues-react instead"
