#!/bin/bash
set -e

# Make sure all Elasticsearch indexes that we might use in a benchmark are current.
echo "Bootstrapping local Elasticsearch indexes"
bin/elastomer bootstrap

# Install the Elasticsearch benchmarking library (Rally)
echo "Installing Elasticearch benchmarking tools"
sudo apt --quiet update
sudo apt-get --quiet install python3-dev openjdk-11-jdk -y
pip3 install --quiet esrally

echo "Rally setup complete"
