#!/bin/bash
set -e

# This script sets up the github/ospo-policy-service repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/ospo-policy-service repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-ospo-policy-service [-b branch] [-d|h] "
   echo "Options:"
   echo "-d     Before starting, delete the existing ospo-policy-service directory in the codespace."
   echo "-w     Add the ospo-policy-service repo as a workspace in VS Code."
   echo "-h     Print this help message."
   echo
}

# Get the options
while getopts ":hdw" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
      w) # Add the repository as a workspace in VS Code
         ADD_TO_WORKSPACE=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

# If the ospo-policy-service repo already exists and the delete argument hasn't been specified, echo a warning and exit.
if [[ -d "/workspaces/ospo-policy-service" && -z "$DELETE_REPO" ]]; then
  echo -e "${RED}The ospo-policy-service directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
  exit 1
fi

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing ospo-policy-service repo...\n${NC}"
  rm -rf /workspaces/ospo-policy-service
fi

# Do a shallow clone of ospo-policy-service to the same dir as the github/github repo.
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning ospo-policy-service repo...\n${NC}"
git clone https://github.com/github/ospo-policy-service /workspaces/ospo-policy-service

# Bootstrap ospo-policy-service
echo -e "\n${GREEN}➡️ Bootstrapping ospo-policy-service...\n${NC}"
( cd /workspaces/ospo-policy-service ; script/bootstrap )

# Add the ospo-policy-service repo as a workspace in VS Code
if [ "$ADD_TO_WORKSPACE" = true ]; then
   echo -e "\n${GREEN}➡️ Adding ospo-policy-service to VS Code workspace...\n${NC}"
   code --add /workspaces/ospo-policy-service
fi

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The ospo-policy-service repo has been set up! 🎉🎉"
echo -e "To start the ospo-policy-service server in this branch, run the following commands:${NC}"
echo -e ""
echo -e "${ORANGE}cd /workspaces/ospo-policy-service ; script/server"
echo -e ""
