#!/bin/bash
set -e

# This script sets up the github/custom-og-image repository for a github/github codespace.

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print help message
help() {
   echo "Sets up the github/custom-og-image repository for a github/github codespace."
   echo
   echo "Usage: setup-codespaces-custom-og-image [-b branch] [-d|h] "
   echo "Options:"
   echo "-d     Before starting, delete the existing custom-og-image directory in the codespace."
   echo "-w     Add the custom-og-image repo as a workspace in VS Code."
   echo "-h     Print this help message."
   echo
}

# Get the options
while getopts ":hdw" opt; do
   case $opt in
      h) # display help message
         help
         exit;;
      d) # Delete the repository if it exists
         DELETE_REPO=true;;
      w) # Add the repository as a workspace in VS Code
         ADD_TO_WORKSPACE=true;;
     :)
      echo "Error: Option -$OPTARG requires an argument."
      exit 1;;
     \?) # Invalid option
         echo "Error: Invalid option -$OPTARG"
         exit 1;;
   esac
done

# If the custom-og-image repo already exists and the delete argument hasn't been specified, echo a warning and exit.
if [[ -d "/workspaces/custom-og-image" && -z "$DELETE_REPO" ]]; then
  echo -e "${RED}The custom-og-image directory already exists in this codespace.${NC} \nYou can rerun the setup script with the -d argument to force the deletion of the existing repository."
  exit 1
fi

if [ "$DELETE_REPO" = true ]; then
  echo -e "\n${GREEN}➡️ Deleting the existing custom-og-image repo...\n${NC}"
  rm -rf /workspaces/custom-og-image
fi

# Do a shallow clone of custom-og-image to the same dir as the github/github repo.
# If a branch was supplied, use that branch for the clone.
echo -e "\n${GREEN}➡️ Cloning custom-og-image repo...\n${NC}"
git clone https://github.com/github/custom-og-image /workspaces/custom-og-image

# Bootstrap custom-og-image
echo -e "\n${GREEN}➡️ Bootstrapping custom-og-image...\n${NC}"
( cd /workspaces/custom-og-image ; script/bootstrap )

# Add the custom-og-image repo as a workspace in VS Code
if [ "$ADD_TO_WORKSPACE" = true ]; then
   echo -e "\n${GREEN}➡️ Adding custom-og-image to VS Code workspace...\n${NC}"
   code --add /workspaces/custom-og-image
fi

# Seed
CUSTOM_OG_IMAGE_ENV_FILE="/workspaces/custom-og-image/.env"
echo -e "\n${GREEN}➡️ Seeding custom-og-image objects...\n${NC}"
bin/seed og_image_app | tee $CUSTOM_OG_IMAGE_ENV_FILE
echo -e "${ORANGE}Done!${NC}"

echo -e "\n${GREEN}➡️ Updating custom-og-image environment...\n${NC}"
echo -e "PORT=7071\nNODE_TLS_REJECT_UNAUTHORIZED=0\nGITHUB_API_URL=https://api.github.localhost" >> $CUSTOM_OG_IMAGE_ENV_FILE
echo -e "${ORANGE}Done!${NC}"

echo -e ""
echo -e "${GREEN}🎉🎉 FINISHED! The custom-og-image repo has been set up! 🎉🎉"
echo -e "To start the custom-og-image server in this branch, run the following commands:${NC}"
echo -e ""
echo -e "${ORANGE}cd /workspaces/custom-og-image ; script/server${NC}"
echo -e ""
