#!/usr/bin/env ruby
#/ Usage: shard-path <user>/<repo>...
#/ Retreive the host and path location of a repository, gist, or wiki.
require "github"

# show usage
if ARGV.empty? || ARGV.include?("--help")
  exec("grep ^#/ <'#{__FILE__}' | cut -c4-")
end

ARGV.each do |repo|
  begin
    host, path = GitHub::Routing.lookup_route(repo)
    puts "#{host}:#{path}"
  rescue GitHub::Routing::NoSuchRoute
    warn "error: not found: #{repo}"
    exit 1
  end
end
