#!/usr/bin/env ruby
# frozen_string_literal: true
require File.expand_path("../../config/environment", __FILE__)
require_relative "./slack_mock/app"

begin
  slack_integration_url = URI(ReminderSlackWorkspaceConnector.slack_integration.url)
  SlackMock::App.run!(port: slack_integration_url.port)
rescue ArgumentError
  seed_command = "bin/create-seed-internal-integrations"

  if system(seed_command)
    retry
  else
    STDERR.puts "\e[33mSlack integration not yet created. Run #{seed_command}\e[0m"
    exit 1
  end
end
