#!/usr/bin/env bash

srb="$(dirname $0)/../bin/srb"

export SRB_SKIP_GEM_RBIS=1
"$srb" tc 2>&1 | while IFS= read -r line; do
  if [[ "$line" =~ ^([^:]+):([0-9]+):\ (.+)\ (https://srb\.help/([0-9]+))$ ]]; then
    file="${BASH_REMATCH[1]}"
    lineno="${BASH_REMATCH[2]}"
    message="$(echo ${BASH_REMATCH[3]} | sed 's/"/\\"/g')"
    url="${BASH_REMATCH[4]}"
    number="${BASH_REMATCH[5]}"
    fingerprint="$(echo "sorbet|$path:$lineno|$url" | sha256sum | awk '{print $1}')"

    echo "===FAILURE==="
    echo "{"
    echo "  \"suite\": \"Sorbet\","
    echo "  \"name\": \"$number: $message\","
    echo "  \"message\": \"Sorbet help: $url\\nGitHub-specific help: https://aka.ms/github-sorbet\","
    echo "  \"flaky\": false,"
    echo "  \"fingerprint\": \"$fingerprint\","
    echo "  \"location\": \"$file:$lineno\""
    echo "}"
    echo "===END FAILURE==="
    echo
  fi

  echo "$line"
done

exit "${PIPESTATUS[0]}"
