#!/bin/sh

export HTTP_ADDR=127.0.0.1:${SPOKESD_HTTP_PORT:-28081}
export INTERNAL_ADDR=127.0.0.1:${SPOKESD_HTTP_PORT:-28082}
export SPOKESD_MYSQL_DB_NAME=${SPOKESD_MYSQL_DB_NAME:-github_development_spokes}
export SPOKESD_MYSQL_RO_HOST=localhost:3306
export SPOKESD_MYSQL_RO_USER=root
export SPOKESD_MYSQL_RO_PASS=
export SPOKESD_MYSQL_RW_HOST=localhost:3306
export SPOKESD_MYSQL_RW_USER=root
export SPOKESD_MYSQL_RW_PASS=
export SPOKESD_INTERNAL_API_URL=http://api.github.localhost
export SPOKESD_INTERNAL_API_HMAC_KEY=octocat
export SPOKESD_TWIRP_INTERNAL_API_HMAC_KEY=spokesdhmac
export SPOKESD_NO_TLS=true
export SPOKESD_GITRPC_NO_TLS=true
export SPOKESD_GITRPC_USE_DNS=false
export SPOKESD_USE_DNS_FOR_FILESERVERS=false
export SPOKESD_ENV=development
export DATACENTER=default
export REGION=region
export SPOKESD_STORAGE_POLICY=monolith-test
export SPOKESD_GITRPC_DIAL_LOCALHOST=true

export SPOKESD_GITRPCD_dgit1=${SPOKESD_GITRPCD_dgit1:-19418}
export SPOKESD_GITRPCD_dgit2=${SPOKESD_GITRPCD_dgit2:-19419}
export SPOKESD_GITRPCD_dgit3=${SPOKESD_GITRPCD_dgit3:-19420}
export SPOKESD_GITRPCD_dgit4=${SPOKESD_GITRPCD_dgit4:-19421}
export SPOKESD_GITRPCD_dgit5=${SPOKESD_GITRPCD_dgit5:-19422}
export SPOKESD_GITRPCD_GIT_dgit1=${SPOKESD_GITRPCD_GIT_dgit1:-9480}
export SPOKESD_GITRPCD_GIT_dgit2=${SPOKESD_GITRPCD_GIT_dgit2:-9481}
export SPOKESD_GITRPCD_GIT_dgit3=${SPOKESD_GITRPCD_GIT_dgit3:-9482}
export SPOKESD_GITRPCD_GIT_dgit4=${SPOKESD_GITRPCD_GIT_dgit4:-9483}
export SPOKESD_GITRPCD_GIT_dgit5=${SPOKESD_GITRPCD_GIT_dgit5:-9484}
export SPOKESD_GITRPCD_SHARD_PATH_dgit1=${SPOKESD_GITRPCD_SHARD_PATH_dgit1:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit1}
export SPOKESD_GITRPCD_SHARD_PATH_dgit2=${SPOKESD_GITRPCD_SHARD_PATH_dgit2:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit2}
export SPOKESD_GITRPCD_SHARD_PATH_dgit3=${SPOKESD_GITRPCD_SHARD_PATH_dgit3:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit3}
export SPOKESD_GITRPCD_SHARD_PATH_dgit4=${SPOKESD_GITRPCD_SHARD_PATH_dgit4:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit4}
export SPOKESD_GITRPCD_SHARD_PATH_dgit5=${SPOKESD_GITRPCD_SHARD_PATH_dgit5:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit5}

dst="$(echo bin-${GOOS:-$(go env GOOS)}-${GOARCH:-$(go env GOARCH)})"
exec vendor/spokesd/${dst}/spokesctl "$@"
