#!/bin/bash

repo_root="$(git rev-parse --show-toplevel)"
default_db_name="github_development_spokes"
if [ "$(cat ./tmp/runtime/current 2>/dev/null)" = "enterprise" ]; then
  default_db_name="github_enterprise"
fi

export HTTP_ADDR=127.0.0.1:${SPOKESD_HTTP_PORT:-28081}
export INTERNAL_ADDR=127.0.0.1:${SPOKESD_INTERNAL_PORT:-${SPOKESD_HTTP_PORT:-28082}}
export SPOKESD_MYSQL_DB_NAME=${SPOKESD_MYSQL_DB_NAME:-$default_db_name}
export SPOKESD_MYSQL_RO_HOST=localhost:3306
export SPOKESD_MYSQL_RO_USER=root
export SPOKESD_MYSQL_RO_PASS=
export SPOKESD_MYSQL_RW_HOST=localhost:3306
export SPOKESD_MYSQL_RW_USER=root
export SPOKESD_MYSQL_RW_PASS=
export SPOKESD_INTERNAL_API_URL=http://api.github.localhost
export SPOKESD_INTERNAL_API_HMAC_KEY=octocat
export SPOKESD_TWIRP_INTERNAL_API_HMAC_KEY=spokesdhmac
export SPOKESD_NO_TLS=true
export SPOKESD_GITRPC_NO_TLS=true
export SPOKESD_GITRPC_USE_DNS=false
export SPOKESD_USE_DNS_FOR_FILESERVERS=false
export SPOKESD_ENV=development
export DATACENTER=default
export REGION=region
export SPOKESD_STORAGE_POLICY=monolith-test
export SPOKESD_GITRPC_DIAL_LOCALHOST=true

export SPOKESD_GITRPCD_dgit1=${SPOKESD_GITRPCD_dgit1:-19418}
export SPOKESD_GITRPCD_dgit2=${SPOKESD_GITRPCD_dgit2:-19419}
export SPOKESD_GITRPCD_dgit3=${SPOKESD_GITRPCD_dgit3:-19420}
export SPOKESD_GITRPCD_dgit4=${SPOKESD_GITRPCD_dgit4:-19421}
export SPOKESD_GITRPCD_dgit5=${SPOKESD_GITRPCD_dgit5:-19422}
export SPOKESD_GITRPCD_GIT_dgit1=${SPOKESD_GITRPCD_GIT_dgit1:-9480}
export SPOKESD_GITRPCD_GIT_dgit2=${SPOKESD_GITRPCD_GIT_dgit2:-9481}
export SPOKESD_GITRPCD_GIT_dgit3=${SPOKESD_GITRPCD_GIT_dgit3:-9482}
export SPOKESD_GITRPCD_GIT_dgit4=${SPOKESD_GITRPCD_GIT_dgit4:-9483}
export SPOKESD_GITRPCD_GIT_dgit5=${SPOKESD_GITRPCD_GIT_dgit5:-9484}
export SPOKESD_GITRPCD_SHARD_PATH_dgit1=${SPOKESD_GITRPCD_SHARD_PATH_dgit1:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit1}
export SPOKESD_GITRPCD_SHARD_PATH_dgit2=${SPOKESD_GITRPCD_SHARD_PATH_dgit2:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit2}
export SPOKESD_GITRPCD_SHARD_PATH_dgit3=${SPOKESD_GITRPCD_SHARD_PATH_dgit3:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit3}
export SPOKESD_GITRPCD_SHARD_PATH_dgit4=${SPOKESD_GITRPCD_SHARD_PATH_dgit4:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit4}
export SPOKESD_GITRPCD_SHARD_PATH_dgit5=${SPOKESD_GITRPCD_SHARD_PATH_dgit5:-$repo_root/repositories/$(./script/gitrpcd-mode)/dgit5}

logfile=
while [ $# -gt 0 ]; do
  case "$1" in
    --logfile=*)
      logfile="${1#--logfile=}"
      shift
      ;;
    --logfile)
      logfile="$2"
      shift 2
      ;;
    -*)
      printf >&2 "%s: unexpected option: '%s'" "$0" "$1"
      exit 1
      ;;
    *)
      printf >&2 "%s: unexpected argument: '%s'" "$0" "$1"
      exit 1
      ;;
  esac
done

if [ -n "$logfile" ]
then
  exec >"$logfile" 2>&1
fi

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source $SCRIPT_DIR/dx/lib/subproject-containers

dst="$(echo bin-${GOOS:-$(go env GOOS)}-${GOARCH:-$(go env GOARCH)})"

if ([ -z "$LOCAL_SPOKESD" ] || [[ "$LOCAL_SPOKESD" = false ]]) && [[ "$DX_EDGE" = true ]] && [[ "$DX_FEATURE_SUBPROJECT_CONTAINERS" = true ]]; then
  SUBPROJECT_VERSION=$(subproject_version "spokesd")
  echo "spokesd version $SUBPROJECT_VERSION"

  NAME="spokesd-${SPOKESD_HTTP_PORT:-28081}"

  start_subproject --name=$NAME -e HTTP_ADDR=$HTTP_ADDR \
  -e INTERNAL_ADDR=$INTERNAL_ADDR \
  -e SPOKESD_MYSQL_DB_NAME=$SPOKESD_MYSQL_DB_NAME \
  -e SPOKESD_MYSQL_RO_HOST=$SPOKESD_MYSQL_RO_HOST \
  -e SPOKESD_MYSQL_RO_USER=$SPOKESD_MYSQL_RO_USER \
  -e SPOKESD_MYSQL_RO_PASS=$SPOKESD_MYSQL_RO_PASS \
  -e SPOKESD_MYSQL_RW_HOST=$SPOKESD_MYSQL_RW_HOST \
  -e SPOKESD_MYSQL_RW_USER=$SPOKESD_MYSQL_RW_USER \
  -e SPOKESD_MYSQL_RW_PASS=$SPOKESD_MYSQL_RW_PASS \
  -e SPOKESD_INTERNAL_API_URL=$SPOKESD_INTERNAL_API_URL \
  -e SPOKESD_INTERNAL_API_HMAC_KEY=$SPOKESD_INTERNAL_API_HMAC_KEY \
  -e SPOKESD_TWIRP_INTERNAL_API_HMAC_KEY=$SPOKESD_TWIRP_INTERNAL_API_HMAC_KEY \
  -e SPOKESD_NO_TLS=$SPOKESD_NO_TLS \
  -e SPOKESD_GITRPC_NO_TLS=$SPOKESD_GITRPC_NO_TLS \
  -e SPOKESD_GITRPC_USE_DNS=$SPOKESD_GITRPC_USE_DNS \
  -e SPOKESD_USE_DNS_FOR_FILESERVERS=$SPOKESD_USE_DNS_FOR_FILESERVERS \
  -e SPOKESD_ENV=$SPOKESD_ENV \
  -e DATACENTER=$DATACENTER \
  -e REGION=$REGION \
  -e SPOKESD_STORAGE_POLICY=$SPOKESD_STORAGE_POLICY \
  -e SPOKESD_GITRPC_DIAL_LOCALHOST=$SPOKESD_GITRPC_DIAL_LOCALHOST \
  -e SPOKESD_GITRPCD_dgit1=$SPOKESD_GITRPCD_dgit1 \
  -e SPOKESD_GITRPCD_dgit2=$SPOKESD_GITRPCD_dgit2 \
  -e SPOKESD_GITRPCD_dgit3=$SPOKESD_GITRPCD_dgit3 \
  -e SPOKESD_GITRPCD_dgit4=$SPOKESD_GITRPCD_dgit4 \
  -e SPOKESD_GITRPCD_dgit5=$SPOKESD_GITRPCD_dgit5 \
  -e SPOKESD_GITRPCD_GIT_dgit1=$SPOKESD_GITRPCD_GIT_dgit1 \
  -e SPOKESD_GITRPCD_GIT_dgit2=$SPOKESD_GITRPCD_GIT_dgit2 \
  -e SPOKESD_GITRPCD_GIT_dgit3=$SPOKESD_GITRPCD_GIT_dgit3 \
  -e SPOKESD_GITRPCD_GIT_dgit4=$SPOKESD_GITRPCD_GIT_dgit4 \
  -e SPOKESD_GITRPCD_GIT_dgit5=$SPOKESD_GITRPCD_GIT_dgit5 \
  -e SPOKESD_GITRPCD_SHARD_PATH_dgit1=$SPOKESD_GITRPCD_SHARD_PATH_dgit1 \
  -e SPOKESD_GITRPCD_SHARD_PATH_dgit2=$SPOKESD_GITRPCD_SHARD_PATH_dgit2 \
  -e SPOKESD_GITRPCD_SHARD_PATH_dgit3=$SPOKESD_GITRPCD_SHARD_PATH_dgit3 \
  -e SPOKESD_GITRPCD_SHARD_PATH_dgit4=$SPOKESD_GITRPCD_SHARD_PATH_dgit4 \
  -e SPOKESD_GITRPCD_SHARD_PATH_dgit5=$SPOKESD_GITRPCD_SHARD_PATH_dgit5 \
  "ghcr.io/github/spokesd/spokesd:$SUBPROJECT_VERSION"
else
  exec vendor/spokesd/${dst}/spokesd
fi
