#!/usr/bin/env ruby

require File.expand_path("../../config/boot", __FILE__)
require "github/storage"
require "github/config/mysql"

Failbot.disable    # suppress failbot reporting of unhandled exceptions

GitHub.load_activerecord

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} host"
  exit 1
end

def main
  usage unless ARGV.length == 1

  host = ARGV[0]

  if host.nil? || String(host).empty?
    puts "No such route"
    exit 1
  end

  if GitHub::Storage::Online.new(host: host).perform
    puts "#{host} has been put online"
  else
    puts "#{host} could not be put online for an unknown reason"
  end
end

main
