#!/usr/bin/env ruby

require File.expand_path("../../config/boot", __FILE__)
require "github/storage"
require "github/config/mysql"

Failbot.disable

GitHub.load_activerecord

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} <hostname> [--force]"
  exit 1
end

require "action_view"
# don't print deprecation warning
I18n.enforce_available_locales = false

def main
  hostname = ARGV.shift
  usage unless hostname.present?

  force = ARGV.first == "--force"

  GitHub::Storage::Destroyer.destroy_host(hostname, force: force)
end

main
