#!/usr/bin/env ruby

require File.expand_path("../../config/basic", __FILE__)
require "github/storage"

Failbot.disable

GitHub.load_activerecord

include GitHub::Storage::Allocator

def main
  oid = ARGV.first

  unless oid
    puts "Usage: storage-info <oid>"
    exit 10
  end

  hosts = GitHub::Storage::Allocator.hosts_for_oid(oid)

  if hosts.size == 0
    puts "Did not find #{oid[0..5]}... on any hosts"
    exit
  end

  puts "Found #{oid[0..5]}... on the following hosts:"
  hosts.each do |h|
    puts "\t#{h}"
  end
end

main
