#!/usr/bin/env ruby

require File.expand_path("../../config/boot", __FILE__)
require "github/storage"
require "github/config/mysql"

Failbot.disable

GitHub.load_activerecord

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} <host ...>"
  exit 1
end

require "action_view"
# don't print deprecation warning
I18n.enforce_available_locales = false

def main
  require "terminal-table"

  usage if ARGV.empty?

  rows = ARGV.each_with_object([]) do |host, arr|
    remaining_items = GitHub::Storage::Allocator.oids_on_host(host)

    arr << [host, remaining_items.length]
  end

  table = Terminal::Table.new(
    headings: ["Host", "Remaining item(s)"],
    rows: rows,
  )
  puts table
end

main
