#!/usr/bin/env ruby

# This script takes on stdin a list of oids and nodes to which the oid has been
# replicated:
#
# f86a92f0de1ec1906fb0f07a47e412e94469b77c0da063ba45513c8890d08948 host1 host2 host3
# f8d3c82c400117ddce872b0b4a78ef4cb2f322b2f5c49d7711c762faf873634c host2 host4 host1
#
# For each set, it will remove any existing Storage::Replica entries and create
# new entries for the given nodes.

require File.expand_path("../../config/basic", __FILE__)
require "github/config/mysql"
require "github/storage"

GitHub.load_activerecord

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} OID server1 server2 server3 ..."
  exit 1
end

def main
  while line = $stdin.gets
    args = line.split(" ")
    min_replicas = GitHub.storage_replica_count
    usage unless args.length > min_replicas

    oid = args.shift.strip

    GitHub::Storage::Creator.create_replicas_for_oid(oid, args, remove_existing: true)
  end
end

main
