#!/usr/bin/env ruby

require File.expand_path("../../config/boot", __FILE__)
require "github/config/mysql"

Failbot.disable    # suppress failbot reporting of unhandled exceptions

GitHub.load_activerecord

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} object"
  exit 1
end

require "action_view"
include ActionView::Helpers::NumberHelper
# don't print deprecation warning
I18n.enforce_available_locales = false

require "github/storage"

def main
  #usage unless ARGV.length == 1
  require "terminal-table"

  rows = GitHub::Storage::PartitionStats.partition_stats.map do |r|
    r[2] = number_to_human_size(r[2])
    r[3] = number_to_human_size(r[3])
    r
  end

  table = Terminal::Table.new(headings: ["Host", "Partition", "Disk Used", "Disk Free"], rows: rows)

  puts table
end

main
