#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

def usage
  $stderr.puts "Usage:"
  $stderr.puts " #{$0} [--dry-run]"
  exit 1
end

options = {}
ARGV.options do |opts|
  opts.on("-h", "--help") { usage }
  opts.on("--dry-run") { options[:dry_run] = true }
  begin
    opts.parse!
  rescue OptionParser::ParseError => e
    puts e
    usage
  end
end

usage if ARGV.any? { |arg| %w(-h --help).include?(arg) }

require "./config/environment"
Failbot.disable    # suppress failbot reporting of unhandled exceptions
GitHub.load_activerecord

GitHub::Storage::DeleteOrphansCommand.new(
  dry_run: options[:dry_run],
).perform
