#!/usr/bin/env ruby

def usage
  $stderr.puts "Usage:"
  $stderr.puts "  #{$0} type filename"
  exit 1
end

usage unless ARGV.length == 2

type = ARGV[0]
file = ARGV[1]

require File.expand_path("../../config/environment", __FILE__)
Failbot.disable

begin
  object = type.camelize.constantize.find_by_name!(file)
  oid    = object.oid

  if oid
    hosts = GitHub::Storage::Allocator.hosts_for_oid(oid)
    path  = File.join(ENV["ENTERPRISE_STORAGE_DATA_PATH"], oid[0], oid[0...2], oid[2...4], oid)
  end
rescue ActiveRecord::RecordNotFound
  puts "No such file."
  exit 1
end

if object && (!hosts || hosts.empty?)
  puts "No such route."
  exit 1
end

puts hosts.map { |host| "#{host}:#{path}" }
