#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"

if ARGV.include?("--review-lab")
  group_id = "review_lab_stratocaster_timeline_update_#{GitHub.current_ref.parameterize.underscore}"
  subscribe_to = GitHub::StreamProcessors::StratocasterTimelineUpdatesProcessor::REVIEW_LAB_SUBSCRIBE_TO
  filter = ->(message) { message.value[:current_ref] == GitHub.current_ref }
end

GitHub.logger.info(
  "gh.stratocaster.timeline_processor.group.id" => group_id,
  "gh.stratocaster.timeline_processor.subscribe_to" => subscribe_to.to_s,
)

processor = GitHub::StreamProcessors::StratocasterTimelineUpdatesProcessor.new(
  group_id: group_id,
  subscribe_to: subscribe_to,
  filter: filter)

consumer = GitHub.hydro_consumer(processor.options)
GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
