#!/usr/bin/env ruby
#/ Usage: svnbridge [OPTIONS] nwo
#/ View or change svnbridge configuration
#/
#/ Options:
#/  --debug     Enable debug logging for this repository
#/  --no-debug  Stop debug logging
#/  --block     Block SVN access to this repository
#/  --no-block  Stop blocking SVN access

require "optparse"

def main(nwo, commands)
  repository = Repository.with_name_with_owner(nwo)
  commands.each do |cmd|
    cmd.call(repository)
  end
  puts <<INFO
SVN on #{repository}:
  * Blocked?   #{repository.svn_blocked?}
  * Debugging? #{repository.svn_debugging?}
INFO
end

def parse_opts
  nwo = nil
  commands = []
  OptionParser.new do |opts|
    opts.on("--debug")    { commands << lambda { |repo| repo.debug_svn } }
    opts.on("--no-debug") { commands << lambda { |repo| repo.undebug_svn } }
    opts.on("--block")    { commands << lambda { |repo| repo.block_svn } }
    opts.on("--no-block") { commands << lambda { |repo| repo.unblock_svn } }
    opts.on("--help")     { usage; exit }
  end.parse!
  nwo = ARGV.shift
  [nwo, commands]
end

def load_github
  require File.expand_path("../../config/basic", __FILE__)
  require_relative "../config/environment"
end

def usage
  system("grep ^#/ <'#{__FILE__}' | cut -c4-")
end

nwo, commands = parse_opts
if nwo.nil?
  usage
  exit 1
else
  load_github
  main(nwo, commands)
end
