#!/usr/bin/env ruby
# frozen_string_literal: true

$stdout.puts "Loading environment..."
require File.expand_path("../../config/environment", __FILE__)

$stdout.puts "Generating a new tableowners.yaml file"
$stdout.puts "It will overwrite the existing file"
tableowners = GitHub::Serviceowners::Tableowners.new
tableowners.export_to_file
