#!/usr/bin/env ruby
# frozen_string_literal: true
#/ Usage: tear-down-seed-data
#/ Removes seed data created by db/seeds.rb, reverting the
#/ database to a mostly-empty state. Useful for debugging.

require_relative "../config/environment"
require_relative "../lib/github/dgit/sql"

puts "Deleting..."

Organization.find_by(login: "github")&.delete

User.find_by(login: "monalisa")&.delete
User.find_by(login: "supermona")&.delete

UserEmail.find_by(email: "octocat@github.com")&.delete
UserEmail.find_by(email: "super_octocat@github.com")&.delete

Team.find_by(name: "Employees")&.delete

StafftoolsRole.find_by(name: "super-admin")&.delete

puts "Done!"
