#!/usr/bin/env bash

set -e
echo -e Running MULTI_TENANT_ENTERPRISE=1 TEST_ALL_FEATURES=1 TEST_WITH_ALL_EMUS=1 *matrix* for $1

echo -e "Running \"./bin/rails test $1\"\n"

./bin/rails test $1

echo -e "-------------------------\n\n"

./script/test-all-features $1

echo -e "\n\n-------------------------\n\n"

./script/test-multitenant-enterprise $1

echo -e "\n\n-------------------------\n\n"

./script/test-all-features-and-multitenant $1

echo -e "\n\n-------------------------\n\n"

./script/test-all-emus $1
