#!/usr/bin/env ruby
require File.expand_path("../../config/environment", __FILE__)
require File.expand_path("../../lib/github/transitions/20140211175238_set_native_app_public_key_scope.rb", __FILE__)

t = GitHub::Transitions::SetNativeAppPublicKeyScope.new
t.perform
