#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../config/environment"
processor = GitHub::StreamProcessors::Turboghas::SummaryProcessor.new
consumer = GitHub.hydro_consumer(processor.options)

begin
  GitHub.hydro_client.run(processor, consumer: consumer, shutdown_signals: [:INT, :TERM])
rescue => e
  Failbot.report(e)
  raise
end
