#!/bin/bash

set -eou pipefail

clone_only=false
while test $# -ne 0; do
    case "$1" in
    --clone-only)
        clone_only=true
        shift
        ;;
    -*)
        echo "$0: unrecognized option: $1" >&2
        exit 1
        ;;
    *)
        break
        ;;
    esac
done

VERSION_PATTERN='\.r([a-f0-9]+)$'
GEM_PATH="$(bin/bundle show turboscan-client)"

if [[ "${GEM_PATH}" =~ $VERSION_PATTERN ]]; then
  version="${BASH_REMATCH[1]}"

  if [ ! -f config/turboscan-version ] || [ ! -d vendor/turboscan ] || [ "${version}" != "$(cat config/turboscan-version)" ]; then
    echo "${version}" > config/turboscan-version

    script/build-subproject --clone-only turboscan
  fi
else
  echo "${GEM_PATH} does not match ${VERSION_PATTERN}"
  exit 1
fi

if $clone_only; then
  exit 0
fi

(cd vendor/turboscan && go run ./cmd/turbomock)
