#!/usr/bin/env ruby

$stderr.sync = true
require_relative "../config/environment"

if ARGV.empty?
  puts "Usage: two-factor-recovery [login-of-user-to-two-factor-recover]"
  exit(1)
else
  user = User.find_by_login(ARGV[0])
  puts user.two_factor_recovery_code(user.two_factor_recovery_n)
end
