#!/usr/bin/env ruby
#
# uid: get user by uid
# Usage: uid 2
#        defunkt

require File.expand_path("../../config/basic", __FILE__)
require "github/config/mysql"
require "github/sql"

GitHub.load_activerecord

ARGV.each do |arg|
  sql = Arel.sql <<-SQL, id: arg.to_i
    SELECT login
      FROM users
      WHERE id=:id
  SQL
  results = ApplicationRecord::Domain::Users.connection.select_rows(sql)
  puts !results.empty? ? results : "error: could not find user with ID #{arg.to_i}!"
end
