#!/bin/sh
# Usage: unicorn-server [<options>]
# Start unicorn in development mode. When specified, <options> are passed through
# to the unicorn_rails program unmodified.
set -e

# start in RAILS_ROOT
cd $(dirname "$0")/..

# set RAILS_ROOT and RAILS_ENV if they're not already set
: ${RAILS_ROOT:=$(pwd)}
: ${RAILS_ENV:=development}
export RAILS_ROOT RAILS_ENV

# setup the PATH
PATH="$RAILS_ROOT"/script:"$RAILS_ROOT"/bin:"$PATH"

# let the runtime be switchable
export GH_RUNTIME_SWITCHABLE=1

export GRPC_DNS_RESOLVER=native

# if alambic is available, turn on GitHub avatars
if [ -x "vendor/alambic/bin/alambic" ]; then
  export GH_AVATARS=1
fi

# truncate the development.log when starting. this thing gets big quick.
mkdir -p log
cat </dev/null >log/development.log

BINSTUB=unicorn_rails

# start unicorn_rails under the development environment
exec "$RAILS_ROOT/bin/$BINSTUB" -E development -c config/unicorn.rb "$@"
