#! /bin/bash
#/ Usage: update-memex-version
#/        update-memex-version <version>
# This script pulls the latest version of the `@github/memex-frontend` package
# and updates SERVICEOWNERS

set -e

# show usage
if [ "$1" = "--help" ]; then
    grep ^#/ <"$0" |cut -c4-
    exit
fi

# the project root directory
root=$(cd $(dirname "$0")/.. && pwd)
cd "$root"

version="${1:-latest}"

bin/npm i @github/memex-frontend@$version

bin/generate-service-files.rb
