#!/bin/bash
# Ensure that a deploy tarball has valid contents and can be deployed
# https://github.com/github/heaven/blob/master/app/models/deployment/strategy/assets_s3.rb
set -ex

if ! [ -f "$1" ]; then
  echo "Usage: $0 path-to-uncompressed-tarball" 1>&2
  exit 1
fi
tarball=$1

export tmp=$(mktemp -d ./tmp/validate-deploy-tarball.XXXX)
trap "rm -rf $tmp" EXIT

# Validate the manifest
tar tvf $tarball > $tmp/contents
grep "public/stylesheets -> static/stylesheets" $tmp/contents
grep public/static/javascripts/codemirror/mode/meta.js $tmp/contents
grep public/static/images/icons/emoji/dog.png $tmp/contents

# Spot check some schema cache files
ls -l db/schema/mysql1.dump db/schema/repositories.dump db/schema/memex.dump

# Tar seems to select one of these files to create a link each time.
# Ideally we'd create a consistent tarball each time but until we can do that
# just validate the files, not that they're not links.
# grep -E "github-dark.css$" $tmp/contents | \
#   grep -v node_modules | grep -v "link to" | grep hacker
# grep -E "github-light.css$" $tmp/contents | \
#   grep -v node_modules | grep -v "link to" | grep minimal

# Confirm it can be extracted
cd $tmp && tar xf $tarball
