#!/bin/sh
#/ Usage: script/vendor-gitignore
#/ Vendors the current state of the gitignore directory in github/gitignore.

set -e

cd vendor
rm -rf gitignore
git clone --depth=1 https://github.com/github/gitignore.git
