#!/bin/sh
set -e

export VEXI_E2E_ENABLED=1
export FEATURE_FLAG_DATA_URL="http://api.github.localhost:8010/twirp"
export FEATURE_FLAG_DATA_CHECKS_API_HMAC_SHARED_KEY="checks-key-1"

bin/rails console
