#!/usr/bin/env safe-ruby
# frozen_string_literal: true

# VIEWFINDER
#
# Viewfinder is a static analysis tool for Rails views.
# To trace a view, run `bin/viewfinder VIEW_PATH` or `bin/viewfinder MyComponent`

require_relative "./viewfinder"

puts Viewfinder.new.call(ARGV.shift)
