#!/bin/bash

# Ensure vschema directory exists
mkdir -p /workspaces/github/tmp/vtcombo

echo "Starting vtcombo: waiting for MySQL to be ready"
command="mysql --user=root -h '127.0.0.1' -e 'SELECT 1' &>/dev/null"
if ! timeout 10s bash -c "while ! $command; do sleep 1; done"
then
  echo "MySQL is not ready after 10 seconds, aborting"
  exit 1
fi

MYSQL_VERSION=$(mysql --version | awk '{ print $3 }')

exec /workspaces/github/vendor/vitess/bin/vtcombo \
  --logtostderr=true \
  --proto_topo "$(cat /workspaces/github/db/topology)" \
  --schema_dir /workspaces/github/tmp/vtcombo \
  --mysql_server_port 15306 \
  --mysql_server_bind_address 0.0.0.0 \
  --mysql_auth_server_impl none \
  --db_socket /var/run/mysqld/mysqld.sock \
  --db_host localhost \
  --mycnf-file /etc/mysql/mysql.cnf \
  --db_app_user root \
  --db_allprivs_user root \
  --db_appdebug_user root \
  --db_dba_user root \
  --db_repl_user root \
  --dbddl_plugin vttest \
  --health_check_interval 1s \
  --tablet_refresh_interval 1s \
  --queryserver-config-query-timeout 300 \
  --queryserver-config-transaction-timeout 300 \
  --queryserver-config-transaction-cap 10  \
  --queryserver-config-pool-size 10 \
  --queryserver-enable-settings-pool \
  --enforce_strict_trans_tables=false \
  --port 15000 \
  --grpc_port 15001 \
  --tablet_types_to_wait 'PRIMARY' \
  --service_map 'grpc-vtgateservice,grpc-vtctl,grpc-vtctld' \
  --db_charset utf8mb4_unicode_520_ci \
  --vschema_ddl_authorized_users='%' \
  --planner-version=gen4 \
  --mysql_server_version=$MYSQL_VERSION
