#!/bin/sh
# Usage: ngrok [<reserved_tunnel>]
# Starts the ngrok vpn tunnel used to get the Braintree sandbox to interact with
# billing in dev. Ask @github/gitcoin for details.
set -e

reserved="southgate muan tclem eanakashima chrishunt kasima achiu"

if [ $1 ]; then
  subdomain="ghdev-$1"
else
  subdomain="ghdev-1"
fi

ngrok http -subdomain=$subdomain 3000
