#!/bin/bash

# The "next" version of Ruby. Usually this tracks the upcoming version,
# released in December of each year and is bumped each week, but may be the
# previous version for some time after we upgrade.
# This is tested in CI but doesn't run in production.
RUBY_NEXT_SHA="80d457b4b4357d3b6a44abd0ceb67e7657bc657a"

# The current version of Ruby, which we run in production. This may include
# some backports but otherwise should be very stable.
# Currently this is Ruby 3.3.4 with some additional backports
RUBY_SHA="cb756da930f1b259860771af601b7640244f5a2e"

if [ -n "$JANKY_ENV_RUBY_SHA" ]; then
  echo -n "$JANKY_ENV_RUBY_SHA"
elif [ -n "$RUBY_NEXT" ]; then
  echo -n "$RUBY_NEXT_SHA"
else
  echo -n "$RUBY_SHA"
fi
