# Helpers
tap "github/bootstrap"

# Ruby
brew "openssl"
brew "autoconf"
brew "rbenv"
brew "ruby-build"

# Manage
brew "gnupg"
brew "node" # for js tests

# Services
brew "nginx", restart_service: !ENV["BOXEN_HOME"]

# Build Utilities
brew "cmake"
