# frozen_string_literal: true
source "https://rubygems.org"

gem "activemodel", "~> 6.1"
gem "activesupport", "6.1.7.6"
gem "addressable"
gem "argon2"
gem "autoprefixer-rails"
gem "bcrypt"
gem "chronic"
gem "enterprise-crypto", "0.4.22"
gem "erubis"
gem "failbot", "~>2.10.0"
gem "faraday", "~> 2.7.2"
gem "github-ldap",        "1.10.1.7.g5a50c9c"
gem "mail",               "~> 2.7.1"
gem "mysql2", "~> 0.5.4"
gem "net-ldap",           "~> 0.16.0"
gem "net-smtp", require: false
gem "openssl-extensions"
gem "parse-cron",         "~> 0.1.4"
gem "public_suffix"
gem "rack", "2.2.8.1"
gem "rack_csrf"
gem "rack-proxy"
gem "rack-rewrite"
gem "rake"
gem "rubyzip"
gem "rugged", "~> 1.6.0"
gem "sassc", "2.4.0"
gem "sequel", "~> 5.63"
gem "sinatra", "2.2.3"
gem "sinatra-contrib", "2.2.3"
gem "sprockets", "4.1.1"
gem "sprockets-helpers", "1.4.0"
gem "sshkey", "~> 2.0"
gem "tzinfo"
gem "uglifier", "4.2.0"
gem "unicorn", "6.1.0"
gem "octokit", "~> 9.1"

group :development do
  gem "foreman", "0.87.2"
  gem 'licensed'
  gem "pry"
  gem "rb-fsevent"
  gem "rerun"
  gem "rubocop", "~> 1.51.0", require: false
end

group :test do
  gem "capybara"
  gem "hashdiff"
  gem "html-proofer"
  gem "ladle", "~>1.0.1"
  gem "mocha"
  gem "rack-test", "~>2.0.2"
  gem "running_man"
  gem "simplecov"
  gem "test-unit"
  gem "webmock"
end

group :development, :test do
  gem "byebug"
end

gem "warden", "~> 1.2"

# Source internal packages from GPR
source "https://rubygems.pkg.github.com/github" do
  gem "unicornfigure", "0.1.2"
end
