# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::AccountConnection`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::AccountConnection`.

class Api::App::PlatformTypes::AccountConnection < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(T::Array[Api::App::PlatformTypes::AccountEdge])) }
  def edges; end

  sig { returns(T::Boolean) }
  def edges?; end

  sig do
    returns(T.nilable(T::Array[T.any(Api::App::PlatformTypes::User, Api::App::PlatformTypes::Organization, Api::App::PlatformTypes::Enterprise, Api::App::PlatformTypes::Bot, Api::App::PlatformTypes::Mannequin, Api::App::PlatformTypes::ProgrammaticAccessBot)]))
  end
  def nodes; end

  sig { returns(T::Boolean) }
  def nodes?; end

  sig { returns(Api::App::PlatformTypes::PageInfo) }
  def page_info; end

  sig { returns(T::Boolean) }
  def page_info?; end

  sig { returns(Integer) }
  def total_count; end

  sig { returns(T::Boolean) }
  def total_count?; end
end
