# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::AddPullRequestReviewCommentPayload`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::AddPullRequestReviewCommentPayload`.

class Api::App::PlatformTypes::AddPullRequestReviewCommentPayload < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(String)) }
  def client_mutation_id; end

  sig { returns(T::Boolean) }
  def client_mutation_id?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequestReviewComment)) }
  def comment; end

  sig { returns(T::Boolean) }
  def comment?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::PullRequestReviewCommentEdge)) }
  def comment_edge; end

  sig { returns(T::Boolean) }
  def comment_edge?; end
end
