# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::DiscussionPollOption`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::DiscussionPollOption`.

class Api::App::PlatformTypes::DiscussionPollOption < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.any(String, Integer)) }
  def id; end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(String) }
  def option; end

  sig { returns(T::Boolean) }
  def option?; end

  sig { returns(T.nilable(Api::App::PlatformTypes::DiscussionPoll)) }
  def poll; end

  sig { returns(T::Boolean) }
  def poll?; end

  sig { returns(Integer) }
  def total_vote_count; end

  sig { returns(T::Boolean) }
  def total_vote_count?; end

  sig { returns(T::Boolean) }
  def viewer_has_voted; end

  sig { returns(T::Boolean) }
  def viewer_has_voted?; end
end
