# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::FileLine`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::FileLine`.

class Api::App::PlatformTypes::FileLine < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(String) }
  def html; end

  sig { returns(T::Boolean) }
  def html?; end

  sig { returns(GraphQL::Client::Schema::ScalarType) }
  def html_raw; end

  sig { returns(T::Boolean) }
  def html_raw?; end

  sig { returns(Integer) }
  def number; end

  sig { returns(T::Boolean) }
  def number?; end
end
