# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::MilestoneItem`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::MilestoneItem`.

module Api::App::PlatformTypes::MilestoneItem; end
