# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::Minimizable`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::Minimizable`.

class Api::App::PlatformTypes::Minimizable < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T::Boolean) }
  def is_minimized; end

  sig { returns(T::Boolean) }
  def is_minimized?; end

  sig { returns(T.nilable(String)) }
  def minimized_reason; end

  sig { returns(T::Boolean) }
  def minimized_reason?; end

  sig { returns(T::Boolean) }
  def viewer_can_minimize; end

  sig { returns(T::Boolean) }
  def viewer_can_minimize?; end

  sig { returns(T::Boolean) }
  def viewer_can_see_minimize_button; end

  sig { returns(T::Boolean) }
  def viewer_can_see_minimize_button?; end

  sig { returns(T::Boolean) }
  def viewer_can_see_unminimize_button; end

  sig { returns(T::Boolean) }
  def viewer_can_see_unminimize_button?; end
end
