# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::NotificationListWithThreadCount`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::NotificationListWithThreadCount`.

class Api::App::PlatformTypes::NotificationListWithThreadCount < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(Integer) }
  def count; end

  sig { returns(T::Boolean) }
  def count?; end

  sig do
    returns(T.any(Api::App::PlatformTypes::Organization, Api::App::PlatformTypes::Repository, Api::App::PlatformTypes::Team, Api::App::PlatformTypes::User, Api::App::PlatformTypes::Enterprise))
  end
  def list; end

  sig { returns(T::Boolean) }
  def list?; end

  sig { returns(Integer) }
  def unread_count; end

  sig { returns(T::Boolean) }
  def unread_count?; end
end
