# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::OIDCProviderType`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::OIDCProviderType`.

module Api::App::PlatformTypes::OIDCProviderType
  sig { returns(T::Boolean) }
  def aad?; end

  AAD = T.let("AAD", String)
end
