# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::PullRequestReviewStateFilter`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::PullRequestReviewStateFilter`.

module Api::App::PlatformTypes::PullRequestReviewStateFilter
  sig { returns(T::Boolean) }
  def approved?; end

  sig { returns(T::Boolean) }
  def changes_requested?; end

  sig { returns(T::Boolean) }
  def none?; end

  sig { returns(T::Boolean) }
  def required?; end

  APPROVED = T.let("APPROVED", String)
  CHANGES_REQUESTED = T.let("CHANGES_REQUESTED", String)
  NONE = T.let("NONE", String)
  REQUIRED = T.let("REQUIRED", String)
end
