# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::RepositoryDiscussionCommentAuthor`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::RepositoryDiscussionCommentAuthor`.

class Api::App::PlatformTypes::RepositoryDiscussionCommentAuthor < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(Api::App::PlatformTypes::DiscussionCommentConnection) }
  def repository_discussion_comments; end

  sig { returns(T::Boolean) }
  def repository_discussion_comments?; end
end
