# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::App::PlatformTypes::UnmarkIssueAsDuplicatePayload`.
# Please instead update this file by running `bin/tapioca dsl Api::App::PlatformTypes::UnmarkIssueAsDuplicatePayload`.

class Api::App::PlatformTypes::UnmarkIssueAsDuplicatePayload < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(String)) }
  def client_mutation_id; end

  sig { returns(T::Boolean) }
  def client_mutation_id?; end

  sig { returns(T.nilable(T.any(Api::App::PlatformTypes::Issue, Api::App::PlatformTypes::PullRequest))) }
  def duplicate; end

  sig { returns(T::Boolean) }
  def duplicate?; end
end
