#!/bin/bash

#!/bin/sh
#/ Usage: toggle-feature-flags enable
#/        toggle-feature-flags disable
#/
#/ Toggle the feature flags required for Multi-Tenant development

set -e

print_usage() {
    grep ^#/ <"$0" | cut -c4-
}

# show usage message
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    print_usage
    exit 2
fi

if [ "$1" != "enable" ] && [ "$1" != "disable" ]; then
    echo "ERROR: unknown option \"$1\""
    print_usage
    exit 1
fi

echo -e "==== $1 feature flags for Multi-Tenant ===="

bin/toggle-feature-flag $1 \
    block_suffixed_request_params \
    -F block_suffixed_response_payloads \
    -F tenant_namespacing \
    -F check_for_multi_tenant_in_tenant_namespacing \
    -F owner_scoped_github_apps

