// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
/* eslint eslint-comments/no-use: off */
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

declare namespace SubIssuesListViewModuleCssNamespace {
  export interface ISubIssuesListViewModuleCss {
    container: string
  }
}

declare const SubIssuesListViewModuleCssModule: SubIssuesListViewModuleCssNamespace.ISubIssuesListViewModuleCss

export = SubIssuesListViewModuleCssModule
