#!/usr/bin/env bash
set -euo pipefail

romount(){
  path=$1

  mount --rbind "$path" "$path"
  mount --make-rprivate "$path"
  mount -o remount,ro,bind "$path"
}

if [ -z "${UNSHARED_MOUNT_NS:-}" ] ; then
  export UNSHARED_MOUNT_NS=1
  exec unshare --propagation shared -m -- "$0" "$@"
fi

romount /etc/ssh/sshd_config
# romount /etc/passwd
# romount /etc/group

if [ ! -e /data/user/waagent.unrestricted ] ; then
  romount /data
fi

exec /usr/sbin/waagent "$@"
