# frozen_string_literal: true

[$stdout, $stderr, $stdin].each { |fd| fd.sync = true }
require File.expand_path("../config/application", __FILE__)
require "gettext_i18n_rails/tasks"

require "rake"
GitHub::Application.load_tasks

task :default do
  puts "The full test suite runs on CI but takes many hours to run on a dev machine."
  puts "You *could* run `bin/rake test` but you probably don't want to!"
  puts "Read more: https://thehub.github.com/engineering/products-and-services/dotcom/testing/"
end
