# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Proto::SecretScanning::Api::V2::PanicResponse`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Proto::SecretScanning::Api::V2::PanicResponse`.

class GitHub::Proto::SecretScanning::Api::V2::PanicResponse
  sig { params(response: T.nilable(String)).void }
  def initialize(response: nil); end

  sig { void }
  def clear_response; end

  sig { returns(String) }
  def response; end

  sig { params(value: String).void }
  def response=(value); end
end
