# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Copilotapi::Chat::V1::GetRepositoryResponse`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Copilotapi::Chat::V1::GetRepositoryResponse`.

class MonolithTwirp::Copilotapi::Chat::V1::GetRepositoryResponse
  sig { params(repository: T.nilable(MonolithTwirp::Copilotapi::Chat::V1::Repository)).void }
  def initialize(repository: nil); end

  sig { void }
  def clear_repository; end

  sig { returns(T.nilable(MonolithTwirp::Copilotapi::Chat::V1::Repository)) }
  def repository; end

  sig { params(value: T.nilable(MonolithTwirp::Copilotapi::Chat::V1::Repository)).void }
  def repository=(value); end
end
