# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Copilotapi::Chat::V1::GetReleaseResponse`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Copilotapi::Chat::V1::GetReleaseResponse`.

class MonolithTwirp::Copilotapi::Chat::V1::GetReleaseResponse
  sig { params(release: T.nilable(MonolithTwirp::Copilotapi::Chat::V1::Release)).void }
  def initialize(release: nil); end

  sig { void }
  def clear_release; end

  sig { returns(T.nilable(MonolithTwirp::Copilotapi::Chat::V1::Release)) }
  def release; end

  sig { params(value: T.nilable(MonolithTwirp::Copilotapi::Chat::V1::Release)).void }
  def release=(value); end
end
