# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MonolithTwirp::Copilotapi::Chat::V1::GetPullRequestCommitsResponse`.
# Please instead update this file by running `bin/tapioca dsl MonolithTwirp::Copilotapi::Chat::V1::GetPullRequestCommitsResponse`.

class MonolithTwirp::Copilotapi::Chat::V1::GetPullRequestCommitsResponse
  sig do
    params(
      commits: T.nilable(T.any(Google::Protobuf::RepeatedField[MonolithTwirp::Copilotapi::Chat::V1::Commit], T::Array[MonolithTwirp::Copilotapi::Chat::V1::Commit]))
    ).void
  end
  def initialize(commits: T.unsafe(nil)); end

  sig { void }
  def clear_commits; end

  sig { returns(Google::Protobuf::RepeatedField[MonolithTwirp::Copilotapi::Chat::V1::Commit]) }
  def commits; end

  sig { params(value: Google::Protobuf::RepeatedField[MonolithTwirp::Copilotapi::Chat::V1::Commit]).void }
  def commits=(value); end
end
