#!/bin/bash

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Not enough args" >&2
  exit 1
fi

service_name="$1"

CONSUL_HTTP_TOKEN="$(ghe-config secrets.consul.acl-master-token)"
export CONSUL_HTTP_TOKEN

local_node_id=$(consul-cli agent self | jq -r .Config.NodeID)

#shellcheck disable=SC2016
jq_expr='.[] | select(.Node.ID == $nodeid).Checks | map(select(.ServiceName == $service)) | length > 0'

while true; do
  if consul-cli health service "$service_name" | jq --arg service "$service_name" --arg nodeid "$local_node_id" -e "$jq_expr" >/dev/null; then
    break
  fi

  sleep 0.25
done
