#!/bin/bash
#/ Usage: ghe-cluster-status-memcache [-hjnv]
#/
#/ Check the status of the Memcache service in the cluster.
#/
#/ OPTIONS:
#/   -h | --help      Show this message.
#/   -j | --json      JSON formatted output.
#/   -n | --nagios    Nagios formatted output and exit codes.
#/   -v | --verbose   Show verbose output.
#/
set -e

# Show usage.
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' < "$0" | cut -c 4-
  exit 2
fi

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-cluster-status-common
source /usr/local/share/enterprise/ghe-cluster-status-common

start_output "memcache"

for hostname in $(ghe-cluster-nodes -r memcache); do
  if echo stats | nc.openbsd -w 2 "$hostname" 11211 >/dev/null 2>&1; then
    check_result "$hostname" "memcached" "ok"
  else
    check_result "$hostname" "memcached" "error" "No response from memcached"
  fi
done

end_output "memcache"
