#!/bin/bash
#/ Usage: ghe-es-setup <cluster_dc>
#/
#/ Wrapper script for running the Elasticsearch setup process.
#/ This is called in phase 2 (migration phase) of the config apply run and is
#/ guarded to ensure it only runs on the MySQL master (cluster delegate) node.
set -e

cluster_dc=$1
# Note that it doesn't matter if $cluster_dc is not set — in that case calling
# es:enterprise:setup[""] is equivalent to calling es:enterprise:setup
/usr/local/bin/github-env bin/rake --trace es:enterprise:setup["$cluster_dc"]
