#!/bin/sh
#/ Usage: ghe-clean-tmp

set -e

# Show usage.
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' <"$0" | cut -c 4-
  exit 2
fi

# Clean up files in /data/user/tmp/ created over 7 days ago
find /data/user/tmp/* -name '*' -ctime +7 -delete

# Clean up files in /var/lib/ghe-updates/ created over 7 days ago
find /var/lib/ghe-updates/ -name '*.tmp' -ctime +7 -delete

# Clean up accumulated .backup files from log path daily
find /var/log/ -name '*.backup' -ctime +1 -delete
