#!/bin/bash
#
#/ There is no need to call this script directly. 
#/ It is normally called by `ghe-maintenance` when setting a customized support message.
#/

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo "Run this script as the root user." >&2
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help)
      usage
      exit 2
      ;;
    -s|--set)
      shift 1
      set +x
      echo "$1" > /data/user/common/maintenance_mode_message.txt
      github-env bin/maintenance
      echo "set maintenance mode message: $1 " 
      ;;
    -q|--query)
      cat /data/user/common/maintenance_mode_message.txt
      ;;
    --)
      shift
      break
      ;;
  esac
  shift
done
