#!/bin/bash
#/ Usage: ghe-repl-stop-redis
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib
ensure_replica

ghe-redis-cli --local slaveof no one | grep -q OK
ghe-redis-cli --local config rewrite | grep -q OK
