#!/bin/bash
#/ Usage: ghe-service-ensure-elasticsearch
set -e

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' < "$0" | cut -c4-
  exit 2
fi

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo Run this script as the root user. >&2
  exit 1
}

. /usr/local/share/enterprise/ghe-systemd-lib.sh

if ! service_enabled elasticsearch; then
  /usr/local/share/enterprise/ghe-nomad-local-alloc-stop elasticsearch
  exit 0
fi

/usr/local/share/enterprise/ghe-nomad-jobs queue /etc/nomad-jobs/elasticsearch/elasticsearch.hcl
