#!/bin/bash
#/ Usage: ghe-orchestrator-post-failover <new_primary>
#/
#/ Called by Orchestrator's PostFailoverProcesses, defined in `lib/configapply/orchestrator.rb`.
#/
set -e

usage () {
  grep '^#/' < "$0" | cut -c4-
}

if [ -z "$1" ]; then
  usage
  exit 1
fi

ghe-cluster-each -- "ghe-config cluster.mysql-master \"$1\"" || true
ghe-cluster-each -- "/usr/local/share/enterprise/ghe-call-configrb dump_exportable_methods | sudo sponge /etc/github/configapply.json" || true
