#!/bin/bash
#/ Usage: ghe-repl-fingerprint
set -e

cat /etc/github/repl-fingerprint 2>/dev/null || {
  openssl rand -hex 10 2>/dev/null | sudo dd of=/etc/github/repl-fingerprint 2>/dev/null
  cat /etc/github/repl-fingerprint
}
