#!/bin/bash
#/ Usage:
#/    ghe-repl-start-consul # Start Consul replication
#/ Start consul replication on a configured replica.
set -e

export PATH="$PATH:/usr/local/share/enterprise"

. ghe-repl-lib
. ghe-repl-consul
ensure_replica

if ! systemctl is-active consul-replicate >/dev/null ; then
  if ! sudo systemctl start consul-replicate >/dev/null ; then
    echo "consul-replicate is not starting"
    exit 1
  fi
fi

for ((n=0; n<30; n++)); do
  if check_consul_replication; then
    break
  fi
  if [ "$n" == 29 ] ; then
    echo "Checking consul replication failed"
    exit check_consul_replication
  fi
  sleep 1
done
