#!/bin/bash
#
#
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib
ensure_replica

status=$(query "SHOW SLAVE STATUS\G")
if [[ -z "${status}" ]]; then
  echo "This node is not set up as a replica" 1>&2
  exit 1
fi

query "STOP SLAVE"
