#!/bin/bash
#/ Usage: ghe-service-ensure-mysql
set -e

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-mysql-lib
. /usr/local/share/enterprise/ghe-mysql-lib

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' < "$0" | cut -c4-
  exit 2
fi

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo Run this script as the root user. >&2
  exit 1
}

. /usr/local/share/enterprise/ghe-systemd-lib.sh

if ! /usr/local/share/enterprise/ghe-call-configrb mysql_enabled?; then
  stop_mysql
  exit 0
fi

if ! check_mysql; then
  start_mysql
fi