#!/bin/bash
#/ Usage: ghe-actions-enable [-h]
#/
#/ Enables GitHub Actions and sets the app.actions.enabled key and blob storage configuration.
#/
#/ OPTIONS:
#/   -h | --help              Show this message
#/
set -e

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-actions-lib
. /usr/local/share/enterprise/ghe-actions-lib

usage() {
    grep '^#/' <"$0" | cut -c 4-
    exit 2
}

while [ "${1:-none}" != "none" ]; do
    case $1 in
    -h | --help)
        usage
        ;;
    *) usage ;;
    esac
done

prompt() {
    read -r -p "$1 [y/N] "

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
}

prompt "Proceed with enabling GitHub Actions?"

echo -e "\nEnabling Github Actions..."

# Configure and test blob storage connection
/usr/local/share/enterprise/ghe-blob-storage-config

# Set app.actions.enabled to true once storage checks are successful
ghe-config app.actions.enabled true

echo -e "\nActions has been enabled. Run 'ghe-config-apply' to finish enabling Actions."

exit 0
