#!/bin/bash

SIZE_X=$(tput cols)

exec journalctl -n${1:-5} --output=json -f _EXE=/lib/systemd/systemd + _TRANSPORT=kernel | while read LINE ; do
  eval $(echo "$LINE" | jq -r '@sh "timestamp=\(.__REALTIME_TIMESTAMP)\nmessage=\(.MESSAGE)\nmessage_source=\(.UNIT // ._SYSTEMD_UNIT // .SYSLOG_IDENTIFIER)\npriority=\(.PRIORITY)"')

  timestamp=$(date +'%H:%M:%S' --date="@${timestamp:0:${#timestamp}-6}")
  message_source=$(echo "$message_source" | sed -e 's/\.service$//')

  if [ "$priority" -le "3" ] 2>/dev/null ; then
    message_color=$(tput sgr0)$(tput setaf 1)
  elif [ "$priority" -le "4" ] 2>/dev/null ; then
    message_color=$(tput sgr0)$(tput bold)$(tput setaf 3)
  else
    message_color=$(tput sgr0)
  fi

  echo -en "\n$(tput rev)$timestamp$(tput sgr0)$(tput bold) $message_source:$message_color ${message:0:$SIZE_X - ${#timestamp} - ${#message_source} - 3}$(tput sgr0)"
done
