#!/bin/bash

/usr/local/share/enterprise/github-mysql $(cat <<EOF
  SELECT SUM(table_rows) AS numrows, table_name
  FROM information_schema.tables
  WHERE table_schema='github_enterprise'
  GROUP BY table_name
  ORDER BY numrows DESC, table_name
EOF
)
