#!/bin/bash
#/ Usage: ghe-nomad-signal [options] <job> <signal>
#/
#/ This script allows to send signals to all running nomad allocations for a given job.
#/ By default the signal is sent to all allocations in the local Nomad cluster.
#/
#/ OPTIONS:
#/   -h | --help                       Show this message.
#/   -v | --verbose                    Enable verbosity.
#/   -n <node> | --node <node>         Only send signal to allocations on <node>.
#/   -l | --local                      Only send signal to allocations on the local node.
#/
set -e

usage() {
  grep '^#/' <"$0" | cut -c 4-
}

echo_verbose() {
  if [[ -n "$verbose" ]]; then
    echo "$@"
  fi
}

verbose=
node=
local=

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 2
      ;;
    -v|--verbose)
      verbose=true
      shift
      ;;
    -n|--node)
      node=$2
      shift 2
      ;;
    -l|--local)
      local=true
      shift
      ;;
    -*)
      echo "Error: unexpected flag ${1%%=*}" 1>&2
      usage 1>&2
      exit 1
      ;;
    *)
      break;
      ;;
  esac
done

job=$1
signal=$2

if [[ -z "$job" ]]; then
  echo "Error: Job must be present." 1>&2
  usage 1>&2
  exit 1
fi

if [[ -z "$signal" ]]; then
  echo "Error: Signal must be present." 1>&2
  usage 1>&2
  exit 1
fi

if [[ -n "$local" ]]; then
  ## For local allocation we will not search by node name since its node name might not be updated if job is not reloaded
  allocation_ids=$(nomad node status -self -allocs | grep "$job" | grep running | awk '{ print $1}')
else
  if [[ -n "$node" ]]; then
    node_select="| select(.NodeName == \"$node\")"
  fi

  allocations=$(ghe-nomad-api "job/$job/allocations")
  allocation_ids=$(echo "$allocations" |
    jq -r "
    [.[]
    $node_select
    | select(.JobID == \"$job\")
    | select(.TaskStates[\"$job\"].State == \"running\")
    | .ID]
    | join(\" \")" )
fi

if [[ -z "$allocation_ids" ]]; then
  echo -n "Failed to find running allocations for ${job}" 1>&2
  if [[ -n "$node" ]]; then
    echo -n " on ${node}" 1>&2
  fi
  echo "." 1>&2

  exit 1
fi

for allocation_id in $allocation_ids; do
  echo_verbose -n "Sending ${signal} to ${allocation_id} for ${job}"
  if [[ -n "$node" ]]; then
    echo_verbose -n " on ${node}"
  fi
  echo_verbose "."

  nomad alloc signal -s "$signal" "$allocation_id"
done
