#!/bin/bash
set -e

# set oom_score_adj to avoid mysql get oom killer
# oom_score_adj = -1000 -- never be killed

oom_score_adj=-1000

# auto exit due to "set -e" if mysqld is not found
pid=$(pgrep mysqld)

if [[ "$(cat "/proc/$pid/oom_score_adj")" != "$oom_score_adj" ]]; then
  echo -1000 > "/proc/$pid/oom_score_adj"
fi
