#!/bin/bash
# Stop mysql replication
#
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

# If the appliance is standalone, exit early before doing replica checks
if "repl_role" = standalone; then
  # Check status once with no retry to be sure there is no replica configuration lingering in MySQL
	status=$(sudo mysql -u root -e "SHOW SLAVE STATUS\G")
  if [ -z "${status}" ]; then
    exit 0
  fi
fi

status=$(query "SHOW SLAVE STATUS\G")
if [ -z "${status}" ]; then
  exit 0
fi

query "STOP SLAVE"
query "RESET SLAVE ALL"
query "SET GLOBAL read_only = 0"

OLD_MYSQL_SEED_DIR="/data/user/mysql"
MYSQL_SEED_DIR="/data/user/common/mysql"
sudo find $OLD_MYSQL_SEED_DIR -maxdepth 1 -name database_seed_* -delete
if [ -d $MYSQL_SEED_DIR ]; then
  sudo find $MYSQL_SEED_DIR -maxdepth 1 -name database_seed_* -delete
fi
