#!/bin/bash

if [ -d /data/user/common ]; then
  sudo setfacl -m u:fluent-bit:rwx,d:u:fluent-bit:rw /data/user/common
  if [ -f /data/user/common/ghe-config.log ] ; then
    sudo chmod 664 /data/user/common/ghe-config.log
  fi
fi

# setup directories
sudo mkdir -p /data/user/config-apply/logs /data/user/config-apply/events
sudo chown fluent-bit:fluent-bit /data/user/config-apply/logs /data/user/config-apply/events 

# setup centralized-directories
sudo mkdir -p /data/user/config-apply/centralized-logs /data/user/config-apply/centralized-events
sudo chown fluent-bit:fluent-bit /data/user/config-apply/centralized-logs /data/user/config-apply/centralized-events 
