#!/bin/bash
#/ Usage: ghe-repl-status-consul [-v] [--check]
#/ Indicate whether `consul-replicate` is successfully replicating data between Consul datacenters
#/ In --check mode, act like a nagios check.
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib
. ghe-repl-consul

if [ "$1" = "-v" ]; then
  systemctl status consul-replicate.service | grep Active | sed -e 's/^[[:space:]]*//'
  exit 0
elif [ $# -eq 0 ]; then
  systemctl status consul-replicate.service | grep Active | sed -e 's/^[[:space:]]*//'
  exit 0
fi

check_consul_replication || {
  exit 1
}

echo "OK: consul replication is in sync"
exit 0
