#!/bin/bash
#/ Usage: ghe-cancel-scheduled-maintenance
#/
#/ Cancel upcoming maintenance mode by removing `ghe-cluster-maintenance
#/ -s` from the enterprise-manage user's crontab.  There is no need to call
#/ this script directly.  It is normally called from `ghe-maintenance -u`.
#/

PATH=/bin:/usr/bin
case "$USER" in
	enterprise-manage)
		crontab -l 2>/dev/null | grep -v 'ghe.*maintenance -s' | crontab -
		;;
	*)
		echo "This script must be run as the enterprise-manage user."
		echo "Try this:"
		echo "  sudo -u enterprise-manage $0"
		exit 1
		;;
esac
