#!/bin/bash
#
# Create a tmp directory in user storage to store transient data.
#
# The tmp directory contents are deleted everytime the user storage
# is mounted or ghe-cleanup-caches is run.
set -e

[ "$(whoami)" = "root" ] || {
    exec sudo -u root "$0" "$@"
    echo Run this script as the root user. >&2
    exit 1
}

dir=/data/user/tmp
  
if ! mountpoint -q /data/user; then
  echo "WARN: /data/user filesystem not mounted, ignoring." >&2
  exit
fi

if [ -d $dir ]; then
  find $dir -mindepth 1 -mmin +60 -print0 | xargs -r -0 rm -rf
else
  mkdir -p $dir
fi

chmod 1777 $dir
