#!/bin/bash
set -e

hostname=$1
port=$2
shift; shift
query=$(printf "%q" "$@")

github-env eval "echo $query | MYSQL_PWD=\$ENTERPRISE_MYSQL_PASSWORD mysql --protocol tcp --user=\$ENTERPRISE_MYSQL_USERNAME --host=$hostname --port=$port"
