#!/bin/bash
#/ Usage: ghe-repl-status-git-hooks [-v] [--check]
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

! is_cache_replica || exit 0

ensure_replica
REPLICA_LAST_SYNC=$(sudo cat /data/user/git-hooks/.last_git-hooks_sync || echo 0)
PRIMARY_LAST_SYNC=$(primary_ssh "sudo -u git flock -s -w 60 /var/run/lock/ghe-repl-git-hooks.lock -c 'cat /data/user/git-hooks/.last_git-hooks_sync'" || echo "")
REPL_STATUS_TYPE="git-hooks"
report_legacy_status "$@"
