#!/bin/bash
#
# Shows the replicas that are connected. exits 1 if no replicas are found.

set -e

slave_hosts () {
  sudo mysql -u root -e "SHOW SLAVE HOSTS"
}

replicas=$(slave_hosts)

if [[ -z $replicas ]]; then
  echo "No replicas found"
  exit 1
else
  echo "${replicas}"
fi
