#!/bin/bash
#/ Usage:
#/    ghe-mssql-repl-start [-h]
#/
#/ Options:
#/    -h | --help     Show this message.
#/
#/ Start MS SQL replication on the primary and replica.  This script is
#/ idempotent, meaning it will no-op if there are no changes to make.  When
#/ invoked on the replica, this script will ssh to the primary and configure
#/ the primary first, if necessary.
#/
set -e

export PATH="$PATH:/usr/local/share/enterprise"

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-actions-lib
. ghe-actions-lib
#shellcheck source=vm_files/usr/local/share/enterprise/ghe-mssql-lib
. ghe-mssql-lib
#shellcheck source=vm_files/usr/local/share/enterprise/ghe-repl-lib
. ghe-repl-lib
#shellcheck source=vm_files/usr/local/share/enterprise/ghe-mssql-repl-lib
. ghe-mssql-repl-lib

usage() {
  grep '^#/' < "$0" | cut -c 4-
  exit 2
}

fail() {
  >&2 echo "$@"
  exit 1
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  usage
fi

(
  flock 200

  hostname=$(cat /etc/github/cluster)
  mssql_master_node="$(ghe-config cluster.mssql-master)"
  
  key_encryption_password=$(ghe-config "secrets.mssql.key-encryption-password")
  if [ "$mssql_master_node" = "$hostname" ]; then
    setup-mssql-replication-primary
  elif [ -n "$(ghe-config cluster.$hostname.mssql-server)" ]; then
    setup-mssql-replication-replica
  else
    fail "Cannot setup MSSQL HA on node $hostname because it does not have the role mssql-server"
  fi
) 200>/var/run/lock/ghe-mssql-repl-start.lock
