#!/bin/bash
#/ Usage: ghe-cluster-status-git [-hjnv]
#/
#/ Check the status of the Git service in the cluster.
#/
#/ OPTIONS:
#/   -h | --help      Show this message.
#/   -j | --json      JSON formatted output.
#/   -n | --nagios    Nagios formatted output and exit codes.
#/   -v | --verbose   Show verbose output.
#/
set -e

# Show usage.
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' < "$0" | cut -c 4-
  exit 2
fi

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-cluster-status-common
source /usr/local/share/enterprise/ghe-cluster-status-common

start_output "git"

git_status=$(ghe-spokes status | grep -v ^app= || true)
online_hosts=$(mysql_query "SELECT * FROM fileservers WHERE online = 1;" || true)
for hostname in $(ghe-cluster-nodes -r git); do
  uuid=$(ghe-config "cluster.$hostname.uuid")
  if echo "$online_hosts" | grep -q "git-server-$uuid"; then
    check_result "$hostname" "git-host-online" "ok"
  else
    check_result "$hostname" "git-host-online" "error" "Git server (git-server-$uuid) not marked online"
  fi
done

mysql_master=$(/usr/local/share/enterprise/ghe-call-configrb mysql_master)
if [ -n "$git_status" ]; then
  failed_count="$(total_error_counts "$git_status" "FAILED network replicas" "FAILED gist replicas")"
  total_count="$(total_error_counts "$git_status" \
    "under/over-replicated networks" "under/over-replicated gists" \
    "network replicas that need cleanup" "gist replicas that need cleanup" \
    "repo replicas with bad checksums" "gist replicas with bad checksums" \
    "FAILED network replicas" "FAILED gist replicas" \
    "under-replicated repository IDs")"

  if [ "$failed_count" -gt 0 ]; then
    check_result "$mysql_master" "git-replication" "error" "$failed_count failed network replicas"
  elif [ "$total_count" -gt 0 ]; then
    check_result "$mysql_master" "git-replication" "warn" "$total_count unsynchronized repositories and/or gists"
  else
    check_result "$mysql_master" "git-replication" "ok" "Git replication is in sync"
  fi
else
  check_result "$mysql_master" "git-replication" "error" "Git replication has stopped"
fi

end_output "git"
