#!/bin/bash
#
#/ Bash script to invoke common MYSQL functions
#/ Usage: ghe-mysql
#
#/ OPTIONS:
#/
#/    -h, --help     Usage
#/    --check_mysql  Check if MySQL is running
#/    --stop_mysql   Stop MySQL
#/    --start_mysql  Start MySQL
#/

set -e

usage () {
  grep '^#/' < "$0" | cut -c4-
}

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-mysql-lib
. /usr/local/share/enterprise/ghe-mysql-lib

case "$1" in
  -h|--help)
    usage
    ;;
  --check_mysql)
    check_mysql
    ;;
  --stop_mysql)
    stop_mysql
    ;;
  --start_mysql)
    start_mysql
    ;;
  -*)
    echo "error: unexpected flag ${1%%=*}" 1>&2
    usage 1>&2
    exit 1
    ;;
esac
