#!/bin/bash

# For volumes that were created from snapshots, the storage blocks must be pulled down
# from Amazon S3 and written to the volume before you can access them.
# This preliminary action takes time and can cause a significant increase in the latency of
# I/O operations the first time each block is accessed.
# Volume performance is achieved after all blocks have been downloaded and written to the volume.
# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html

# This script reads all files from the provided directory and can be used to expedite partial
# initialization of the volume
set -e

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  exit 1
}

echo "Running ghe-block-init.sh on $1"
fio --opendir=$1 --rw=read --bs=1M --iodepth=32 --ioengine=libaio --direct=1 --name=fs-warmup
