#!/bin/bash
#/ Starts the Elasticsearch Nomad job
#/ Usage: ghe-repl-start-es
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

# we should only use this script to start elasticsearch on replica nodes
ensure_replica

ghe-service-ensure-elasticsearch

if /usr/local/share/enterprise/ghe-service-enabled "elasticsearch" ; then

  # temporarily hard coding curl commands here
  curl -s -o /dev/null -X PUT \
    "localhost:9201/_cluster/settings?pretty" \
    -H 'Content-Type: application/json' \
    -d "{ \"persistent\": { \"cluster.routing.allocation.exclude._ip\": \"\" } }"

  curl -s -X DELETE "localhost:9201/_cluster/voting_config_exclusions?wait_for_removal=false"
fi

ghe-es-wait-for-green --yellow-ok
