#!/usr/bin/env bash

# Default delay of 15 seconds to ensure if this is called via waagent there is enough time for it to report back status.
delay=15 

while [[ $# -gt 0 ]]
do
key="$1"
  case "$key" in
    --restartWaagentAfter)  
      delay=$2
      shift
      shift
      echo "RestartWaagentAfter: $delay"
      ;;
    *)
    echo "Invalid parameter: $1"
    exit 1
    ;;
  esac
done

set -euo pipefail

if [ ! -e /data/user/waagent.unrestricted ] ; then
  touch /data/user/waagent.unrestricted
  echo "Restarting walinuxagent after a delay of $delay seconds."
  sleep "$delay"
  systemctl restart walinuxagent
fi
