#!/bin/bash
#/ Usage: ghe-repl-stop-git
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

ensure_replica
replica_host="git-server-$(cat /data/user/common/uuid)"
echo "UPDATE fileservers SET online = 0 WHERE host = '$replica_host'" | ghe-dbconsole -y
