#!/bin/bash
# Usage: ghe-set-haproxy-pre-config <operation>
# Toggle between prod and pre-config nomad configurations
# Parameters:
#   <operation>:
#                  enable - enable haproxy-pre-config.service
#                  disable - disable haproxy-pre-config.service

OPERATION=$1
if [ "$OPERATION" == 'enable' ]; then
  if ! /bin/systemctl is-enabled haproxy-pre-config &>/dev/null; then
    echo "Enabling haproxy-pre-config.service"
    /bin/systemctl unmask haproxy-pre-config &>/dev/null
    /bin/systemctl enable haproxy-pre-config &>/dev/null
  fi
  if ! /bin/systemctl is-active haproxy-pre-config &>/dev/null; then
    echo "Starting haproxy-pre-config.service"
    /bin/systemctl start haproxy-pre-config &>/dev/null
  fi
elif [ "$OPERATION" == 'disable' ]; then
  if /bin/systemctl is-enabled haproxy-pre-config &>/dev/null; then
    echo "Disabling haproxy-pre-config.service"
    /bin/systemctl stop haproxy-pre-config &>/dev/null
    /bin/systemctl disable haproxy-pre-config &>/dev/null
    /bin/systemctl mask haproxy-pre-config &>/dev/null
  else
    echo "haproxy-pre-config.service is already stopped - nothing to do"
  fi
else
  echo "Must be either enable or disable."
  exit 1
fi
