#!/bin/bash
#/ Usage: ghe-storage-init-alambic <device>
#/ Initialize the specified block device as /data/alambic
set -e

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo Run this script as the root user. >&2
  exit 1
}

export PATH="$PATH:/usr/local/share/enterprise"

ghe-storage-init-device "$1" "/data/alambic-data" 10
