#!/bin/bash
# Retrieve the number of resque jobs being processed in redis
#/ Usage: ghe-resque-jobs-count
#/

ghe-redis-cli smembers resque:workers | xargs -r -I{} echo resque:worker:{} | xargs -r ghe-redis-cli --no-raw mget | grep -cv "(nil)"
