#!/bin/bash
#/  Runs innochecksum against all InnoDB tables in the MySQL datadir
#/  Usage:
#/        ghe-mysql-checksum - defaults to /data/user/mysql/
#/        ghe-mysql-checksum <path to datadir> - specify a datadir
#/

set -e

readonly MYSQL_PATH=${1:-/data/user/mysql/}

# Show usage.
if [ "$1" = "--help" ]
then grep '^#/' <"$0" |cut -c 4-
    exit 2
fi

checksum_table() {
  local ibd=$1
  innochecksum -v $ibd
}

echo "Running innochecksum against all InnoDB tables in $MYSQL_PATH"

for table in $(ls $(readlink -e $MYSQL_PATH)/*/*.ibd)
do
  checksum_table $table
done

