#!/bin/bash
set -e

htmltmp=$(mktemp)
/usr/share/rbenv/versions/current/bin/erb /usr/local/share/enterprise/replication.html.erb > "$htmltmp"
if [ "$(ghe-config cluster.ha || true)" = "true" ]; then
  chown enterprise-manage:enterprise-manage "$htmltmp"
  chmod a+r "$htmltmp"
  cp -a "$htmltmp" /data/enterprise-manage/current/public/index.html
fi
chown git:git "$htmltmp"
mv "$htmltmp" /data/github/current/public/index.html