#!/bin/bash
# Retrieve the number of background jobs being processed
#/ Usage: ghe-background-jobs-count
#/

echo $((10#$(/usr/local/share/enterprise/ghe-resque-jobs-count) + 10#$(/usr/local/share/enterprise/ghe-aqueduct-jobs-count)))
