#!/bin/bash

set -e

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo Run this script as the root user. >&2
  exit 1
}

user_dirs="alambic_cdn alambic_assets storage"
mountpoint="/data/alambic-data"

if ! mountpoint -q "$mountpoint"; then
  echo "Error: $mountpoint is not mounted. Use ghe-storage-init-alambic first." >&2
  exit 1
fi

for dir in $user_dirs; do
  user_dir="/data/user/$dir"
  if [ -L "$user_dir" ]; then
    echo "Error: $user_dir is already a symlink" >&2
    exit 1
  elif [ -e "$user_dir" ]; then
    echo "Preseeding $user_dir to $mountpoint ..."
    rsync --info=progress2 -a --delete "$user_dir" "$mountpoint/"
  fi
done

echo "Success: alambic directories preseeded to $mountpoint"
