#!/bin/bash
#/ Github Eneterprise wrapper for orchestrator-client. We need this since with http_proxy set,
#/ orchestrator-client will not be able to return correctly through the API

http_proxy="" /usr/share/orchestrator/orchestrator-client "$@"
