#!/bin/bash
# Use this script to bring databases from RESTORING state to ONLINE and ready for setup as stand alone instance again.
# It applies in following scenarios:
#   - After failover away and dropping local availability group on old primary, local databases will be in RESTORING state.
#   - After stopping mssql replication (where the replica is removed from AG).
set -e

all_dbs=$(ghe-mssql-console -y -n -q "SET NOCOUNT ON; SELECT name FROM sys.databases")
for db in $all_dbs; do
  if [[ ! "$db" =~ ^(master|tempdb|model|msdb)$ ]] && [[ "$db" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    ghe-mssql-console -y -q "RESTORE DATABASE [$db] WITH RECOVERY" 1>/dev/null
  fi
done
