#!/bin/bash
#/ Usage: ghe-cluster-status-metrics [-hjnv]
#/
#/ Check the status of the metrics service in the cluster.
#/
#/ OPTIONS:
#/   -h | --help      Show this message.
#/   -j | --json      JSON formatted output.
#/   -n | --nagios    Nagios formatted output and exit codes.
#/   -v | --verbose   Show verbose output.
#/
set -e

# Show usage.
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' < "$0" | cut -c 4-
  exit 2
fi

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-cluster-status-common
source /usr/local/share/enterprise/ghe-cluster-status-common

start_output "metrics"
metric_name=memory.memory-used.value
for hostname in $(ghe-cluster-nodes -r metrics); do
  for _ in $(seq 1 5); do
    metrics=$(curl --connect-timeout "$CONNECT_TIMEOUT" -s --noproxy '*' "http://$hostname:8000/render?format=json&from=-5min&target=$hostname.$metric_name" || true)
    if [ "$metrics" != "[]" ]; then
      break
    fi
    sleep 1
  done
  if [ -z "$metrics" ]; then
    check_result "$hostname" "metrics-graphite-render" "error" "No metrics returned or connection timed out"
  elif [ "$metrics" != "[]" ]; then
    check_result "$hostname" "metrics-graphite-render" "ok"
  else
    check_result "$hostname" "metrics-graphite-render" "error" "Metric not found"
  fi
done

end_output "metrics"