#!/bin/bash
#/ Usage: ghe-service-wait-aqueduct <timeout>
set -eu

timeout=${1:-900}
port=${AQUEDUCT_PORT:-9096}

check_aqueduct() {
  curl --fail "http://localhost:$port/admin/health" | jq -r .status | grep UP
}

for _ in $(seq "$timeout"); do
  if check_aqueduct 2>/dev/null; then
    exit 0
  fi
  sleep 1
done

exit 1
