#!/bin/bash
#/ Usage: ghe-service-wait-minio <timeout>
set -eu

timeout=${1:-900}
port=${MINIO_PORT:-10004}

check_minio() {
  curl --fail "http://localhost:$port/minio/health/ready"
}

for _ in $(seq "$timeout"); do
  if check_minio 2>/dev/null; then
    exit 0
  fi
  sleep 1
done
check_minio
exit 1
