#!/bin/bash

set -e

export MYSQL_USERNAME="${MYSQL_USERNAME:-$(/usr/local/share/enterprise/ghe-call-configrb mysql_username)}"
export MYSQL_PASSWORD="${MYSQL_PASSWORD:-$(/usr/local/share/enterprise/ghe-call-configrb mysql_password)}"
TURBOGHAS_IMAGE_TAG="turboghas:$(cat /data/docker-image-tags/turboghas_image_tag)"
export TURBOGHAS_LOG_LEVEL="${TURBOGHAS_LOG_LEVEL:-error}"

docker_run_mode="-i"
migration_list_file=
migration_events_file=

case "$1" in
transition)
    binary=transition
    migration_list_file=/data/user/tmp/turboghas-migration-list.json
    migration_events_file=/data/user/tmp/turboghas-migration-events.json
    ;;
*)
    echo "Usage: ghe-turboghas (transition)" >&2
    exit 1
    ;;
esac
shift

docker run "$docker_run_mode" --rm --network host \
    -e APP_ENV=enterprise \
    -e GHES_MIGRATION_LIST_FILE="$migration_list_file" \
    -e GHES_MIGRATION_EVENTS_FILE="$migration_events_file" \
    -e MYSQL_USERNAME \
    -e MYSQL_PASSWORD \
    -e MYSQL_ADDR="localhost:3307" \
    -e MYSQL_DB_NAME=github_enterprise \
    -e TURBOGHAS_LOG_LEVEL \
    --entrypoint "$binary" \
    -i "$TURBOGHAS_IMAGE_TAG" \
    "$@"
