#!/bin/bash

set -e
export PATH="$PATH:/usr/local/share/enterprise"

github-mysql "SELECT COUNT(*) as queries FROM INFORMATION_SCHEMA.PROCESSLIST WHERE COMMAND = \"Query\" AND ID != CONNECTION_ID();" | tail -n 1
