#!/usr/share/rbenv/versions/current/bin/ruby
# frozen_string_literal: true
#/ Usage: cat meta.json | ghe-es-load-meta http://localhost:9200 > failures.json
require "rubygems"
require "net/http"
require "json"
require "uri"

if ARGV.size < 1
  puts File.read(__FILE__).lines.select { |l| l =~ /^#\// }.map { |l| l[3, l.size] }.join("\n")
  exit 1
end

url = ARGV[0]
uri = URI.parse(url)

Net::HTTP.start(uri.host, uri.port) do |http|
  STDIN.set_encoding("BINARY", "BINARY") if STDIN.respond_to?(:set_encoding)
  STDIN.each do |line|
    metadata = JSON.parse(line)
    metadata.each do |index_name, index_metadata|
      uri.path = "/#{index_name}"
      request = Net::HTTP::Put.new uri
      request["Content-Type"] = "application/json"
      request.body = JSON.dump(index_metadata)
      response = http.request request
      if response.code != "200"
        STDERR.puts response.body
        STDOUT.puts JSON.dump({index_name => index_metadata})
      end
    end
  end
end
