#!/bin/bash

#/ Handles removing mssql replication prior to restoring from backup
#/ The ghe-config-apply that happens at the end of the restore should re-enable it

set -e

export PATH="$PATH:/usr/local/share/enterprise"

#shellcheck source=vm_files/usr/local/share/enterprise/ghe-mssql-lib
. ghe-mssql-lib

echo "Dropping existing availability group..."

# marking this best effort, these should really only fail if they are already gone
ghe-mssql-console -y -q "DROP AVAILABILITY GROUP ha" || true

echo "Dropping replication endpoint and certificate..."
ghe-mssql-console -y -q "DROP ENDPOINT agep" || true
ghe-mssql-console -y -q "DROP CERTIFICATE dbm_certificate" || true
sudo rm -f /data/user/mssql/data/endpoint.cer || true
sudo rm -f /data/user/mssql/data/endpoint.pvk || true
