#!/bin/bash

if [ -e '/etc/gitub/configured' ] ; then
  exit 0
fi

if [ ! -e '/etc/haproxy/ssl.crt+key' ] ; then
  /usr/local/share/enterprise/ghe-ssl-generate-self-signed
fi

if $(openssl x509 -in /etc/haproxy/ssl.crt -text | grep "Subject:" | grep -q "GitHub Automatic Self Signed Certificate"); then
  /usr/share/rbenv/versions/current/bin/erb -r openssl -r digest -T - /usr/local/share/enterprise/ssl_warning.html.erb > /data/enterprise-manage/current/public/ssl_warning.html
  file /data/enterprise-manage/current/public/ssl_warning.html
else
  rm -f /data/enterprise-manage/current/public/ssl_warning.html
fi
