#!/bin/bash
#/ Usage: ghe-cluster-hostname-init
#/
#/ Initializes the hostname for clusters. Used by manage's cluster-init API end point.
#/
#/ OPTIONS:
#/   -h                 Show this message
#/   -v                 Run with verbose output

set -e

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo Run this script as the root user. >&2
  exit 1
}

usage() {
  grep '^#/' <"$0" | cut -c 4-
}

while getopts "hv" OPTION; do
  case $OPTION in
    h)
      usage
      exit 2
      ;;
    v)
      set -x
      ;;
    ?)
      usage
      exit
      ;;
  esac
done

hostname=$1

if [ -f /etc/hosts.dnsmasq ]; then
  echo "Updating hosts..."
  sed -i 's/127.0.0.1.*/127.0.0.1\t'"$hostname"'/g' /etc/hosts.dnsmasq;
fi

echo "Updating hostname..."
hostnamectl set-hostname "$hostname"

echo "Updating /etc/github/cluster..."
echo "$hostname" > /etc/github/cluster;

echo "Reloading dnsmasq service"
systemctl reload dnsmasq.service

echo "Success."
