#!/bin/bash
set -e
set -x
export PATH="$PATH:/usr/local/share/enterprise"

[ "$(whoami)" = "root" ] || {
  exec sudo -u root "$0" "$@"
  echo Run this script as the root user. >&2
  exit 1
}

if [ "$(cat /etc/github/repl-state 2>/dev/null)" = "replica" ]; then
  exit 0
fi

initial_message=$1

function set_status_message {
  export LOADING_STATUS="$1"
  if [ -f /data/github/current/public/index.html ]; then LOADING=1 UNICORN=1 /usr/share/rbenv/versions/current/bin/erb /usr/local/share/enterprise/preflight.html.erb > /data/github/current/public/index.html; fi
  if [ -f /data/enterprise-manage/current/public/index.html ]; then LOADING=1 /usr/share/rbenv/versions/current/bin/erb /usr/local/share/enterprise/preflight.html.erb > /data/enterprise-manage/current/public/index.html; fi
}

set_status_message "$initial_message"
