#!/bin/bash
#/ Usage: ghe-cleanup-removed-refs
#/ Prunes erroneously created special "removed" refs from replica repositories.
set -e

# usage
if [ "$1" = "--help" ]; then
  grep '^#/' < "$0" | cut -c4-
  exit 1
fi

# re-exec as the git user
if [ $(whoami) != "git" ]; then
  exec sudo -u git "$0" "$@"
  exit 1
fi

# delete recursively created removed refs from all repositories
cd /data/user/repositories
for repo in $(find . -name '*.git' -type d); do
  echo "cleaning: $repo ..."
  git --git-dir="$repo" show-ref |
    cut -d ' ' -f 2 | grep '^refs/removed/[^/]*/removed' |
    xargs -rn 1 git --git-dir="$repo" update-ref -d || true
done
