#!/bin/bash
#/ Usage: ghe-repl-start-git
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

ensure_replica
replica_host="git-server-$(cat /data/user/common/uuid)"
primary_ssh "/usr/local/share/enterprise/github-mysql \"UPDATE fileservers SET online = 1 WHERE host = '$replica_host'\""
