#!/bin/bash
#/ ghe-hook-env-update-curl is a helper for ghe-hook-env-update,
#/ to wrap `curl` so it can run under sudo as the "githook" user.
#/
#/ Being the user that web hooks run as, "githook" has its
#/ network connections restricted by iptables, e.g. localhost is denied.
#/
#/ Run as: sudo -u githook ghe-hook-env-update-curl http://url/foo.tar
#/ STDOUT will receive the name of the temp directory created

set -euo pipefail

TARBALL_URL=${1:?"URL argument must be specified"}

if [ "$(whoami)" != "githook" ] && [[ $TARBALL_URL =~ ^https?: ]]; then
  echo "Run this script as the githook user." >&2
  exit 1
fi

curl --globoff --location --silent --show-error --max-time 900 \
  --proto =http,https,file --proto-redir =http,https \
  --no-buffer "$TARBALL_URL"
