#!/bin/bash
#/ Usage: ghe-service-wait-redis --local <timeout>
set -e

if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' < "$0" | cut -c4-
  exit 2
fi

check_local=false
if [ "$1" = "--local" ]; then
  shift
  check_local=true
fi

timeout=${1:-900}

check_redis() {
  if $check_local; then
    ghe-redis-cli --local ping
  else
    ghe-redis-cli ping
  fi
}

for i in $(seq $timeout); do
  if check_redis 2>/dev/null | grep -q PONG; then
    exit 0
  fi
  sleep 1
done
check_redis
