#!/bin/bash
#/ Usage: ghe-storage-init-db <device>
#/ Initialize the specified block device as /data/db
set -e
export PATH="$PATH:/usr/local/share/enterprise"

ghe-storage-init-device "$1" "/data/db" 10
