#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "/usr/local/share/enterprise/lib/config"

options = {}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: /usr/local/share/enterprise/ghe-config-apply-status --reset"

  opts.on("--reset", "Resets the config apply status (updating the /data/user/common/ghe-config-apply.status.json on disk)") do
    options[:reset] = true
  end

  opts.on_tail("-h", "--help", "Prints this help") do
    warn opts
    exit 2
  end
end
parser.parse!

if options[:reset].nil?
  warn parser
  exit 2
end

begin
  Enterprise::ConfigApply::Run.new.reset_status
rescue => e
  STDERR.puts "The config status could not be reset: #{e.message}"
  exit 1
end
