#!/usr/share/rbenv/versions/current/bin/ruby
#/ This script is used by backup-utils during ghe-restore.
#/
#/ Usage: cat network_list.txt | ghe-restore-gist-routes > gists_with_routes.txt

r, w = IO.pipe
spawn "github-env", "bin/ghe-lookup-gist-ids", out: w
spawn "ghe-spokesctl", "backup-utils", "restore-gist-routes", in: r
w.close
r.close

statuses = Process.waitall
ok = statuses.all? { |_, status| status.success? }
exit 1 unless ok
