#!/bin/bash
#/ Usage:
#/    ghe-repl-start-redis # Start Redis replication
#/ Start mysql replication on a configured replica.
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

ghe-redis-repl-start "$(primary_ip)"
