#!/bin/bash
#/ Optimizes all tables in the github_enterprise database.
#/ Optimizing a table allows MySQL to reclaim space and reduce the size of the table.
#/ Usage:
#/          ghe-mysql-optimize [options]
#/ Options:
#/          -h | --help           Show this message
#/          -t | --table <table>  Table to optimize
#/          -a | --all            Optimize all tables

set -e

optimize() {
  local table=$1
  if [[ -z $table ]]; then
    mysqlcheck -u root -o github_enterprise
  else
    mysqlcheck -u root -o github_enterprise $table
  fi
  echo "Optimize complete."
}

usage(){
  grep '^#/' <"$0" |cut -c 4-
  exit 2
}

proceed() {
    read -p "Proceed with MySQL optimize? [y/N] " -r
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
      exit 1
    fi
}

case $1 in
  -h|--help)
    usage
  ;;

  -t|--table)
    banner=$(cat <<EOF
This will lock the table $2 while the optimize is running.
It is recommended you only run this while the host is in maintenance mode.
EOF
)
    echo "$banner"
    proceed
    optimize $2
  ;;

  -a|--all)
    banner=$(cat <<EOF
This will optimize all tables in the github_enterprise database.
While this tool is running the tables will be locked.
It is recommended you only run this while the host is in maintenance mode.
EOF
)
    echo "$banner"
    proceed
    optimize
  ;;

  *)
    usage
  ;;
esac
