#!/bin/bash
#/ Usage: ghe-repl-sync-git-hooks [ASSET PATH]
set -e

# re-exec as the git user
if [ $(whoami) != "git" ]; then
  exec sudo -u git "$0" "$@"
  exit 1
fi

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib
ensure_primary

# can be empty, that just means it'll do a full sync
ASSET_PATH="$1"

date +%s > /data/user/git-hooks/.last_git-hooks_sync

(
  flock -w 1 -n 9 || {
    echo "ghe-repl-sync-git-hooks-do-sync is already running" >&2
    exit 0
  }

  /usr/local/share/enterprise/ghe-repl-sync-git-hooks-do-sync $ASSET_PATH
) 9>/var/run/lock/ghe-repl-git-hooks.lock
