#!/usr/share/rbenv/versions/current/bin/ruby
# frozen_string_literal: true
#/ Usage: ghe-http-hostnames
#/   List the HTTP hostnames currently active in `haproxy-frontend.cfg`

haproxy_cfg = ENV["HAPROXY_CFG"] || "/etc/haproxy/haproxy-frontend.cfg"

# Read config file, strip comments, and pull out the hostnames
# Note, this is fairly fragile and would break if the format of haproxy-frontend.cfg were different
hostnames = File.read(haproxy_cfg).gsub(/#.+$/, "").scan(/acl\s+\w+_host.+ -i ([^\s:]+):?/).flatten.uniq

# sort the list, but put the "root" domain first
root = hostnames.min { |a, b| a.size <=> b.size }
hostnames = [root] + hostnames.grep_v(root).sort

puts hostnames.join("\n")

STDERR.puts "No hostnames were found in #{haproxy_cfg}" if hostnames.empty?
