#!/bin/bash

set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib
. ghe-repl-consul
ensure_replica

if systemctl is-active consul-replicate >/dev/null ; then
    if ! out=$(sudo systemctl stop consul-replicate >/dev/null); then
      echo "$out" 1>&2
      exit 1
    else
      exit 0
    fi
else
    echo "consul-replicate was not running"
    exit 0
fi
