#!/bin/bash
#/ Usage: ghe-repl-stop-pages
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

ensure_replica

if [ -f /etc/github/cluster ]; then
  replica_host="pages-server-$(cat /data/user/common/uuid)"
  echo "UPDATE pages_fileservers SET online = 0, updated_at = NOW() WHERE host = '$replica_host'" | ghe-dbconsole -y 2>/dev/null
fi
