#!/bin/bash
set -e

HOSTNAME=$1
IP=$2
SSH_KEY=$(ghe-config secrets.admin-ssh-pubkey)
LICENSE=/data/user/common/enterprise.ghl

# Use the password set in configs if it's set
if ghe-config --blank secrets.manage; then
  PASSWORD="$(openssl rand -hex 16)4eMx"  
else
  PASSWORD=$(ghe-config secrets.manage)
fi

if [ ! -f $LICENSE ]; then
  echo "License file not installed"
  exit 1
fi

# us ghes-manage api to init node
EXIT_CODE=0
output=$(sudo curl --noproxy '*' -s -k -w "%{http_code}" "https://${IP}:8443/manage/v1/cluster/init-node" -F "hostname=${HOSTNAME}" -F "authorized_key=${SSH_KEY}" -F license=@${LICENSE} -F "password=${PASSWORD}")
echo $output | grep -q 200 || EXIT_CODE=$?
if [ $EXIT_CODE -eq 0 ]; then
  echo "Node initialised via GHES Manage API"
  exit 0
else
  exit $EXIT_CODE
fi

