#!/bin/sh
#/ Usage: ghe-clean-fs

set -e
umask 0022

# Show usage.
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
  grep '^#/' <"$0" | cut -c 4-
  exit 2
fi

touch /tmp/clean_fs.lock
for i in 0 1 2 3 4 5 6 7 8 9 a b c d e f; do

  if [ -d /data/repositories/$i ]; then
    # refresh repositories index
    find /data/repositories/$i/?? -mindepth 4 -maxdepth 5 -type d -name *.git > /data/repositories/$i/index.txt.new 2>/dev/null || true
    mv /data/repositories/$i/index.txt.new /data/repositories/$i/index.txt
  fi
done
rm -f /tmp/clean_fs.lock

#cleanup up dpages migration directories older than 30 days
find /data/user -maxdepth 0 -name 'pages-old*' -type d -ctime +30 -exec rm -rf {} +
