#!/bin/bash

set -e

[ -z "$FORCE_INSTALL" ] && systemctl --quiet is-active docker && {
  # As an additional safety, don't run this meaningfully when Docker is active, as the intent is that
  # the system is more or less completely inactive when these upgrades occur.
  echo "Docker is running, not installing packages this boot"
  exit 0
}

if [ ! -d "/data/deferred-upgrade-packages" ] || [ -z "$(ls -A /data/deferred-upgrade-packages/*.deb 2>/dev/null)" ] ; then
  echo "No deferred packages to install, exiting"
  exit 0
fi

export DEBIAN_FRONTEND=noninteractive

# Install all the packages at once to take into account intermediate dependency issues
# All of the version checking (i.e. "do we install this package or not") is done in the hotpatch
# installer and the package file won't actually exist unless it needs to be installed
dpkg --install /data/deferred-upgrade-packages/*.deb
rm -vf /data/deferred-upgrade-packages/*.deb


