#!/bin/bash
# Check if there's a restore in progress, if there's one wait for it to finish

set -e

status_file="/data/user/common/ghe-restore-status"

if ! test -e "$status_file"; then
  echo "OK: $status_file doesn't exist"
  exit 0
fi

while test "$(cat $status_file)" != "complete"; do
  echo "restore not complete: $(cat $status_file)"
  sleep 10
done

echo "OK: restore is complete"
