#!/bin/bash
#/ Usage:
#/    ghe-repl-start-mysql # Configure or start MySQL replication
#/ Start mysql replication on a configured replica.
set -e

export PATH="$PATH:/usr/local/share/enterprise"
. ghe-repl-lib

ghe-mysql-repl-start "$(primary_ip)" "$@"
