#!/bin/bash
#/ Teardown Elasticsearch node from a cluster / HA
#/ Usage: ghe-repl-es-teardown
set -e

sudo rm -rf /data/user/elasticsearch
sudo mkdir -p /data/user/elasticsearch/_state
sudo chown -R elasticsearch:elasticsearch /data/user/elasticsearch /data/user/elasticsearch/_state
sudo chmod 0700 /data/user/elasticsearch /data/user/elasticsearch/_state
