#!/usr/bin/bash
set -e

if [ $# -ne 1 ]; then
  echo "Find the first history directory matching a given Config-Apply run_id"
  echo "Usage: $0 <run_id>"
  exit 1
fi

run_id="$1"

# Check history directories for a matching run_id
for d in {/data/user/config-apply,/data/user/common/ghe-config-apply/config-file-history/*}; do
  if run_id="$run_id" jq -e '.run_id == env.run_id' $d/status.json > /dev/null; then
    echo "$d"
    exit 0
  fi
done

echo "run id not found" >&2
exit 1
