#!/bin/bash
set -e

. /usr/local/share/enterprise/ghe-systemd-lib.sh

if [ $# -ne 1 ] ; then
  log_message "usage: $0 [name of unicorn process]"
  exit 1
fi

if [ -z "$MAINPID" ] ; then
  log_message "this script expects MAINPID to be set"
  exit 1
fi

wait_for_unicorns $1
