# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Billing::UsageThresholdBanner`.
# Please instead update this file by running `bin/tapioca dsl Billing::UsageThresholdBanner`.

class Billing::UsageThresholdBanner
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
