# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Platform::Interfaces::Actor`.
# Please instead update this file by running `bin/tapioca dsl Platform::Interfaces::Actor`.

module Platform::Interfaces::Actor
  extend GraphQL::Schema::Interface::DefinitionMethods
  extend Platform::Interfaces::Base::BaseDefinitionMethods
end
