# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest`.

class GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest
  sig do
    params(
      owner_id: T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity),
      updates: T.nilable(T.any(Google::Protobuf::RepeatedField[GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest::LabelOps], T::Array[GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest::LabelOps]))
    ).void
  end
  def initialize(owner_id: nil, updates: T.unsafe(nil)); end

  sig { void }
  def clear_owner_id; end

  sig { void }
  def clear_updates; end

  sig { returns(T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity)) }
  def owner_id; end

  sig { params(value: T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity)).void }
  def owner_id=(value); end

  sig do
    returns(Google::Protobuf::RepeatedField[GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest::LabelOps])
  end
  def updates; end

  sig do
    params(
      value: Google::Protobuf::RepeatedField[GitHub::Launch::Services::Selfhostedrunners::BulkUpdateRunnerLabelsRequest::LabelOps]
    ).void
  end
  def updates=(value); end
end
