# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::Launch::Services::Selfhostedrunners::DeleteRunnerRequest`.
# Please instead update this file by running `bin/tapioca dsl GitHub::Launch::Services::Selfhostedrunners::DeleteRunnerRequest`.

class GitHub::Launch::Services::Selfhostedrunners::DeleteRunnerRequest
  sig do
    params(
      repository_id: T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity),
      runner_id: T.nilable(Integer)
    ).void
  end
  def initialize(repository_id: nil, runner_id: nil); end

  sig { void }
  def clear_repository_id; end

  sig { void }
  def clear_runner_id; end

  sig { returns(T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity)) }
  def repository_id; end

  sig { params(value: T.nilable(GitHub::Launch::Pbtypes::GitHub::Identity)).void }
  def repository_id=(value); end

  sig { returns(Integer) }
  def runner_id; end

  sig { params(value: Integer).void }
  def runner_id=(value); end
end
