# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlatformTypes::DeleteProjectV2ItemPayload`.
# Please instead update this file by running `bin/tapioca dsl PlatformTypes::DeleteProjectV2ItemPayload`.

class PlatformTypes::DeleteProjectV2ItemPayload < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(String)) }
  def client_mutation_id; end

  sig { returns(T::Boolean) }
  def client_mutation_id?; end

  sig { returns(T.nilable(T.any(String, Integer))) }
  def deleted_item_id; end

  sig { returns(T::Boolean) }
  def deleted_item_id?; end
end
