# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlatformTypes::IncrementRegistryPackageDownloadCountPayload`.
# Please instead update this file by running `bin/tapioca dsl PlatformTypes::IncrementRegistryPackageDownloadCountPayload`.

class PlatformTypes::IncrementRegistryPackageDownloadCountPayload < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(String)) }
  def client_mutation_id; end

  sig { returns(T::Boolean) }
  def client_mutation_id?; end

  sig { returns(T.nilable(T.any(String, Integer))) }
  def package_version_id; end

  sig { returns(T::Boolean) }
  def package_version_id?; end
end
