# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlatformTypes::OauthApplicationTransferAuditEntryState`.
# Please instead update this file by running `bin/tapioca dsl PlatformTypes::OauthApplicationTransferAuditEntryState`.

module PlatformTypes::OauthApplicationTransferAuditEntryState
  sig { returns(T::Boolean) }
  def active?; end

  sig { returns(T::Boolean) }
  def pending_deletion?; end

  sig { returns(T::Boolean) }
  def suspended?; end

  ACTIVE = T.let("ACTIVE", String)
  PENDING_DELETION = T.let("PENDING_DELETION", String)
  SUSPENDED = T.let("SUSPENDED", String)
end
