# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PlatformTypes::UpdateProjectV2CollaboratorsPayload`.
# Please instead update this file by running `bin/tapioca dsl PlatformTypes::UpdateProjectV2CollaboratorsPayload`.

class PlatformTypes::UpdateProjectV2CollaboratorsPayload < GraphQL::Client::Schema::ObjectClass
  sig { returns(T.nilable(String)) }
  def __typename; end

  sig { returns(T.nilable(String)) }
  def client_mutation_id; end

  sig { returns(T::Boolean) }
  def client_mutation_id?; end

  sig { returns(T.nilable(PlatformTypes::ProjectV2ActorConnection)) }
  def collaborators; end

  sig { returns(T::Boolean) }
  def collaborators?; end
end
