# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Marketplace::Payloads::Models::Show`.
# Please instead update this file by running `bin/tapioca dsl Marketplace::Payloads::Models::Show`.

class Marketplace::Payloads::Models::Show
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
