# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BillingPlatform::Api::V1::CreateDiscountResponse`.
# Please instead update this file by running `bin/tapioca dsl BillingPlatform::Api::V1::CreateDiscountResponse`.

class BillingPlatform::Api::V1::CreateDiscountResponse
  sig { params(uuid: T.nilable(String)).void }
  def initialize(uuid: nil); end

  sig { void }
  def clear_uuid; end

  sig { returns(String) }
  def uuid; end

  sig { params(value: String).void }
  def uuid=(value); end
end
