# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BillingPlatform::Api::V1::GetAllProductsRequest`.
# Please instead update this file by running `bin/tapioca dsl BillingPlatform::Api::V1::GetAllProductsRequest`.

class BillingPlatform::Api::V1::GetAllProductsRequest
  sig { void }
  def initialize; end
end
