#!/bin/sh

NONGIT_OK=
SUBDIRECTORY_OK=t
. "$(git --exec-path)/git-sh-setup"

# Return cumulative on-disk size of all objects on stdin.
object_size() {
    git cat-file --batch-check='%(objectsize:disk)' |
    perl -lne '$total += $_; END { print $total+0 }'
}

# Convert a large size into a more human-readable figure.
humanize() {
    perl -lne '
        sub show { print int($_[1]+0.5), $_[0] }
        if ($_ < 1024) { print $_; next }
        $_ /= 1024; if ($_ < 1024) { show(K => $_); next }
        $_ /= 1024; if ($_ < 1024) { show(M => $_); next }
        $_ /= 1024; show(G => $_);
    '
}

# Show the ratio of $1/$2 as an integer percentage.
percent() {
    if test "$2" -eq 0
    then
        echo "NA"
    else
        echo $((100 * $1 / $2))
    fi
}
