#!/bin/sh
# Usage: git prune-refs
# Prunes empty directories under refs/*. These are left around after
# git-pack-refs under git <= v1.7.0.2 and can cause serious performance problems
# because all other commands want to stat every file in the whole hierarchy.
# This has been fixed in newer version of git. This script can be removed once
# the new version is live.

# better safe than sorry
git_dir="$(git rev-parse --git-dir)" || exit 1

# grab all directories depth-first and attempt an rmdir on them
find "$git_dir"/refs -mindepth 1 -depth -type d |
    xargs rmdir 2>/dev/null

# rmdir fails on non-empty directories. we don't care.
exit 0
