#!/bin/sh
# Git post-upload-pack hook script. Runs after any fetch or clone operation
# completes.

: ${AUDIT_MSG:-"got a clone/fetch outside production in $(pwd)"}

LOGGER_FLAGS="-i -t github_audit -p user.info --size 4096"

logger $LOGGER_FLAGS "$AUDIT_MSG" 1>/dev/null 2>&1 ||
    echo "Warning: R9133 Please contact GitHub Enterprise Support via https://support.github.com." 1>&2

exit 0
