#!/bin/sh
# Wrapper for git hooks that forces them to use bin/safe-ruby.
# Also exports a $REPO_PATH pointing to the originating <id>.git.
set -e

if [ -n "$GIT_SOCKSTAT_VAR_disable_hooks" ]; then
  export GIT_SOCKSTAT_VAR_quarantine_only=1
fi

# expand relative paths and symlinks to an absolute canonical path.
_realpath () {
    (cd "$1" && pwd -P)
}

ROOT=$(_realpath $(_realpath $(dirname $0))/../../../..)
SAFE_RUBY=$ROOT/bin/safe-ruby

REPO_PATH=$(_realpath $(dirname $0)/..)
export REPO_PATH

if [ "$GIT_SOCKSTAT_VAR_githooks_env" = "development" ] || [ "$GIT_SOCKSTAT_VAR_githooks_env" = "test" ]; then
    PRE_RECEIVE_BINARY=$ROOT/vendor/gitrpcd/build/githooks/ghe/fork/pre-receive
else
    PRE_RECEIVE_BINARY=/usr/libexec/ghe-pre-receive-fork
fi
$PRE_RECEIVE_BINARY && rc=$? || rc=$?

if [ $rc -eq 2 ]; then
    rc=1
fi

exit $rc
