# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Actions::ScheduledDeleteActionRequiredCheckSuitesJob`.
# Please instead update this file by running `bin/tapioca dsl Actions::ScheduledDeleteActionRequiredCheckSuitesJob`.

class Actions::ScheduledDeleteActionRequiredCheckSuitesJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: Actions::ScheduledDeleteActionRequiredCheckSuitesJob).void)
      ).returns(T.any(Actions::ScheduledDeleteActionRequiredCheckSuitesJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
