#!/bin/bash
# Usage: script/cibuild
# CI build script
set -e

# setup environment
export PATH="/usr/local/share/nodenv/shims:$PATH"
export NODENV_VERSION=v6.9.1

#shellcheck disable=SC2155
export RAILS_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export RAILS_ENV="test"
export RACK_ROOT="$RAILS_ROOT"
export RACK_ENV="$RAILS_ENV"

BASE_PATH="$(cd "$(dirname "$0")"/../../ && pwd)"

# chdir to project root early on
cd "$RAILS_ROOT"

# reset working tree to a pristine state to ensure a clean build. this ensures
# that artifacts aren't left around from previous builds.
rm -rf tmp/*
mkdir -p bin

#shellcheck source=./script/util.sh
. "$BASE_PATH/script/util.sh"

# clean out the ruby environment
export PATH="/usr/share/rbenv/shims:$PATH"
export RUBYLIB=
export RUBYOPT=
#shellcheck disable=SC2155
export RBENV_VERSION="$(< .ruby-version)"

run_summarize script/bootstrap --local

echo "Running tests..."
./script/test
