#!/bin/bash
# Usage: script/cibuild-js
set -ex

export PATH="/usr/local/share/nodenv/shims:$PATH"
export NODENV_VERSION=v6.9.1

# setup environment
export RAILS_ROOT=$(cd "$(dirname $0)"/.. && pwd)
export RAILS_ENV="test"
export RACK_ROOT="$RAILS_ROOT"
export RACK_ENV="$RAILS_ENV"

# chdir to project root early on
cd "$RAILS_ROOT"

# clean out the ruby environment
export PATH="/usr/share/rbenv/shims:$PATH"
export RUBYLIB=
export RUBYOPT=
export RBENV_VERSION="$(< .ruby-version)"

# reset working tree to a pristine state to ensure a clean build. this ensures
# that artifacts aren't left around from previous builds.
git clean -qfdx -e "/vendor/gems" -e "/.bundle" -e "/bin" -e "/tmp"
rm -rf tmp/*
mkdir -p bin

BASE_PATH=$(cd $(dirname $0)/../../ && pwd)

. $BASE_PATH/script/util.sh

export FORCE_BUILD=1

run_summarize script/bootstrap

# Run Tests
export CI=1
./script/run-js-tests.sh
