#!/bin/bash
# Usage: script/clean
# Get back to a clean environment.

# Cleanup after all of the Docker resources that may have been created and could be caching things.
# This cleans up networks, images and volumes. It should probably always be the last cleanup step,
# as other steps may actually use Docker to execute their cleanup.
exec docker compose \
  -f docker-compose.dependencies.yaml -f docker-compose.dev.yaml -f docker-compose.vscode.yaml \
  down --volumes --rmi all

