#!/bin/bash
# Usage: script/db-shell
# Exec into the MySQL DB container

docker exec -it "$(docker ps --format '{{json .}}' | jq -r '. | select(.Names=="enterprise-manage_mysql_1").ID')" mysql -umc -pmc github_enterprise
