#!/bin/bash
# Usage: script/server
# Start a local development server.

# Get the GHES Manage SHA
GHES_MANAGE_SHA="${GHES_MANAGE_SHA:-$(cat ../manifest-focal/base-pinned | grep ghes-manage | sed -n 's/.*~\(.*\)-\{1\}\([a-f0-9]*\).*/\2/p')""}"

service="${1:-single}"
exec env GHES_MANAGE_SHA=$GHES_MANAGE_SHA docker compose \
  -f docker-compose.dependencies.yaml -f docker-compose.dev.yaml \
  run --rm "$service" /bin/bash
