#!/bin/bash
# Usage: script/setup
# Setup licenses used for local development.

if ! [ -f /.dockerenv ] || [ -n "$CODESPACES" ]; then
  exec docker compose -f docker-compose.dependencies.yaml -f docker-compose.vscode.yaml \
    run --rm vscode script/setup "$@"
fi

# force run under bundler
if [ -z "$BUNDLE_BIN_PATH" ]; then
  exec bundle exec "$0" "$@"
fi

set -e

# grab root project dir and change into it
root="$(cd $(dirname "$0")/.. && pwd)"
cd "$root"

if [ "$1" = "--force" ]; then
  echo "Cleaning up and regenerating licenses"
  ./bin/rake clean
fi

mkdir -p tmp/pids work

if [ -f "license.ghl" ] && [ -f "unlimited.ghl" ] && [ -f "perpetual.ghl" ] && [ -f "expired.ghl" ]; then
  echo "Licenses already exist, use --force if you'd like to regenerate licenses."
fi

./bin/rake setup

echo "All setup! Run script/server to start the development server."
