#!/usr/bin/env ruby
# frozen_string_literal: true
# / Usage: sync-settings
# / Reads the current github.conf and secrets.conf and regenerates these files.
# / This process backfills any missing keys and defaults.

# setup load path
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)
require "rubygems"
require "bundler/setup"
$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
ENV["ENTERPRISE_IS_SETTINGS_SYNC"] = "1"

require "manage"

Manage.setup

configuration = Manage::EnterpriseSettings.load(Manage.github_conf_path)
# Rugged::Config#tranasaction will handle rolling back the configuration
# if an exception occurs during the save proccess.
begin
  configuration.save
  $stdout.puts "Configuration updated."
  ENV["ENTERPRISE_IS_SETTINGS_SYNC"] = "0"
rescue
  $stderr.puts "Failed to update configuration."
  exit 1
end
