#!/bin/bash
# Usage: script/test
# Run tests for Enterprise Manage

# Get the GHES Manage SHA
GHES_MANAGE_SHA="${GHES_MANAGE_SHA:-$(cat ../manifest-focal/base-pinned | grep ghes-manage | sed -n 's/.*~\(.*\)-\{1\}\([a-f0-9]*\).*/\2/p')""}"

# Codespaces test output fix https://github.com/docker/compose/issues/8833 </dev/null explanation 
if ! [ -f /.dockerenv ] 2> /dev/null || [ -n "$CODESPACES" ] ; then
  exec env UID=$(id -u) GID=$(id -g) GHES_MANAGE_SHA=$GHES_MANAGE_SHA docker compose -f docker-compose.dependencies.yaml -f docker-compose.build.yaml \
    run --rm  -T build script/test "$@" </dev/null
fi

# force run under bundler
if [ -z "$BUNDLE_BIN_PATH" ]; then
  exec bundle exec "$0" "$@"
fi

set -e

# grab root project dir and change into it
root="$(cd $(dirname "$0")/.. && pwd)"
cd "$root"

if [ -n "$1" ]; then
  RUBYOPT="-W0" ./bin/rake test TEST="$1" TESTOPTS="${@:2}"
else
  ./bin/rake test
fi
