#!/bin/bash
set -e

echo -e "==== Enabling feature flags ===="

# NOTE: toggle-feature-flag supports additional flags via the -F/--flag option
# Keeping this list sorted may help prevent merge conflicts.
bin/toggle-feature-flag enable \
  bogus_placeholder_feature \
  -F alert_prioritization_owner_csv_job_ui \
  -F business_security_center_use_new_sso_banner \
  -F enterprise_teams_enabled_for_organizations \
  -F enterprise_teams_security_manager_sync \
  -F proxima_request_scoping_disabled \
  -F report_missing_tenant \
  -F security_center_backfill_code_scanning_alert_number \
  -F security_center_business_new_advanced_security_policies_survey \
  -F security_center_dashboards_cards_parallel_queries_per_tool \
  -F security_center_dashboards_show_sast_table \
  -F security_center_dashboards_show_secret_scanning_filter \
  -F security_center_dashboards_show_severity_filter \
  -F security_center_dashboards_show_three_tab_dashboard \
  -F security_center_feedback_link \
  -F security_center_overview_dashboard_csv_export \
  -F security_center_show_enterprise_security_manager_assignment_page \
  -F security_center_unified_alerts \
  -F security_overview_analytics_reconciliation_session_duration_factor \
  -F show_repo_id_in_alert_prioritization_experiment_csv \
  -F tenant_header_parsing \
  -F tenant_namespacing \
  --mode verbose

bin/toggle-global-flags --enable
