#!/bin/bash
set -e

# Workaround for hyperscan dependency installation issue on codespaces
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/

tmux_init () {
  tmux new-session -d -s security_center_setup
  tmux set -t security_center_setup pane-border-status top
  tmux send-keys -t security_center_setup "printf '\033]2;%s\033\\' 'FF change'; script/security_center/enable-feature-flags; read" C-m
  tmux split-window -h -t security_center_setup "printf '\033]2;%s\033\\' 'tss setup'; script/setup-codespaces-token-scanning-service; read"
  tmux split-window -h -t security_center_setup "printf '\033]2;%s\033\\' 'turboscan setup'; script/setup-codespaces-turboscan; read"
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t security_center_setup
  else
    echo "# Started security center setup in a new tmux session: security_center_setup"
  fi
}

no_tmux_init() {
  script/security_center/enable-feature-flags &
  script/setup-codespaces-token-scanning-service &
  script/setup-codespaces-turboscan &

  wait
}

case "$1" in
  --no-tmux) no_tmux_init;;
  *) tmux_init;;
esac
