#!/bin/bash
set -e

tmux new-session -d -s security_center_run
tmux set -t security_center_run pane-border-status top
tmux select-layout -t security_center_run tiled
tmux send-keys -t security_center_run "echo 'y' | bin/server" C-m
tmux split-window -t security_center_run "printf '\033]2;%s\033\\' 'sc hydro'; bin/security-center-repository-update-processor"
tmux select-layout -t security_center_run tiled
tmux split-window -t security_center_run "printf '\033]2;%s\033\\' 'tss server'; cd /workspaces/token-scanning-service && script/server"
tmux select-layout -t security_center_run tiled
tmux split-window -t security_center_run "printf '\033]2;%s\033\\' 'tss jobs'; cd /workspaces/token-scanning-service && script/worker"
tmux select-layout -t security_center_run tiled
tmux split-window -t security_center_run "printf '\033]2;%s\033\\' 'tss hydro'; cd /workspaces/token-scanning-service && script/consumer"
tmux select-layout -t security_center_run tiled
tmux split-window -t security_center_run "printf '\033]2;%s\033\\' 'turboscan server'; cd /workspaces/turboscan && script/server"
if [[ -z "$TMUX" ]]; then
  tmux attach-session -t security_center_run
else
  echo "# Started security center run in a new tmux session: security_center_run"
fi
