# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Turboghas::Proto::GetOrganizationsResponse::Organization`.
# Please instead update this file by running `bin/tapioca dsl Turboghas::Proto::GetOrganizationsResponse::Organization`.

class Turboghas::Proto::GetOrganizationsResponse::Organization
  sig do
    params(
      active_committers: T.nilable(Integer),
      id: T.nilable(Integer),
      login: T.nilable(String),
      unique_committers: T.nilable(Integer)
    ).void
  end
  def initialize(active_committers: nil, id: nil, login: nil, unique_committers: nil); end

  sig { returns(Integer) }
  def active_committers; end

  sig { params(value: Integer).void }
  def active_committers=(value); end

  sig { void }
  def clear_active_committers; end

  sig { void }
  def clear_id; end

  sig { void }
  def clear_login; end

  sig { void }
  def clear_unique_committers; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(String) }
  def login; end

  sig { params(value: String).void }
  def login=(value); end

  sig { returns(Integer) }
  def unique_committers; end

  sig { params(value: Integer).void }
  def unique_committers=(value); end
end
