# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration`.

module Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration
  class << self
    sig { returns(Google::Protobuf::EnumDescriptor) }
    def descriptor; end

    sig { params(number: Integer).returns(T.nilable(Symbol)) }
    def lookup(number); end

    sig { params(symbol: Symbol).returns(T.nilable(Integer)) }
    def resolve(symbol); end
  end
end

Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration::SNIPPY_DISABLED = 2
Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration::SNIPPY_ENABLED = 1
Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration::SNIPPY_NO_POLICY = 4
Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration::SNIPPY_UNCONFIGURED = 3
Hydro::Schemas::Github::Copilot::V1::Entities::CopilotSnippyConfiguration::SNIPPY_UNKNOWN = 0
