# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SecurityCenter::SubheadComponent`.
# Please instead update this file by running `bin/tapioca dsl SecurityCenter::SubheadComponent`.

class SecurityCenter::SubheadComponent
  sig { returns(T.untyped) }
  def feedback_link; end

  sig { returns(T::Boolean) }
  def feedback_link?; end

  sig { returns(T.untyped) }
  def phase_label; end

  sig { returns(T::Boolean) }
  def phase_label?; end

  sig { params(args: T.nilable(T::Array[T.untyped]), _arg1: T.untyped, block: T.untyped).returns(T.untyped) }
  def with_feedback_link(*args, **_arg1, &block); end

  sig { params(args: T.nilable(T::Array[T.untyped]), _arg1: T.untyped, block: T.untyped).returns(T.untyped) }
  def with_phase_label(*args, **_arg1, &block); end
end
