# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Hydro::Schemas::Github::Copilot::V2::CopilotPullRequestSummaries`.
# Please instead update this file by running `bin/tapioca dsl Hydro::Schemas::Github::Copilot::V2::CopilotPullRequestSummaries`.

class Hydro::Schemas::Github::Copilot::V2::CopilotPullRequestSummaries
  sig do
    params(
      analytics_tracking_id: T.nilable(String),
      base_revision: T.nilable(String),
      copilot_telemetry_snapshot_id: T.nilable(String),
      head_revision: T.nilable(String),
      repository_id: T.nilable(Integer),
      status: T.nilable(String)
    ).void
  end
  def initialize(analytics_tracking_id: nil, base_revision: nil, copilot_telemetry_snapshot_id: nil, head_revision: nil, repository_id: nil, status: nil); end

  sig { returns(String) }
  def analytics_tracking_id; end

  sig { params(value: String).void }
  def analytics_tracking_id=(value); end

  sig { returns(String) }
  def base_revision; end

  sig { params(value: String).void }
  def base_revision=(value); end

  sig { void }
  def clear_analytics_tracking_id; end

  sig { void }
  def clear_base_revision; end

  sig { void }
  def clear_copilot_telemetry_snapshot_id; end

  sig { void }
  def clear_head_revision; end

  sig { void }
  def clear_repository_id; end

  sig { void }
  def clear_status; end

  sig { returns(String) }
  def copilot_telemetry_snapshot_id; end

  sig { params(value: String).void }
  def copilot_telemetry_snapshot_id=(value); end

  sig { returns(String) }
  def head_revision; end

  sig { params(value: String).void }
  def head_revision=(value); end

  sig { returns(Integer) }
  def repository_id; end

  sig { params(value: Integer).void }
  def repository_id=(value); end

  sig { returns(String) }
  def status; end

  sig { params(value: String).void }
  def status=(value); end
end
