# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `BillingDeleteObsoleteCouponExpirationNoticesJob`.
# Please instead update this file by running `bin/tapioca dsl BillingDeleteObsoleteCouponExpirationNoticesJob`.

class BillingDeleteObsoleteCouponExpirationNoticesJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: BillingDeleteObsoleteCouponExpirationNoticesJob).void)
      ).returns(T.any(BillingDeleteObsoleteCouponExpirationNoticesJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
