# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DisableTwoFactorRequirementJob`.
# Please instead update this file by running `bin/tapioca dsl DisableTwoFactorRequirementJob`.

class DisableTwoFactorRequirementJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: DisableTwoFactorRequirementJob).void)
      ).returns(T.any(DisableTwoFactorRequirementJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
