# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `MirrorSchedulerJob`.
# Please instead update this file by running `bin/tapioca dsl MirrorSchedulerJob`.

class MirrorSchedulerJob
  class << self
    sig do
      params(
        block: T.nilable(T.proc.params(job: MirrorSchedulerJob).void)
      ).returns(T.any(MirrorSchedulerJob, FalseClass))
    end
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
