# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SponsorsBusinessOrgOnboardingJob`.
# Please instead update this file by running `bin/tapioca dsl SponsorsBusinessOrgOnboardingJob`.

class SponsorsBusinessOrgOnboardingJob
  class << self
    sig do
      params(
        organization: T.nilable(::Organization),
        actor: T.nilable(::User),
        block: T.nilable(T.proc.params(job: SponsorsBusinessOrgOnboardingJob).void)
      ).returns(T.any(SponsorsBusinessOrgOnboardingJob, FalseClass))
    end
    def perform_later(organization:, actor:, &block); end

    sig { params(organization: T.nilable(::Organization), actor: T.nilable(::User)).void }
    def perform_now(organization:, actor:); end
  end
end
