# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SyncSponsorsPatreonUserJob`.
# Please instead update this file by running `bin/tapioca dsl SyncSponsorsPatreonUserJob`.

class SyncSponsorsPatreonUserJob
  class << self
    sig do
      params(
        sponsors_patreon_user: ::SponsorsPatreonUser,
        actor: T.nilable(::User),
        block: T.nilable(T.proc.params(job: SyncSponsorsPatreonUserJob).void)
      ).returns(T.any(SyncSponsorsPatreonUserJob, FalseClass))
    end
    def perform_later(sponsors_patreon_user, actor: T.unsafe(nil), &block); end

    sig { params(sponsors_patreon_user: ::SponsorsPatreonUser, actor: T.nilable(::User)).void }
    def perform_now(sponsors_patreon_user, actor: T.unsafe(nil)); end
  end
end
