#!/usr/bin/env ruby
# typed: true
# frozen_string_literal: true

require_relative "telemetry/telemetry"

service = ARGV.shift
action = ARGV.shift

if service.nil? || action.nil?
  puts "Usage: script/report-usage <service> <action>"
  exit 1
end

settings = [DX::Telemetry::USER_TAG, DX::Telemetry::DEVCONTAINER_TAG, DX::Telemetry::RESILIENT]
DX::Telemetry.monitor_script_usage("monolith.#{service}.#{action}", tags: [], settings: settings)
