#!/bin/bash

export OVERMIND_DAEMONIZE=1
script/server "$@"

echo "The GitHub server has been started. To stop it, run \`script/dx/server-stop\`."
echo ""
echo "IMPORTANT: It is possible to view the logs, but leaving the logs open for a longer period of time in \
a terminal window could lead to the same failure states as when running \`script/server\` in a terminal window. \
To have a look at the logs, run \`script/dx/server-logs\` (and make sure to kill that process soon)."
