#!/bin/bash
#
# This script checks out a shallow copy of a remote branch. It is intended for usage after `shallow-clone`.
#
# Usage: shallow-checkout <branch> [<depth>]
# Arguments:
#  - branch: The remote branch to check out.
#  - depth: The number of commits to check out, defaults to 1.
#
# Note that this shallow checkout does not necessarily contain the whole history of the remote branch.

set -e

branch=$1
depth=${2:-1}

if [ -z "${branch}" ]; then
  echo "Missing argument: branch"
  exit 1
fi

git remote set-branches origin "${branch}"
git fetch --depth "${depth}" origin "${branch}"
git checkout "${branch}"
