#!/bin/bash
#
# This script will execute a git pull with the --shallow-since flag to include all reachable commits <days> ago on the current branch. 
#
# Usage: shallow-pull <days>
# Arguments:
#  - days: The number of days for the history, defaults to 30.
#
# Note that shallow-pull is only intended to be used on shallow repositiories.

set -e

days="${1:-30}"
git pull --shallow-since=$(date --date="${days} day ago" +%Y-%m-%d) origin $(git branch --show-current)
