#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
cd $SCRIPT_DIR/../..

images=$(jq -r 'to_entries | .[] | "\(.key) \(.value)"' ./script/dx/subproject-to-image-map.json)
echo "$images" | while read -r version_file image; do
  sha=$(cat $version_file | grep -v '^#')
  tagged_image="$image:$sha"
  # The no-op pull for this many existing image is noticably slow; use grep to skip it (30s vs 300ms)
  if ! docker images --format '{{.Repository}}:{{.Tag}}' | grep "$tagged_image"; then
    echo "Pulling $tagged_image"
    docker pull "$tagged_image"
  else
    echo "${tagged_image} already present"
  fi
done
