# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `S4::Api::V1::MetricsReq`.
# Please instead update this file by running `bin/tapioca dsl S4::Api::V1::MetricsReq`.

class S4::Api::V1::MetricsReq
  sig do
    params(
      accept: T.nilable(T.any(Symbol, Integer)),
      date_end: T.nilable(Integer),
      date_start: T.nilable(Integer),
      owner_id: T.nilable(String)
    ).void
  end
  def initialize(accept: nil, date_end: nil, date_start: nil, owner_id: nil); end

  sig { returns(T.any(Symbol, Integer)) }
  def accept; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def accept=(value); end

  sig { void }
  def clear_accept; end

  sig { void }
  def clear_date_end; end

  sig { void }
  def clear_date_start; end

  sig { void }
  def clear_owner_id; end

  sig { returns(Integer) }
  def date_end; end

  sig { params(value: Integer).void }
  def date_end=(value); end

  sig { returns(Integer) }
  def date_start; end

  sig { params(value: Integer).void }
  def date_start=(value); end

  sig { returns(String) }
  def owner_id; end

  sig { params(value: String).void }
  def owner_id=(value); end
end
