#!/bin/bash

git config --global credential.helper store
echo "https://git:$GITHUB_TOKEN@github.com" >> "$HOME/.git-credentials"
chmod 400 "$HOME/.git-credentials"
git config --global url."https://github.com/".insteadOf git@github.com:
