#!/bin/bash
# Usage: script/ci/generate-erblint-data

# Find gem path
PVC_PATH=$(bin/bundle info primer_view_components --path)/lib/primer/view_components/linters
# Get all `Counter` linters as a comma separated list
LINTERS=$(find $PVC_PATH/*_counter.rb -type f -iname "*.rb" -execdir basename {} .rb ';' | tr '\n' ',' | sed 's/,$/\n/')
# Run erblint using all pvc linters
DUMP_LINT_DATA=1 bin/bundle exec erblint --format json --enable-linters $LINTERS app/views app/components packages/**/app/components app/forms/**/

exit 0
