#!/bin/bash
if [[ $(ls -A $ARTIFACTS_DIR/*.dump 2> /dev/null) ]]; then
  find $ARTIFACTS_DIR/ -name '*.dump' -print >/tmp/stackprof.list
  tar -czf "$ARTIFACTS_DIR/stackprof-$(hostname -s).tgz" -T /tmp/stackprof.list
  find $ARTIFACTS_DIR/ -name '*.dump' | xargs rm
fi
