#!/bin/bash
# Usage: script/ci/vtcombo-up
#
set -e

# VTCombo can be slow to start against large databases, so
# if we have disabled vitess don't even start vtcombo, see
# https://github.com/github/data-patterns-and-scaling/issues/54
# for more information
if [ -n "$DISABLE_VITESS" ]; then
  echo "Not starting vtcombo as DISABLE_VITESS is set"
  exit 0
fi

echo "SET GLOBAL max_connections = 10000;" | mysql -u root

mysql_version=$(mysql -u root --batch --skip-column-names --execute "SELECT VERSION()")

exec /sbin/start-stop-daemon --start \
  --pidfile $(pwd)/tmp/vtcombo.pid \
  --background \
  --exec $(pwd)/vendor/vitess/bin/vtcombo -- \
  --pid_file $(pwd)/tmp/vtcombo.pid \
  --alsologtostderr=true \
  --log_dir $(pwd)/tmp \
  --proto_topo "$(cat db/topology)" \
  --schema_dir "$(pwd)/tmp/vtcombo" \
  --mysql_server_port 15306 \
  --mysql_server_bind_address 0.0.0.0 \
  --mysql_auth_server_impl none \
  --mysql_server_version "$mysql_version" \
  --db_socket /var/run/mysqld/mysqld.sock \
  --db_host localhost \
  --mycnf-file /etc/mysql/mysql.cnf \
  --db_app_user root \
  --db_allprivs_user root \
  --db_appdebug_user root \
  --db_dba_user root \
  --db_repl_user root \
  --dbddl_plugin vttest \
  --queryserver-config-query-timeout 300 \
  --queryserver-config-transaction-timeout 300 \
  --queryserver-config-transaction-cap 10  \
  --queryserver-config-pool-size 10 \
  --queryserver-enable-settings-pool \
  --enforce_strict_trans_tables=false \
  --port 15000 \
  --grpc_port 15001 \
  --service_map 'grpc-vtgateservice,grpc-vtctl,grpc-vtctld' \
  --db_charset utf8mb4_general_ci \
  --vschema_ddl_authorized_users='%' \
  --planner-version=gen4 \
  --health_check_interval 1s \
  --tablet_refresh_interval 1s \
  --tablet_types_to_wait 'PRIMARY' \
  --schema_change_signal=false \
  --queryserver-config-schema-change-signal=false \
  --disable_active_reparents
