#!/bin/bash
#/ Usage:
#/    validate_uuid <uuid>
#/
#/ Description:
#/    Validates that the provided uuid has the following format:
#/    dd718d08-5bed-11ee-8d14-0621d2c20601
#/
#/    Exits 0 if the uuid is valid. Exits 1 otherwise.

usage() {
  grep '^#/' <"$0" | cut -c 4-
}

if [ $# -ne 1 ]; then
  echo "validate_uuid accepts a single argument."
  usage
  exit 1
fi

uuid="$1"

pattern='^\{?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\}?$'
if [[ $uuid =~ $pattern ]]; then
  exit 0
else
  echo "error: invalid UUID. Sample UUID format: dd718d08-5bed-11ee-8d14-0621d2c20601" >&2
  exit 1
fi
