#!/bin/bash
#/ verbose-utils is a helper script to configure verbose output of shell scripts.

# create clones of stdout and stderr
exec {orig_stdout}>&1
exec {orig_stderr}>&2

# disable_verbose_mode performs I/O redirection to silence stdout and stderr.
disable_verbose_mode() {
  exec 1>/dev/null
  exec 2>/dev/null
}

# enable_verbose_mode performs I/O redirection to re-enable stdout and stderr.
enable_verbose_mode() {
  exec 1>&$orig_stdout
  exec 2>&$orig_stderr
}

# shout always prints to stdout, regardless of verbose mode
shout() {
  >&$orig_stdout echo -e "$@"
}

# shout_err always prints to stderr, regardless of verbose mode
shout_err() {
  >&$orig_stderr echo -e "$@"
}
