// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
/* eslint eslint-comments/no-use: off */
/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */

declare namespace EnterpriseCloudSummaryModuleCssNamespace {
  export interface IEnterpriseCloudSummaryModuleCss {
    bannerDismissButton: string
    gap6: string
    lineHeightSpacious: string
    warnFooter: string
  }
}

declare const EnterpriseCloudSummaryModuleCssModule: EnterpriseCloudSummaryModuleCssNamespace.IEnterpriseCloudSummaryModuleCss

export = EnterpriseCloudSummaryModuleCssModule
