# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GitHub::HostedComputeIms::ImagesApi::ImageDefinition`.
# Please instead update this file by running `bin/tapioca dsl GitHub::HostedComputeIms::ImagesApi::ImageDefinition`.

class GitHub::HostedComputeIms::ImagesApi::ImageDefinition
  sig do
    params(
      architecture: T.nilable(T.any(Symbol, Integer)),
      id: T.nilable(Integer),
      latest_version: T.nilable(String),
      name: T.nilable(String),
      os_type: T.nilable(T.any(Symbol, Integer))
    ).void
  end
  def initialize(architecture: nil, id: nil, latest_version: nil, name: nil, os_type: nil); end

  sig { returns(T.any(Symbol, Integer)) }
  def architecture; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def architecture=(value); end

  sig { void }
  def clear_architecture; end

  sig { void }
  def clear_id; end

  sig { void }
  def clear_latest_version; end

  sig { void }
  def clear_name; end

  sig { void }
  def clear_os_type; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: Integer).void }
  def id=(value); end

  sig { returns(String) }
  def latest_version; end

  sig { params(value: String).void }
  def latest_version=(value); end

  sig { returns(String) }
  def name; end

  sig { params(value: String).void }
  def name=(value); end

  sig { returns(T.any(Symbol, Integer)) }
  def os_type; end

  sig { params(value: T.any(Symbol, Integer)).void }
  def os_type=(value); end
end
