# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Github::DependencySnapshotsApi::TimeoutResponse`.
# Please instead update this file by running `bin/tapioca dsl Github::DependencySnapshotsApi::TimeoutResponse`.

class Github::DependencySnapshotsApi::TimeoutResponse
  sig { void }
  def initialize; end
end
